// Generated by tools/generate.ts; do not edit by hand.

// The round constants in the bit-interleaved form of the state, as (even, odd) halves.
const ROUND_CONSTANTS = new Int32Array([
  0x00000001, 0x00000000, 0x00000000, 0x00000089, 0x00000000, 0x8000008b, 0x00000000, 0x80008080,
  0x00000001, 0x0000008b, 0x00000001, 0x00008000, 0x00000001, 0x80008088, 0x00000001, 0x80000082,
  0x00000000, 0x0000000b, 0x00000000, 0x0000000a, 0x00000001, 0x00008082, 0x00000000, 0x00008003,
  0x00000001, 0x0000808b, 0x00000001, 0x8000000b, 0x00000001, 0x8000008a, 0x00000001, 0x80000081,
  0x00000000, 0x80000081, 0x00000000, 0x80000008, 0x00000000, 0x00000083, 0x00000000, 0x80008003,
  0x00000001, 0x80008088, 0x00000000, 0x80000088, 0x00000001, 0x00008000, 0x00000000, 0x80008082,
]);

// Keccak-f[1600] on a bit-interleaved state: lane i is s[2i], holding its even-numbered bits, and
// s[2i + 1], holding its odd-numbered bits. A 64-bit rotation is then two 32-bit rotations, which V8
// compiles to single instructions. Lane x + 5y is a{x + 5y}; rho and pi move it to
// b{y + 5((2x + 3y) mod 5)}. Each iteration runs two rounds, which halves the register shuffling at
// the loop's back edge.
export function permute(s: Uint32Array): void {
  let a0e = s[0] | 0;

  let a0o = s[1] | 0;

  let a1e = s[2] | 0;

  let a1o = s[3] | 0;

  let a2e = s[4] | 0;

  let a2o = s[5] | 0;

  let a3e = s[6] | 0;

  let a3o = s[7] | 0;

  let a4e = s[8] | 0;

  let a4o = s[9] | 0;

  let a5e = s[10] | 0;

  let a5o = s[11] | 0;

  let a6e = s[12] | 0;

  let a6o = s[13] | 0;

  let a7e = s[14] | 0;

  let a7o = s[15] | 0;

  let a8e = s[16] | 0;

  let a8o = s[17] | 0;

  let a9e = s[18] | 0;

  let a9o = s[19] | 0;

  let a10e = s[20] | 0;

  let a10o = s[21] | 0;

  let a11e = s[22] | 0;

  let a11o = s[23] | 0;

  let a12e = s[24] | 0;

  let a12o = s[25] | 0;

  let a13e = s[26] | 0;

  let a13o = s[27] | 0;

  let a14e = s[28] | 0;

  let a14o = s[29] | 0;

  let a15e = s[30] | 0;

  let a15o = s[31] | 0;

  let a16e = s[32] | 0;

  let a16o = s[33] | 0;

  let a17e = s[34] | 0;

  let a17o = s[35] | 0;

  let a18e = s[36] | 0;

  let a18o = s[37] | 0;

  let a19e = s[38] | 0;

  let a19o = s[39] | 0;

  let a20e = s[40] | 0;

  let a20o = s[41] | 0;

  let a21e = s[42] | 0;

  let a21o = s[43] | 0;

  let a22e = s[44] | 0;

  let a22o = s[45] | 0;

  let a23e = s[46] | 0;

  let a23o = s[47] | 0;

  let a24e = s[48] | 0;

  let a24o = s[49] | 0;

  let c0e = 0;

  let c0o = 0;

  let c1e = 0;

  let c1o = 0;

  let c2e = 0;

  let c2o = 0;

  let c3e = 0;

  let c3o = 0;

  let c4e = 0;

  let c4o = 0;

  let d = 0;

  let b0e = 0;

  let b0o = 0;

  let b1e = 0;

  let b1o = 0;

  let b2e = 0;

  let b2o = 0;

  let b3e = 0;

  let b3o = 0;

  let b4e = 0;

  let b4o = 0;

  let b5e = 0;

  let b5o = 0;

  let b6e = 0;

  let b6o = 0;

  let b7e = 0;

  let b7o = 0;

  let b8e = 0;

  let b8o = 0;

  let b9e = 0;

  let b9o = 0;

  let b10e = 0;

  let b10o = 0;

  let b11e = 0;

  let b11o = 0;

  let b12e = 0;

  let b12o = 0;

  let b13e = 0;

  let b13o = 0;

  let b14e = 0;

  let b14o = 0;

  let b15e = 0;

  let b15o = 0;

  let b16e = 0;

  let b16o = 0;

  let b17e = 0;

  let b17o = 0;

  let b18e = 0;

  let b18o = 0;

  let b19e = 0;

  let b19o = 0;

  let b20e = 0;

  let b20o = 0;

  let b21e = 0;

  let b21o = 0;

  let b22e = 0;

  let b22o = 0;

  let b23e = 0;

  let b23o = 0;

  let b24e = 0;

  let b24o = 0;

  for (let round = 0; round < 48; round += 4) {
    c0e = a0e ^ a5e ^ a10e ^ a15e ^ a20e;

    c0o = a0o ^ a5o ^ a10o ^ a15o ^ a20o;

    c1e = a1e ^ a6e ^ a11e ^ a16e ^ a21e;

    c1o = a1o ^ a6o ^ a11o ^ a16o ^ a21o;

    c2e = a2e ^ a7e ^ a12e ^ a17e ^ a22e;

    c2o = a2o ^ a7o ^ a12o ^ a17o ^ a22o;

    c3e = a3e ^ a8e ^ a13e ^ a18e ^ a23e;

    c3o = a3o ^ a8o ^ a13o ^ a18o ^ a23o;

    c4e = a4e ^ a9e ^ a14e ^ a19e ^ a24e;

    c4o = a4o ^ a9o ^ a14o ^ a19o ^ a24o;

    d = c4e ^ ((c1o << 1) | (c1o >>> 31));

    a0e ^= d;

    a5e ^= d;

    a10e ^= d;

    a15e ^= d;

    a20e ^= d;

    d = c4o ^ c1e;

    a0o ^= d;

    a5o ^= d;

    a10o ^= d;

    a15o ^= d;

    a20o ^= d;

    d = c0e ^ ((c2o << 1) | (c2o >>> 31));

    a1e ^= d;

    a6e ^= d;

    a11e ^= d;

    a16e ^= d;

    a21e ^= d;

    d = c0o ^ c2e;

    a1o ^= d;

    a6o ^= d;

    a11o ^= d;

    a16o ^= d;

    a21o ^= d;

    d = c1e ^ ((c3o << 1) | (c3o >>> 31));

    a2e ^= d;

    a7e ^= d;

    a12e ^= d;

    a17e ^= d;

    a22e ^= d;

    d = c1o ^ c3e;

    a2o ^= d;

    a7o ^= d;

    a12o ^= d;

    a17o ^= d;

    a22o ^= d;

    d = c2e ^ ((c4o << 1) | (c4o >>> 31));

    a3e ^= d;

    a8e ^= d;

    a13e ^= d;

    a18e ^= d;

    a23e ^= d;

    d = c2o ^ c4e;

    a3o ^= d;

    a8o ^= d;

    a13o ^= d;

    a18o ^= d;

    a23o ^= d;

    d = c3e ^ ((c0o << 1) | (c0o >>> 31));

    a4e ^= d;

    a9e ^= d;

    a14e ^= d;

    a19e ^= d;

    a24e ^= d;

    d = c3o ^ c0e;

    a4o ^= d;

    a9o ^= d;

    a14o ^= d;

    a19o ^= d;

    a24o ^= d;

    b0e = a0e;

    b0o = a0o;

    b1e = (a6e << 22) | (a6e >>> 10);

    b1o = (a6o << 22) | (a6o >>> 10);

    b2e = (a12o << 22) | (a12o >>> 10);

    b2o = (a12e << 21) | (a12e >>> 11);

    b3e = (a18o << 11) | (a18o >>> 21);

    b3o = (a18e << 10) | (a18e >>> 22);

    b4e = (a24e << 7) | (a24e >>> 25);

    b4o = (a24o << 7) | (a24o >>> 25);

    b5e = (a3e << 14) | (a3e >>> 18);

    b5o = (a3o << 14) | (a3o >>> 18);

    b6e = (a9e << 10) | (a9e >>> 22);

    b6o = (a9o << 10) | (a9o >>> 22);

    b7e = (a10o << 2) | (a10o >>> 30);

    b7o = (a10e << 1) | (a10e >>> 31);

    b8e = (a16o << 23) | (a16o >>> 9);

    b8o = (a16e << 22) | (a16e >>> 10);

    b9e = (a22o << 31) | (a22o >>> 1);

    b9o = (a22e << 30) | (a22e >>> 2);

    b10e = (a1o << 1) | (a1o >>> 31);

    b10o = a1e;

    b11e = (a7e << 3) | (a7e >>> 29);

    b11o = (a7o << 3) | (a7o >>> 29);

    b12e = (a13o << 13) | (a13o >>> 19);

    b12o = (a13e << 12) | (a13e >>> 20);

    b13e = (a19e << 4) | (a19e >>> 28);

    b13o = (a19o << 4) | (a19o >>> 28);

    b14e = (a20e << 9) | (a20e >>> 23);

    b14o = (a20o << 9) | (a20o >>> 23);

    b15e = (a4o << 14) | (a4o >>> 18);

    b15o = (a4e << 13) | (a4e >>> 19);

    b16e = (a5e << 18) | (a5e >>> 14);

    b16o = (a5o << 18) | (a5o >>> 14);

    b17e = (a11e << 5) | (a11e >>> 27);

    b17o = (a11o << 5) | (a11o >>> 27);

    b18e = (a17o << 8) | (a17o >>> 24);

    b18o = (a17e << 7) | (a17e >>> 25);

    b19e = (a23e << 28) | (a23e >>> 4);

    b19o = (a23o << 28) | (a23o >>> 4);

    b20e = (a2e << 31) | (a2e >>> 1);

    b20o = (a2o << 31) | (a2o >>> 1);

    b21e = (a8o << 28) | (a8o >>> 4);

    b21o = (a8e << 27) | (a8e >>> 5);

    b22e = (a14o << 20) | (a14o >>> 12);

    b22o = (a14e << 19) | (a14e >>> 13);

    b23e = (a15o << 21) | (a15o >>> 11);

    b23o = (a15e << 20) | (a15e >>> 12);

    b24e = (a21e << 1) | (a21e >>> 31);

    b24o = (a21o << 1) | (a21o >>> 31);

    a0e = b0e ^ (~b1e & b2e) ^ ROUND_CONSTANTS[round];

    a0o = b0o ^ (~b1o & b2o) ^ ROUND_CONSTANTS[round + 1];

    a1e = b1e ^ (~b2e & b3e);

    a1o = b1o ^ (~b2o & b3o);

    a2e = b2e ^ (~b3e & b4e);

    a2o = b2o ^ (~b3o & b4o);

    a3e = b3e ^ (~b4e & b0e);

    a3o = b3o ^ (~b4o & b0o);

    a4e = b4e ^ (~b0e & b1e);

    a4o = b4o ^ (~b0o & b1o);

    a5e = b5e ^ (~b6e & b7e);

    a5o = b5o ^ (~b6o & b7o);

    a6e = b6e ^ (~b7e & b8e);

    a6o = b6o ^ (~b7o & b8o);

    a7e = b7e ^ (~b8e & b9e);

    a7o = b7o ^ (~b8o & b9o);

    a8e = b8e ^ (~b9e & b5e);

    a8o = b8o ^ (~b9o & b5o);

    a9e = b9e ^ (~b5e & b6e);

    a9o = b9o ^ (~b5o & b6o);

    a10e = b10e ^ (~b11e & b12e);

    a10o = b10o ^ (~b11o & b12o);

    a11e = b11e ^ (~b12e & b13e);

    a11o = b11o ^ (~b12o & b13o);

    a12e = b12e ^ (~b13e & b14e);

    a12o = b12o ^ (~b13o & b14o);

    a13e = b13e ^ (~b14e & b10e);

    a13o = b13o ^ (~b14o & b10o);

    a14e = b14e ^ (~b10e & b11e);

    a14o = b14o ^ (~b10o & b11o);

    a15e = b15e ^ (~b16e & b17e);

    a15o = b15o ^ (~b16o & b17o);

    a16e = b16e ^ (~b17e & b18e);

    a16o = b16o ^ (~b17o & b18o);

    a17e = b17e ^ (~b18e & b19e);

    a17o = b17o ^ (~b18o & b19o);

    a18e = b18e ^ (~b19e & b15e);

    a18o = b18o ^ (~b19o & b15o);

    a19e = b19e ^ (~b15e & b16e);

    a19o = b19o ^ (~b15o & b16o);

    a20e = b20e ^ (~b21e & b22e);

    a20o = b20o ^ (~b21o & b22o);

    a21e = b21e ^ (~b22e & b23e);

    a21o = b21o ^ (~b22o & b23o);

    a22e = b22e ^ (~b23e & b24e);

    a22o = b22o ^ (~b23o & b24o);

    a23e = b23e ^ (~b24e & b20e);

    a23o = b23o ^ (~b24o & b20o);

    a24e = b24e ^ (~b20e & b21e);

    a24o = b24o ^ (~b20o & b21o);

    c0e = a0e ^ a5e ^ a10e ^ a15e ^ a20e;

    c0o = a0o ^ a5o ^ a10o ^ a15o ^ a20o;

    c1e = a1e ^ a6e ^ a11e ^ a16e ^ a21e;

    c1o = a1o ^ a6o ^ a11o ^ a16o ^ a21o;

    c2e = a2e ^ a7e ^ a12e ^ a17e ^ a22e;

    c2o = a2o ^ a7o ^ a12o ^ a17o ^ a22o;

    c3e = a3e ^ a8e ^ a13e ^ a18e ^ a23e;

    c3o = a3o ^ a8o ^ a13o ^ a18o ^ a23o;

    c4e = a4e ^ a9e ^ a14e ^ a19e ^ a24e;

    c4o = a4o ^ a9o ^ a14o ^ a19o ^ a24o;

    d = c4e ^ ((c1o << 1) | (c1o >>> 31));

    a0e ^= d;

    a5e ^= d;

    a10e ^= d;

    a15e ^= d;

    a20e ^= d;

    d = c4o ^ c1e;

    a0o ^= d;

    a5o ^= d;

    a10o ^= d;

    a15o ^= d;

    a20o ^= d;

    d = c0e ^ ((c2o << 1) | (c2o >>> 31));

    a1e ^= d;

    a6e ^= d;

    a11e ^= d;

    a16e ^= d;

    a21e ^= d;

    d = c0o ^ c2e;

    a1o ^= d;

    a6o ^= d;

    a11o ^= d;

    a16o ^= d;

    a21o ^= d;

    d = c1e ^ ((c3o << 1) | (c3o >>> 31));

    a2e ^= d;

    a7e ^= d;

    a12e ^= d;

    a17e ^= d;

    a22e ^= d;

    d = c1o ^ c3e;

    a2o ^= d;

    a7o ^= d;

    a12o ^= d;

    a17o ^= d;

    a22o ^= d;

    d = c2e ^ ((c4o << 1) | (c4o >>> 31));

    a3e ^= d;

    a8e ^= d;

    a13e ^= d;

    a18e ^= d;

    a23e ^= d;

    d = c2o ^ c4e;

    a3o ^= d;

    a8o ^= d;

    a13o ^= d;

    a18o ^= d;

    a23o ^= d;

    d = c3e ^ ((c0o << 1) | (c0o >>> 31));

    a4e ^= d;

    a9e ^= d;

    a14e ^= d;

    a19e ^= d;

    a24e ^= d;

    d = c3o ^ c0e;

    a4o ^= d;

    a9o ^= d;

    a14o ^= d;

    a19o ^= d;

    a24o ^= d;

    b0e = a0e;

    b0o = a0o;

    b1e = (a6e << 22) | (a6e >>> 10);

    b1o = (a6o << 22) | (a6o >>> 10);

    b2e = (a12o << 22) | (a12o >>> 10);

    b2o = (a12e << 21) | (a12e >>> 11);

    b3e = (a18o << 11) | (a18o >>> 21);

    b3o = (a18e << 10) | (a18e >>> 22);

    b4e = (a24e << 7) | (a24e >>> 25);

    b4o = (a24o << 7) | (a24o >>> 25);

    b5e = (a3e << 14) | (a3e >>> 18);

    b5o = (a3o << 14) | (a3o >>> 18);

    b6e = (a9e << 10) | (a9e >>> 22);

    b6o = (a9o << 10) | (a9o >>> 22);

    b7e = (a10o << 2) | (a10o >>> 30);

    b7o = (a10e << 1) | (a10e >>> 31);

    b8e = (a16o << 23) | (a16o >>> 9);

    b8o = (a16e << 22) | (a16e >>> 10);

    b9e = (a22o << 31) | (a22o >>> 1);

    b9o = (a22e << 30) | (a22e >>> 2);

    b10e = (a1o << 1) | (a1o >>> 31);

    b10o = a1e;

    b11e = (a7e << 3) | (a7e >>> 29);

    b11o = (a7o << 3) | (a7o >>> 29);

    b12e = (a13o << 13) | (a13o >>> 19);

    b12o = (a13e << 12) | (a13e >>> 20);

    b13e = (a19e << 4) | (a19e >>> 28);

    b13o = (a19o << 4) | (a19o >>> 28);

    b14e = (a20e << 9) | (a20e >>> 23);

    b14o = (a20o << 9) | (a20o >>> 23);

    b15e = (a4o << 14) | (a4o >>> 18);

    b15o = (a4e << 13) | (a4e >>> 19);

    b16e = (a5e << 18) | (a5e >>> 14);

    b16o = (a5o << 18) | (a5o >>> 14);

    b17e = (a11e << 5) | (a11e >>> 27);

    b17o = (a11o << 5) | (a11o >>> 27);

    b18e = (a17o << 8) | (a17o >>> 24);

    b18o = (a17e << 7) | (a17e >>> 25);

    b19e = (a23e << 28) | (a23e >>> 4);

    b19o = (a23o << 28) | (a23o >>> 4);

    b20e = (a2e << 31) | (a2e >>> 1);

    b20o = (a2o << 31) | (a2o >>> 1);

    b21e = (a8o << 28) | (a8o >>> 4);

    b21o = (a8e << 27) | (a8e >>> 5);

    b22e = (a14o << 20) | (a14o >>> 12);

    b22o = (a14e << 19) | (a14e >>> 13);

    b23e = (a15o << 21) | (a15o >>> 11);

    b23o = (a15e << 20) | (a15e >>> 12);

    b24e = (a21e << 1) | (a21e >>> 31);

    b24o = (a21o << 1) | (a21o >>> 31);

    a0e = b0e ^ (~b1e & b2e) ^ ROUND_CONSTANTS[round + 2];

    a0o = b0o ^ (~b1o & b2o) ^ ROUND_CONSTANTS[round + 2 + 1];

    a1e = b1e ^ (~b2e & b3e);

    a1o = b1o ^ (~b2o & b3o);

    a2e = b2e ^ (~b3e & b4e);

    a2o = b2o ^ (~b3o & b4o);

    a3e = b3e ^ (~b4e & b0e);

    a3o = b3o ^ (~b4o & b0o);

    a4e = b4e ^ (~b0e & b1e);

    a4o = b4o ^ (~b0o & b1o);

    a5e = b5e ^ (~b6e & b7e);

    a5o = b5o ^ (~b6o & b7o);

    a6e = b6e ^ (~b7e & b8e);

    a6o = b6o ^ (~b7o & b8o);

    a7e = b7e ^ (~b8e & b9e);

    a7o = b7o ^ (~b8o & b9o);

    a8e = b8e ^ (~b9e & b5e);

    a8o = b8o ^ (~b9o & b5o);

    a9e = b9e ^ (~b5e & b6e);

    a9o = b9o ^ (~b5o & b6o);

    a10e = b10e ^ (~b11e & b12e);

    a10o = b10o ^ (~b11o & b12o);

    a11e = b11e ^ (~b12e & b13e);

    a11o = b11o ^ (~b12o & b13o);

    a12e = b12e ^ (~b13e & b14e);

    a12o = b12o ^ (~b13o & b14o);

    a13e = b13e ^ (~b14e & b10e);

    a13o = b13o ^ (~b14o & b10o);

    a14e = b14e ^ (~b10e & b11e);

    a14o = b14o ^ (~b10o & b11o);

    a15e = b15e ^ (~b16e & b17e);

    a15o = b15o ^ (~b16o & b17o);

    a16e = b16e ^ (~b17e & b18e);

    a16o = b16o ^ (~b17o & b18o);

    a17e = b17e ^ (~b18e & b19e);

    a17o = b17o ^ (~b18o & b19o);

    a18e = b18e ^ (~b19e & b15e);

    a18o = b18o ^ (~b19o & b15o);

    a19e = b19e ^ (~b15e & b16e);

    a19o = b19o ^ (~b15o & b16o);

    a20e = b20e ^ (~b21e & b22e);

    a20o = b20o ^ (~b21o & b22o);

    a21e = b21e ^ (~b22e & b23e);

    a21o = b21o ^ (~b22o & b23o);

    a22e = b22e ^ (~b23e & b24e);

    a22o = b22o ^ (~b23o & b24o);

    a23e = b23e ^ (~b24e & b20e);

    a23o = b23o ^ (~b24o & b20o);

    a24e = b24e ^ (~b20e & b21e);

    a24o = b24o ^ (~b20o & b21o);
  }

  s[0] = a0e;

  s[1] = a0o;

  s[2] = a1e;

  s[3] = a1o;

  s[4] = a2e;

  s[5] = a2o;

  s[6] = a3e;

  s[7] = a3o;

  s[8] = a4e;

  s[9] = a4o;

  s[10] = a5e;

  s[11] = a5o;

  s[12] = a6e;

  s[13] = a6o;

  s[14] = a7e;

  s[15] = a7o;

  s[16] = a8e;

  s[17] = a8o;

  s[18] = a9e;

  s[19] = a9o;

  s[20] = a10e;

  s[21] = a10o;

  s[22] = a11e;

  s[23] = a11o;

  s[24] = a12e;

  s[25] = a12o;

  s[26] = a13e;

  s[27] = a13o;

  s[28] = a14e;

  s[29] = a14o;

  s[30] = a15e;

  s[31] = a15o;

  s[32] = a16e;

  s[33] = a16o;

  s[34] = a17e;

  s[35] = a17o;

  s[36] = a18e;

  s[37] = a18o;

  s[38] = a19e;

  s[39] = a19o;

  s[40] = a20e;

  s[41] = a20o;

  s[42] = a21e;

  s[43] = a21o;

  s[44] = a22e;

  s[45] = a22o;

  s[46] = a23e;

  s[47] = a23o;

  s[48] = a24e;

  s[49] = a24o;
}
