// Generated by tools/generate.ts; do not edit by hand.

// FIPS 204 SimpleBitPack (Algorithm 16) and BitPack (Algorithm 17) of the 256 coefficients of w into
// out at offset, eight coefficients at a time: eight b-bit values fill exactly b bytes. BitPack stores
// b - w[i], which lies in [0, 2^bits) for coefficients in [-a, b].
export function simpleBitPack10(w: Int32Array, out: Uint8Array, offset: number): void {
  for (let i = 0, o = offset; i < 256; i += 8, o += 10) {
    const a0 = w[i];

    const a1 = w[i + 1];

    const a2 = w[i + 2];

    const a3 = w[i + 3];

    const a4 = w[i + 4];

    const a5 = w[i + 5];

    const a6 = w[i + 6];

    const a7 = w[i + 7];

    out[o] = a0;

    out[o + 1] = (a0 >> 8) | (a1 << 2);

    out[o + 2] = (a1 >> 6) | (a2 << 4);

    out[o + 3] = (a2 >> 4) | (a3 << 6);

    out[o + 4] = a3 >> 2;

    out[o + 5] = a4;

    out[o + 6] = (a4 >> 8) | (a5 << 2);

    out[o + 7] = (a5 >> 6) | (a6 << 4);

    out[o + 8] = (a6 >> 4) | (a7 << 6);

    out[o + 9] = a7 >> 2;
  }
}

export function bitPack3(w: Int32Array, b: number, out: Uint8Array, offset: number): void {
  for (let i = 0, o = offset; i < 256; i += 8, o += 3) {
    const a0 = b - w[i];

    const a1 = b - w[i + 1];

    const a2 = b - w[i + 2];

    const a3 = b - w[i + 3];

    const a4 = b - w[i + 4];

    const a5 = b - w[i + 5];

    const a6 = b - w[i + 6];

    const a7 = b - w[i + 7];

    out[o] = a0 | (a1 << 3) | (a2 << 6);

    out[o + 1] = (a2 >> 2) | (a3 << 1) | (a4 << 4) | (a5 << 7);

    out[o + 2] = (a5 >> 1) | (a6 << 2) | (a7 << 5);
  }
}

export function bitPack4(w: Int32Array, b: number, out: Uint8Array, offset: number): void {
  for (let i = 0, o = offset; i < 256; i += 8, o += 4) {
    const a0 = b - w[i];

    const a1 = b - w[i + 1];

    const a2 = b - w[i + 2];

    const a3 = b - w[i + 3];

    const a4 = b - w[i + 4];

    const a5 = b - w[i + 5];

    const a6 = b - w[i + 6];

    const a7 = b - w[i + 7];

    out[o] = a0 | (a1 << 4);

    out[o + 1] = a2 | (a3 << 4);

    out[o + 2] = a4 | (a5 << 4);

    out[o + 3] = a6 | (a7 << 4);
  }
}

export function bitPack13(w: Int32Array, b: number, out: Uint8Array, offset: number): void {
  for (let i = 0, o = offset; i < 256; i += 8, o += 13) {
    const a0 = b - w[i];

    const a1 = b - w[i + 1];

    const a2 = b - w[i + 2];

    const a3 = b - w[i + 3];

    const a4 = b - w[i + 4];

    const a5 = b - w[i + 5];

    const a6 = b - w[i + 6];

    const a7 = b - w[i + 7];

    out[o] = a0;

    out[o + 1] = (a0 >> 8) | (a1 << 5);

    out[o + 2] = a1 >> 3;

    out[o + 3] = (a1 >> 11) | (a2 << 2);

    out[o + 4] = (a2 >> 6) | (a3 << 7);

    out[o + 5] = a3 >> 1;

    out[o + 6] = (a3 >> 9) | (a4 << 4);

    out[o + 7] = a4 >> 4;

    out[o + 8] = (a4 >> 12) | (a5 << 1);

    out[o + 9] = (a5 >> 7) | (a6 << 6);

    out[o + 10] = a6 >> 2;

    out[o + 11] = (a6 >> 10) | (a7 << 3);

    out[o + 12] = a7 >> 5;
  }
}
