// Generated by tools/generate.ts; do not edit by hand.

const LIMB = 65536;

const LIMB_INVERSE = 2 ** -16;

// The product, unrolled into one sum per limb with the terms of weight 2^256 and above folded in as
// 2^256 = 38. Inputs have limbs below 2^19 in magnitude, so a sum stays below 2^48 and exact. One
// full carry pass leaves every limb in [0, 2^16) except the first, which can reach 2^32; carrying it
// twice more brings every limb into [-1, 2^16], as two full passes would.
export function multiply(o: Float64Array, a: Float64Array, b: Float64Array): void {
  const a0 = a[0];

  const a1 = a[1];

  const a2 = a[2];

  const a3 = a[3];

  const a4 = a[4];

  const a5 = a[5];

  const a6 = a[6];

  const a7 = a[7];

  const a8 = a[8];

  const a9 = a[9];

  const a10 = a[10];

  const a11 = a[11];

  const a12 = a[12];

  const a13 = a[13];

  const a14 = a[14];

  const a15 = a[15];

  const b0 = b[0];

  const b1 = b[1];

  const b2 = b[2];

  const b3 = b[3];

  const b4 = b[4];

  const b5 = b[5];

  const b6 = b[6];

  const b7 = b[7];

  const b8 = b[8];

  const b9 = b[9];

  const b10 = b[10];

  const b11 = b[11];

  const b12 = b[12];

  const b13 = b[13];

  const b14 = b[14];

  const b15 = b[15];

  let t0 = a0 * b0 + 38 * (a1 * b15 + a2 * b14 + a3 * b13 + a4 * b12 + a5 * b11 + a6 * b10 + a7 * b9 + a8 * b8 +
      a9 * b7 + a10 * b6 + a11 * b5 + a12 * b4 + a13 * b3 + a14 * b2 + a15 * b1);

  let t1 = a0 * b1 + a1 * b0 + 38 * (a2 * b15 + a3 * b14 + a4 * b13 + a5 * b12 + a6 * b11 + a7 * b10 + a8 * b9 +
      a9 * b8 + a10 * b7 + a11 * b6 + a12 * b5 + a13 * b4 + a14 * b3 + a15 * b2);

  let t2 = a0 * b2 + a1 * b1 + a2 * b0 + 38 * (a3 * b15 + a4 * b14 + a5 * b13 + a6 * b12 + a7 * b11 + a8 * b10 +
      a9 * b9 + a10 * b8 + a11 * b7 + a12 * b6 + a13 * b5 + a14 * b4 + a15 * b3);

  let t3 = a0 * b3 + a1 * b2 + a2 * b1 + a3 * b0 + 38 * (a4 * b15 + a5 * b14 + a6 * b13 + a7 * b12 + a8 * b11 +
      a9 * b10 + a10 * b9 + a11 * b8 + a12 * b7 + a13 * b6 + a14 * b5 + a15 * b4);

  let t4 = a0 * b4 + a1 * b3 + a2 * b2 + a3 * b1 + a4 * b0 + 38 * (a5 * b15 + a6 * b14 + a7 * b13 + a8 * b12 +
      a9 * b11 + a10 * b10 + a11 * b9 + a12 * b8 + a13 * b7 + a14 * b6 + a15 * b5);

  let t5 = a0 * b5 + a1 * b4 + a2 * b3 + a3 * b2 + a4 * b1 + a5 * b0 + 38 * (a6 * b15 + a7 * b14 + a8 * b13 + a9 * b12 +
      a10 * b11 + a11 * b10 + a12 * b9 + a13 * b8 + a14 * b7 + a15 * b6);

  let t6 = a0 * b6 + a1 * b5 + a2 * b4 + a3 * b3 + a4 * b2 + a5 * b1 + a6 * b0 + 38 * (a7 * b15 + a8 * b14 + a9 * b13 +
      a10 * b12 + a11 * b11 + a12 * b10 + a13 * b9 + a14 * b8 + a15 * b7);

  let t7 = a0 * b7 + a1 * b6 + a2 * b5 + a3 * b4 + a4 * b3 + a5 * b2 + a6 * b1 + a7 * b0 + 38 * (a8 * b15 + a9 * b14 +
      a10 * b13 + a11 * b12 + a12 * b11 + a13 * b10 + a14 * b9 + a15 * b8);

  let t8 = a0 * b8 + a1 * b7 + a2 * b6 + a3 * b5 + a4 * b4 + a5 * b3 + a6 * b2 + a7 * b1 + a8 * b0 + 38 * (a9 * b15 +
      a10 * b14 + a11 * b13 + a12 * b12 + a13 * b11 + a14 * b10 + a15 * b9);

  let t9 = a0 * b9 + a1 * b8 + a2 * b7 + a3 * b6 + a4 * b5 + a5 * b4 + a6 * b3 + a7 * b2 + a8 * b1 + a9 * b0 +
      38 * (a10 * b15 + a11 * b14 + a12 * b13 + a13 * b12 + a14 * b11 + a15 * b10);

  let t10 = a0 * b10 + a1 * b9 + a2 * b8 + a3 * b7 + a4 * b6 + a5 * b5 + a6 * b4 + a7 * b3 + a8 * b2 + a9 * b1 +
      a10 * b0 + 38 * (a11 * b15 + a12 * b14 + a13 * b13 + a14 * b12 + a15 * b11);

  let t11 = a0 * b11 + a1 * b10 + a2 * b9 + a3 * b8 + a4 * b7 + a5 * b6 + a6 * b5 + a7 * b4 + a8 * b3 + a9 * b2 +
      a10 * b1 + a11 * b0 + 38 * (a12 * b15 + a13 * b14 + a14 * b13 + a15 * b12);

  let t12 = a0 * b12 + a1 * b11 + a2 * b10 + a3 * b9 + a4 * b8 + a5 * b7 + a6 * b6 + a7 * b5 + a8 * b4 + a9 * b3 +
      a10 * b2 + a11 * b1 + a12 * b0 + 38 * (a13 * b15 + a14 * b14 + a15 * b13);

  let t13 = a0 * b13 + a1 * b12 + a2 * b11 + a3 * b10 + a4 * b9 + a5 * b8 + a6 * b7 + a7 * b6 + a8 * b5 + a9 * b4 +
      a10 * b3 + a11 * b2 + a12 * b1 + a13 * b0 + 38 * (a14 * b15 + a15 * b14);

  let t14 = a0 * b14 + a1 * b13 + a2 * b12 + a3 * b11 + a4 * b10 + a5 * b9 + a6 * b8 + a7 * b7 + a8 * b6 + a9 * b5 +
      a10 * b4 + a11 * b3 + a12 * b2 + a13 * b1 + a14 * b0 + 38 * (a15 * b15);

  let t15 = a0 * b15 + a1 * b14 + a2 * b13 + a3 * b12 + a4 * b11 + a5 * b10 + a6 * b9 + a7 * b8 + a8 * b7 + a9 * b6 +
      a10 * b5 + a11 * b4 + a12 * b3 + a13 * b2 + a14 * b1 + a15 * b0;

  let c = 0;

  c = Math.floor(t0 * LIMB_INVERSE);

  t0 -= c * LIMB;

  t1 += c;

  c = Math.floor(t1 * LIMB_INVERSE);

  t1 -= c * LIMB;

  t2 += c;

  c = Math.floor(t2 * LIMB_INVERSE);

  t2 -= c * LIMB;

  t3 += c;

  c = Math.floor(t3 * LIMB_INVERSE);

  t3 -= c * LIMB;

  t4 += c;

  c = Math.floor(t4 * LIMB_INVERSE);

  t4 -= c * LIMB;

  t5 += c;

  c = Math.floor(t5 * LIMB_INVERSE);

  t5 -= c * LIMB;

  t6 += c;

  c = Math.floor(t6 * LIMB_INVERSE);

  t6 -= c * LIMB;

  t7 += c;

  c = Math.floor(t7 * LIMB_INVERSE);

  t7 -= c * LIMB;

  t8 += c;

  c = Math.floor(t8 * LIMB_INVERSE);

  t8 -= c * LIMB;

  t9 += c;

  c = Math.floor(t9 * LIMB_INVERSE);

  t9 -= c * LIMB;

  t10 += c;

  c = Math.floor(t10 * LIMB_INVERSE);

  t10 -= c * LIMB;

  t11 += c;

  c = Math.floor(t11 * LIMB_INVERSE);

  t11 -= c * LIMB;

  t12 += c;

  c = Math.floor(t12 * LIMB_INVERSE);

  t12 -= c * LIMB;

  t13 += c;

  c = Math.floor(t13 * LIMB_INVERSE);

  t13 -= c * LIMB;

  t14 += c;

  c = Math.floor(t14 * LIMB_INVERSE);

  t14 -= c * LIMB;

  t15 += c;

  c = Math.floor(t15 * LIMB_INVERSE);

  t15 -= c * LIMB;

  t0 += 38 * c;

  c = Math.floor(t0 * LIMB_INVERSE);

  t0 -= c * LIMB;

  t1 += c;

  c = Math.floor(t1 * LIMB_INVERSE);

  t1 -= c * LIMB;

  t2 += c;

  o[0] = t0;

  o[1] = t1;

  o[2] = t2;

  o[3] = t3;

  o[4] = t4;

  o[5] = t5;

  o[6] = t6;

  o[7] = t7;

  o[8] = t8;

  o[9] = t9;

  o[10] = t10;

  o[11] = t11;

  o[12] = t12;

  o[13] = t13;

  o[14] = t14;

  o[15] = t15;
}

// The same for a square, in 136 products instead of 256.
export function square(o: Float64Array, a: Float64Array): void {
  const a0 = a[0];

  const a1 = a[1];

  const a2 = a[2];

  const a3 = a[3];

  const a4 = a[4];

  const a5 = a[5];

  const a6 = a[6];

  const a7 = a[7];

  const a8 = a[8];

  const a9 = a[9];

  const a10 = a[10];

  const a11 = a[11];

  const a12 = a[12];

  const a13 = a[13];

  const a14 = a[14];

  const a15 = a[15];

  const d0 = 2 * a0;

  const d1 = 2 * a1;

  const d2 = 2 * a2;

  const d3 = 2 * a3;

  const d4 = 2 * a4;

  const d5 = 2 * a5;

  const d6 = 2 * a6;

  const d7 = 2 * a7;

  const d8 = 2 * a8;

  const d9 = 2 * a9;

  const d10 = 2 * a10;

  const d11 = 2 * a11;

  const d12 = 2 * a12;

  const d13 = 2 * a13;

  const d14 = 2 * a14;

  const d15 = 2 * a15;

  let t0 = a0 * a0 + 38 * (d1 * a15 + d2 * a14 + d3 * a13 + d4 * a12 + d5 * a11 + d6 * a10 + d7 * a9 + a8 * a8);

  let t1 = d0 * a1 + 38 * (d2 * a15 + d3 * a14 + d4 * a13 + d5 * a12 + d6 * a11 + d7 * a10 + d8 * a9);

  let t2 = d0 * a2 + a1 * a1 + 38 * (d3 * a15 + d4 * a14 + d5 * a13 + d6 * a12 + d7 * a11 + d8 * a10 + a9 * a9);

  let t3 = d0 * a3 + d1 * a2 + 38 * (d4 * a15 + d5 * a14 + d6 * a13 + d7 * a12 + d8 * a11 + d9 * a10);

  let t4 = d0 * a4 + d1 * a3 + a2 * a2 + 38 * (d5 * a15 + d6 * a14 + d7 * a13 + d8 * a12 + d9 * a11 + a10 * a10);

  let t5 = d0 * a5 + d1 * a4 + d2 * a3 + 38 * (d6 * a15 + d7 * a14 + d8 * a13 + d9 * a12 + d10 * a11);

  let t6 = d0 * a6 + d1 * a5 + d2 * a4 + a3 * a3 + 38 * (d7 * a15 + d8 * a14 + d9 * a13 + d10 * a12 + a11 * a11);

  let t7 = d0 * a7 + d1 * a6 + d2 * a5 + d3 * a4 + 38 * (d8 * a15 + d9 * a14 + d10 * a13 + d11 * a12);

  let t8 = d0 * a8 + d1 * a7 + d2 * a6 + d3 * a5 + a4 * a4 + 38 * (d9 * a15 + d10 * a14 + d11 * a13 + a12 * a12);

  let t9 = d0 * a9 + d1 * a8 + d2 * a7 + d3 * a6 + d4 * a5 + 38 * (d10 * a15 + d11 * a14 + d12 * a13);

  let t10 = d0 * a10 + d1 * a9 + d2 * a8 + d3 * a7 + d4 * a6 + a5 * a5 + 38 * (d11 * a15 + d12 * a14 + a13 * a13);

  let t11 = d0 * a11 + d1 * a10 + d2 * a9 + d3 * a8 + d4 * a7 + d5 * a6 + 38 * (d12 * a15 + d13 * a14);

  let t12 = d0 * a12 + d1 * a11 + d2 * a10 + d3 * a9 + d4 * a8 + d5 * a7 + a6 * a6 + 38 * (d13 * a15 + a14 * a14);

  let t13 = d0 * a13 + d1 * a12 + d2 * a11 + d3 * a10 + d4 * a9 + d5 * a8 + d6 * a7 + 38 * (d14 * a15);

  let t14 = d0 * a14 + d1 * a13 + d2 * a12 + d3 * a11 + d4 * a10 + d5 * a9 + d6 * a8 + a7 * a7 + 38 * (a15 * a15);

  let t15 = d0 * a15 + d1 * a14 + d2 * a13 + d3 * a12 + d4 * a11 + d5 * a10 + d6 * a9 + d7 * a8;

  let c = 0;

  c = Math.floor(t0 * LIMB_INVERSE);

  t0 -= c * LIMB;

  t1 += c;

  c = Math.floor(t1 * LIMB_INVERSE);

  t1 -= c * LIMB;

  t2 += c;

  c = Math.floor(t2 * LIMB_INVERSE);

  t2 -= c * LIMB;

  t3 += c;

  c = Math.floor(t3 * LIMB_INVERSE);

  t3 -= c * LIMB;

  t4 += c;

  c = Math.floor(t4 * LIMB_INVERSE);

  t4 -= c * LIMB;

  t5 += c;

  c = Math.floor(t5 * LIMB_INVERSE);

  t5 -= c * LIMB;

  t6 += c;

  c = Math.floor(t6 * LIMB_INVERSE);

  t6 -= c * LIMB;

  t7 += c;

  c = Math.floor(t7 * LIMB_INVERSE);

  t7 -= c * LIMB;

  t8 += c;

  c = Math.floor(t8 * LIMB_INVERSE);

  t8 -= c * LIMB;

  t9 += c;

  c = Math.floor(t9 * LIMB_INVERSE);

  t9 -= c * LIMB;

  t10 += c;

  c = Math.floor(t10 * LIMB_INVERSE);

  t10 -= c * LIMB;

  t11 += c;

  c = Math.floor(t11 * LIMB_INVERSE);

  t11 -= c * LIMB;

  t12 += c;

  c = Math.floor(t12 * LIMB_INVERSE);

  t12 -= c * LIMB;

  t13 += c;

  c = Math.floor(t13 * LIMB_INVERSE);

  t13 -= c * LIMB;

  t14 += c;

  c = Math.floor(t14 * LIMB_INVERSE);

  t14 -= c * LIMB;

  t15 += c;

  c = Math.floor(t15 * LIMB_INVERSE);

  t15 -= c * LIMB;

  t0 += 38 * c;

  c = Math.floor(t0 * LIMB_INVERSE);

  t0 -= c * LIMB;

  t1 += c;

  c = Math.floor(t1 * LIMB_INVERSE);

  t1 -= c * LIMB;

  t2 += c;

  o[0] = t0;

  o[1] = t1;

  o[2] = t2;

  o[3] = t3;

  o[4] = t4;

  o[5] = t5;

  o[6] = t6;

  o[7] = t7;

  o[8] = t8;

  o[9] = t9;

  o[10] = t10;

  o[11] = t11;

  o[12] = t12;

  o[13] = t13;

  o[14] = t14;

  o[15] = t15;
}
