# cargo-deny policy: known advisories, licence allow-list, dependency sources. Run in CI and
# locally with `cargo deny check`.

[graph]
all-features = true

[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
allow = ["Apache-2.0", "MIT", "BSD-3-Clause"]
confidence-threshold = 0.9

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
