import { Buffer } from "node:buffer";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { sha256 } from "../src/primitives.ts";

// Writes the WebAssembly modules of `zig build dist` into src/ as base64, one module per family,
// and their SHA-256 into wasm/SHA256SUMS. The modules come from the directory given as an
// argument, by default zig/zig-out/dist/wasm. With --check it writes nothing and exits with
// status 1 if a file differs from what it would write.

const PACKAGE = fileURLToPath(new URL("../", import.meta.url));

// File, generated module and constant, in the order of the file names.
const MODULES: readonly (readonly [string, string, string])[] = [
  ["crypto_pq_ml_dsa.wasm", "src/wasm-ml-dsa.ts", "ML_DSA_WASM"],
  ["crypto_pq_ml_kem.wasm", "src/wasm-ml-kem.ts", "ML_KEM_WASM"],
  ["crypto_pq_slh_dsa.wasm", "src/wasm-slh-dsa.ts", "SLH_DSA_WASM"],
  ["crypto_pq_stateful.wasm", "src/wasm-stateful.ts", "STATEFUL_WASM"],
  ["crypto_pq_x_wing_hash.wasm", "src/wasm-x-wing-hash.ts", "X_WING_HASH_WASM"],
];

const MANIFEST = "wasm/SHA256SUMS";

function hex(data: Uint8Array): string {
  return Array.from(data, (b) => b.toString(16).padStart(2, "0")).join("");
}

const options = process.argv.slice(2);

const check = options.includes("--check");

const directory = resolve(options.find((option) => option !== "--check") ?? join(PACKAGE, "../zig/zig-out/dist/wasm"));

const files = new Map<string, string>();

const sums: string[] = [];

for (const [module, path, name] of MODULES) {
  const bytes = new Uint8Array(readFileSync(join(directory, module)));

  const text = Buffer.from(bytes).toString("base64");

  files.set(
    path,
    `// Generated by tools/embed.ts from ${module}; do not edit by hand.\nexport const ${name}: string =\n  "${text}";\n`,
  );

  sums.push(`${hex(sha256(bytes))}  ${module}\n`);
}

files.set(MANIFEST, sums.join(""));

let stale = 0;

for (const [path, text] of files) {
  const target = join(PACKAGE, path);

  let current: string | null = null;

  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = null;
  }

  if (current === text) {
    continue;
  }

  if (check) {
    console.error(`${path} differs from what tools/embed.ts produces`);

    stale++;
  } else {
    mkdirSync(dirname(target), { recursive: true });

    writeFileSync(target, text);

    console.log(`wrote ${path}`);
  }
}

process.exitCode = stale > 0 ? 1 : 0;
