import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";

// Writes the unrolled Keccak, SHA-2, X25519 and ML-DSA packing code of src/ from the definitions below.
// With --check it writes nothing and exits with status 1 if a module differs from what it would write.

const SOURCE = new URL("../src/", import.meta.url);

const HEADER = "// Generated by tools/generate.ts; do not edit by hand.";

const WIDTH = 120;

// A statement, or a block such as a loop: its first line without the brace, then its body.
type Statement = string | Block;

interface Block {
  readonly head: string;

  readonly body: readonly Statement[];
}

function block(head: string, body: readonly Statement[]): Block {
  return { head, body };
}

// One blank line between statements, none after an opening brace or before a closing one.
function emit(statements: readonly Statement[], indent: number): string[] {
  const pad = " ".repeat(indent);

  const lines: string[] = [];

  for (const statement of statements) {
    if (lines.length > 0) {
      lines.push("");
    }

    if (typeof statement === "string") {
      lines.push(...wrap(statement, pad));
    } else {
      lines.push(`${pad}${statement.head} {`, ...emit(statement.body, indent + 2), `${pad}}`);
    }
  }

  return lines;
}

// Breaks a long statement after its " + " operators, continuing four spaces further in.
function wrap(statement: string, pad: string): string[] {
  const lines: string[] = [];

  let line = pad;

  statement.split(" + ").forEach((term, i) => {
    if (i === 0) {
      line += term;
    } else if (line.length + term.length + 5 > WIDTH) {
      lines.push(`${line} +`);

      line = `${pad}    ${term}`;
    } else {
      line += ` + ${term}`;
    }
  });

  lines.push(line);

  if (lines.some((text) => text.length > WIDTH)) {
    throw new Error(`cannot fit within ${WIDTH} columns: ${statement}`);
  }

  return lines;
}

function func(name: string, parameters: readonly string[], exported: boolean, body: readonly Statement[]): string[] {
  const start = `${exported ? "export " : ""}function ${name}(`;

  const line = `${start}${parameters.join(", ")}): void {`;

  const head = line.length <= WIDTH ? [line] : [start, ...parameters.map((p) => `  ${p},`), "): void {"];

  return [...head, ...emit(body, 2), "}"];
}

// A table of 32-bit constants, eight to a line.
function table(name: string, values: readonly number[]): string[] {
  const rows: string[] = [];

  for (let i = 0; i < values.length; i += 8) {
    rows.push(`  ${values.slice(i, i + 8).map(hex).join(", ")},`);
  }

  return [`const ${name} = new Int32Array([`, ...rows, "]);"];
}

function hex(value: number): string {
  return `0x${(value >>> 0).toString(16).padStart(8, "0")}`;
}

// The module's items, such as a commented function, one blank line apart.
function module(items: readonly (readonly string[])[]): string {
  return `${[HEADER, ...items.flatMap((item) => ["", ...item])].join("\n")}\n`;
}

function range(length: number): number[] {
  return Array.from({ length }, (_, i) => i);
}

function rotl(x: string, n: number): string {
  return n === 0 ? x : `(${x} << ${n}) | (${x} >>> ${32 - n})`;
}

function rotr(x: string, n: number): string {
  return `((${x} >>> ${n}) | (${x} << ${32 - n}))`;
}

// Keccak-f[1600] (FIPS 202) on the bit-interleaved state of src/keccak.ts.

// FIPS 202, 3.2.2: the offset of lane x + 5y, along the walk (x, y) -> (y, 2x + 3y) from (1, 0).
function rhoOffsets(): number[] {
  const offsets = new Array<number>(25).fill(0);

  let x = 1;

  let y = 0;

  for (let t = 0; t < 24; t++) {
    offsets[x + 5 * y] = (((t + 1) * (t + 2)) / 2) % 64;

    [x, y] = [y, (2 * x + 3 * y) % 5];
  }

  return offsets;
}

// FIPS 202, Algorithm 5: the LFSR x^8 + x^6 + x^5 + x^4 + 1 behind the round constants.
function rc(t: number): number {
  let r = 1;

  for (let i = 0; i < t % 255; i++) {
    r <<= 1;

    if (r & 0x100) {
      r ^= 0x171;
    }
  }

  return r & 1;
}

// Bit 2^j - 1 of the constant of round i is rc(j + 7i). Every such position except 0 is odd, so it
// lands in the odd half of the interleaved lane, at bit 2^(j - 1) - 1.
function roundConstants(): number[] {
  const halves: number[] = [];

  for (let i = 0; i < 24; i++) {
    let odd = 0;

    for (let j = 1; j < 7; j++) {
      odd |= rc(j + 7 * i) << ((1 << (j - 1)) - 1);
    }

    halves.push(rc(7 * i), odd);
  }

  return halves;
}

function keccakRound(constant: string): string[] {
  const offsets = rhoOffsets();

  const s: string[] = [];

  for (let x = 0; x < 5; x++) {
    for (const half of ["e", "o"]) {
      s.push(`c${x}${half} = ${range(5).map((y) => `a${x + 5 * y}${half}`).join(" ^ ")};`);
    }
  }

  for (let x = 0; x < 5; x++) {
    const left = (x + 4) % 5;

    const right = (x + 1) % 5;

    s.push(`d = c${left}e ^ ((c${right}o << 1) | (c${right}o >>> 31));`);

    s.push(...range(5).map((y) => `a${x + 5 * y}e ^= d;`));

    s.push(`d = c${left}o ^ c${right}e;`);

    s.push(...range(5).map((y) => `a${x + 5 * y}o ^= d;`));
  }

  // Rotating a lane by 2k turns both halves by k; by 2k + 1 it also swaps them, turning by k + 1 and k.
  const moved: [string, string][] = [];

  for (let i = 0; i < 25; i++) {
    const x = i % 5;

    const y = (i - x) / 5;

    const k = offsets[i] >> 1;

    const odd = offsets[i] % 2 === 1;

    moved[y + 5 * ((2 * x + 3 * y) % 5)] = odd
      ? [rotl(`a${i}o`, k + 1), rotl(`a${i}e`, k)]
      : [rotl(`a${i}e`, k), rotl(`a${i}o`, k)];
  }

  moved.forEach(([even, odd], j) => s.push(`b${j}e = ${even};`, `b${j}o = ${odd};`));

  for (let i = 0; i < 25; i++) {
    const row = i - (i % 5);

    const next = row + ((i + 1) % 5);

    const after = row + ((i + 2) % 5);

    for (const half of ["e", "o"]) {
      const iota = i > 0 ? "" : ` ^ ROUND_CONSTANTS[${constant}${half === "e" ? "" : " + 1"}]`;

      s.push(`a${i}${half} = b${i}${half} ^ (~b${next}${half} & b${after}${half})${iota};`);
    }
  }

  return s;
}

function keccak(): string {
  const lanes = range(25).flatMap((i) => [`a${i}e`, `a${i}o`]);

  const columns = range(5).flatMap((x) => [`c${x}e`, `c${x}o`]);

  const moved = range(25).flatMap((j) => [`b${j}e`, `b${j}o`]);

  const body: Statement[] = [
    ...lanes.map((lane, i) => `let ${lane} = s[${i}] | 0;`),
    ...[...columns, "d", ...moved].map((name) => `let ${name} = 0;`),
    block("for (let round = 0; round < 48; round += 4)", [...keccakRound("round"), ...keccakRound("round + 2")]),
    ...lanes.map((lane, i) => `s[${i}] = ${lane};`),
  ];

  return module([
    [
      "// The round constants in the bit-interleaved form of the state, as (even, odd) halves.",
      ...table("ROUND_CONSTANTS", roundConstants()),
    ],
    [
      "// Keccak-f[1600] on a bit-interleaved state: lane i is s[2i], holding its even-numbered bits, and",
      "// s[2i + 1], holding its odd-numbered bits. A 64-bit rotation is then two 32-bit rotations, which V8",
      "// compiles to single instructions. Lane x + 5y is a{x + 5y}; rho and pi move it to",
      "// b{y + 5((2x + 3y) mod 5)}. Each iteration runs two rounds, which halves the register shuffling at",
      "// the loop's back edge.",
      ...func("permute", ["s: Uint32Array"], true, body),
    ],
  ]);
}

// SHA-256 and SHA-512 (FIPS 180-4) compressions on big-endian words.

function primes(count: number): number[] {
  const found: number[] = [];

  for (let candidate = 2; found.length < count; candidate++) {
    if (found.every((p) => candidate % p !== 0)) {
      found.push(candidate);
    }
  }

  return found;
}

// floor(cbrt(n)), by Newton's method from above.
function cubeRoot(n: bigint): bigint {
  let x = 1n << BigInt(Math.ceil(n.toString(2).length / 3) + 1);

  for (;;) {
    const next = (2n * x + n / (x * x)) / 3n;

    if (next >= x) {
      return x;
    }

    x = next;
  }
}

// FIPS 180-4, 4.2.2 and 4.2.3: the first 32 or 64 bits of the fractional parts of the cube roots of
// the first primes, the 64-bit ones as (high, low) pairs.
function shaConstants(count: number, bits: number): number[] {
  return primes(count).flatMap((p) => {
    const fraction = cubeRoot(BigInt(p) << BigInt(3 * bits)) & ((1n << BigInt(bits)) - 1n);

    return bits === 32 ? [Number(fraction)] : [Number(fraction >> 32n), Number(fraction & 0xffffffffn)];
  });
}

const LANE = ["a", "b", "c", "d", "e", "f", "g", "h"];

const SECOND_LANE = ["i", "j", "k", "l", "m", "n", "o", "p"];

const TWO_LANE_PARAMETERS = [
  "init: Int32Array",
  "w: Int32Array",
  "offset: number",
  "out: Int32Array",
  "xInit: Int32Array",
  "x: Int32Array",
  "xOffset: number",
  "xOut: Int32Array",
];

// The roles of the working variables move by one each round, h becoming the next round's a.
function rotate(v: readonly string[]): string[] {
  return [v[7], ...v.slice(0, 7)];
}

function round256(v: readonly string[], constant: string, word: string): string[] {
  const [a, b, c, d, e, f, g, h] = v;

  const sigma1 = `${rotr(e, 6)} ^ ${rotr(e, 11)} ^ ${rotr(e, 25)}`;

  const sigma0 = `${rotr(a, 2)} ^ ${rotr(a, 13)} ^ ${rotr(a, 22)}`;

  return [
    `${h} = (${h} + (${sigma1}) + (${g} ^ (${e} & (${f} ^ ${g}))) + ${constant} + ${word}) | 0;`,
    `${d} = (${d} + ${h}) | 0;`,
    `${h} = (${h} + (${sigma0}) + ((${a} & ${b}) | (${c} & (${a} | ${b})))) | 0;`,
  ];
}

// The message schedule rolls through sixteen variables: word j holds W[t] for t = j mod 16.
function schedule256(w: string, j: number): string {
  const x = `${w}${(j + 1) % 16}`;

  const y = `${w}${(j + 14) % 16}`;

  const sigma0 = `${rotr(x, 7)} ^ ${rotr(x, 18)} ^ (${x} >>> 3)`;

  const sigma1 = `${rotr(y, 17)} ^ ${rotr(y, 19)} ^ (${y} >>> 10)`;

  return `${w}${j} = (${w}${j} + (${sigma0}) + ${w}${(j + 9) % 16} + (${sigma1})) | 0;`;
}

function loads256(word: string, words: string, offset: string, lane: readonly string[], init: string): string[] {
  return [
    ...range(16).map((i) => `let ${word}${i} = ${words}[${offset}${i > 0 ? ` + ${i}` : ""}] | 0;`),
    ...lane.map((name, i) => `let ${name} = ${init}[${i}] | 0;`),
  ];
}

function block256(): string[] {
  const rounds: Statement[] = [];

  let v = LANE;

  for (let r = 0; r < 16; r++) {
    rounds.push(...round256(v, `K256[t${r > 0 ? ` + ${r}` : ""}]`, `w${r}`));

    v = rotate(v);
  }

  const body: Statement[] = [
    ...loads256("w", "w", "offset", LANE, "init"),
    block("for (let t = 0; t < 64; t += 16)", [
      ...rounds,
      block(
        "if (t < 48)",
        range(16).map((j) => schedule256("w", j)),
      ),
    ]),
    ...LANE.map((name, i) => `out[${i}] = (init[${i}] + ${name}) | 0;`),
  ];

  return [
    "// The SHA-256 compression function on words: out = init + rounds(w[offset .. offset + 16]). init and",
    "// out may be the same array. The message schedule rolls through sixteen variables, which V8 keeps in",
    "// registers, instead of an array of 64 words.",
    ...func("block256", ["init: Int32Array", "w: Int32Array", "offset: number", "out: Int32Array"], true, body),
  ];
}

// Rounds from to to - 1 of the two compressions of block256x2, interleaved, with constants inline.
function rounds256x2(from: number, to: number, k: readonly number[]): string[] {
  const s: string[] = [];

  let a = LANE;

  let b = SECOND_LANE;

  for (let t = from; t < to; t++) {
    if (t >= 16) {
      s.push(schedule256("w", t % 16), schedule256("x", t % 16));
    }

    s.push(...round256(a, hex(k[t]), `w${t % 16}`), ...round256(b, hex(k[t]), `x${t % 16}`));

    a = rotate(a);

    b = rotate(b);
  }

  return s;
}

function block256x2(k: readonly number[]): string[] {
  const carried = [...range(16).map((i) => `w${i}`), ...range(16).map((i) => `x${i}`), ...LANE, ...SECOND_LANE];

  const low: Statement[] = [
    ...loads256("w", "w", "offset", LANE, "init"),
    ...loads256("x", "x", "xOffset", SECOND_LANE, "xInit"),
    ...rounds256x2(0, 32, k),
    ...carried.map((name, i) => `HALF[${i}] = ${name};`),
  ];

  const high: Statement[] = [
    ...carried.map((name, i) => `let ${name} = HALF[${i}];`),
    ...rounds256x2(32, 64, k),
    ...LANE.map((name, i) => `out[${i}] = (init[${i}] + ${name}) | 0;`),
    ...SECOND_LANE.map((name, i) => `xOut[${i}] = (xInit[${i}] + ${name}) | 0;`),
  ];

  const lowParameters = ["init: Int32Array", "w: Int32Array", "offset: number", "xInit: Int32Array", "x: Int32Array"];

  const highParameters = ["init: Int32Array", "out: Int32Array", "xInit: Int32Array", "xOut: Int32Array"];

  return [
    ...func("block256x2Low", [...lowParameters, "xOffset: number"], false, low),
    "",
    ...func("block256x2High", highParameters, false, high),
    "",
    "// Two independent SHA-256 compressions, (init, w, offset, out) and (xInit, x, xOffset, xOut), with",
    "// their rounds interleaved: one compression is a long chain of dependent additions, and two of them",
    "// keep the processor busy in each other's latency. The rounds are unrolled, as a loop costs about 15%",
    "// here, in two halves that pass their state through HALF, since one function would come close to the",
    "// 60 KB of bytecode above which V8 stops optimizing it. out and xOut must differ.",
    ...func("block256x2", TWO_LANE_PARAMETERS, true, [
      "block256x2Low(init, w, offset, xInit, x, xOffset);",
      "block256x2High(init, out, xInit, xOut);",
    ]),
  ];
}

// A 64-bit rotation right by n of (high, low), as its new (high, low) halves.
function rot64(high: string, low: string, n: number): [string, string] {
  if (n < 32) {
    return [`((${high} >>> ${n}) | (${low} << ${32 - n}))`, `((${low} >>> ${n}) | (${high} << ${32 - n}))`];
  }

  return [`((${low} >>> ${n - 32}) | (${high} << ${64 - n}))`, `((${high} >>> ${n - 32}) | (${low} << ${64 - n}))`];
}

// The XOR of rotations of the 64-bit variable name, as (high, low) expressions.
function sigma(name: string, rotations: readonly number[]): [string, string] {
  const parts = rotations.map((n) => rot64(`${name}h`, `${name}l`, n));

  return [parts.map(([high]) => high).join(" ^ "), parts.map(([, low]) => low).join(" ^ ")];
}

// Words 16 to 79 of a SHA-512 message schedule held in the arrays high and low.
function schedule512(high: string, low: string): string[] {
  const [s0h, s0l] = sigma("x", [1, 8]);

  const [s1h, s1l] = sigma("y", [19, 61]);

  return [
    `xh = ${high}[t - 15];`,
    `xl = ${low}[t - 15];`,
    `yh = ${high}[t - 2];`,
    `yl = ${low}[t - 2];`,
    `sigmaHigh = ${s0h} ^ (xh >>> 7);`,
    `sigmaLow = ${s0l} ^ ((xl >>> 7) | (xh << 25));`,
    `carry = ${s1h} ^ (yh >>> 6);`,
    `sum = ${s1l} ^ ((yl >>> 6) | (yh << 26));`,
    `sum = (sigmaLow >>> 0) + (sum >>> 0) + (${low}[t - 7] >>> 0) + (${low}[t - 16] >>> 0);`,
    `${low}[t] = sum;`,
    `${high}[t] = sigmaHigh + carry + ${high}[t - 7] + ${high}[t - 16] + ((sum / TWO_32) | 0);`,
  ];
}

// (high, low) = (xHigh, xLow) + (yHigh, yLow), the carry of the low halves being the top bit of
// (x & y) | ((x | y) & ~(x + y)).
function add64(high: string, low: string, xHigh: string, xLow: string, yHigh: string, yLow: string): string[] {
  return [
    `sum = (${xLow} + ${yLow}) | 0;`,
    `${high} = (${xHigh} + ${yHigh} + (((${xLow} & ${yLow}) | ((${xLow} | ${yLow}) & ~sum)) >>> 31)) | 0;`,
    `${low} = sum;`,
  ];
}

// t1 = h + sigma1(e) + ch(e, f, g) + K[t] + W[t] accumulates in h; then d += t1 and h = t1 + sigma0(a)
// + maj(a, b, c), adding the 64-bit values with integer carries.
function round512(v: readonly string[], t: string): string[] {
  const [a, b, c, d, e, f, g, h] = v;

  const [s1h, s1l] = sigma(e, [14, 18, 41]);

  const [s0h, s0l] = sigma(a, [28, 34, 39]);

  const addToH = (yHigh: string, yLow: string) => add64(`${h}h`, `${h}l`, `${h}h`, `${h}l`, yHigh, yLow);

  return [
    `sigmaHigh = ${s1h};`,
    `sigmaLow = ${s1l};`,
    ...addToH("sigmaHigh", "sigmaLow"),
    `sigmaHigh = ${g}h ^ (${e}h & (${f}h ^ ${g}h));`,
    `sigmaLow = ${g}l ^ (${e}l & (${f}l ^ ${g}l));`,
    ...addToH("sigmaHigh", "sigmaLow"),
    ...addToH(`K512[2 * (${t})]`, `K512[2 * (${t}) + 1]`),
    ...addToH(`WH[${t}]`, `WL[${t}]`),
    ...add64(`${d}h`, `${d}l`, `${d}h`, `${d}l`, `${h}h`, `${h}l`),
    `sigmaHigh = ${s0h};`,
    `sigmaLow = ${s0l};`,
    ...addToH("sigmaHigh", "sigmaLow"),
    `sigmaHigh = (${a}h & ${b}h) | (${c}h & (${a}h | ${b}h));`,
    `sigmaLow = (${a}l & ${b}l) | (${c}l & (${a}l | ${b}l));`,
    ...addToH("sigmaHigh", "sigmaLow"),
  ];
}

// The same round for block512x2, where the low halves are summed as doubles and the carry into the
// high halves is the sum divided by 2^32.
function round512Double(v: readonly string[], t: string, wh: string, wl: string): string[] {
  const [a, b, c, d, e, f, g, h] = v;

  const [s1h, s1l] = sigma(e, [14, 18, 41]);

  const [s0h, s0l] = sigma(a, [28, 34, 39]);

  return [
    `sigmaHigh = ${s1h};`,
    `sigmaLow = ${s1l};`,
    `sum = (${h}l >>> 0) + (sigmaLow >>> 0) + ((${g}l ^ (${e}l & (${f}l ^ ${g}l))) >>> 0);`,
    `sum += (K512[2 * (${t}) + 1] >>> 0) + (${wl}[${t}] >>> 0);`,
    `carry = ${h}h + sigmaHigh + (${g}h ^ (${e}h & (${f}h ^ ${g}h))) + K512[2 * (${t})] + ${wh}[${t}];`,
    "carry = (carry + ((sum / TWO_32) | 0)) | 0;",
    "low = sum | 0;",
    `sum = (${d}l >>> 0) + (low >>> 0);`,
    `${d}h = (${d}h + carry + ((sum / TWO_32) | 0)) | 0;`,
    `${d}l = sum | 0;`,
    `sigmaHigh = ${s0h};`,
    `sigmaLow = ${s0l};`,
    `sum = (low >>> 0) + (sigmaLow >>> 0) + (((${a}l & ${b}l) | (${c}l & (${a}l | ${b}l))) >>> 0);`,
    `${h}h = (carry + sigmaHigh + ((${a}h & ${b}h) | (${c}h & (${a}h | ${b}h))) + ((sum / TWO_32) | 0)) | 0;`,
    `${h}l = sum | 0;`,
  ];
}

const TEMPORARIES_512 = ["sigmaHigh", "sigmaLow", "carry", "low", "sum", "xh", "xl", "yh", "yl"];

function loads512(lane: readonly string[], init: string): string[] {
  return lane.flatMap((name, i) => [`let ${name}h = ${init}[${2 * i}];`, `let ${name}l = ${init}[${2 * i + 1}];`]);
}

function block512(): string[] {
  const rounds: Statement[] = [];

  let v = LANE;

  for (let r = 0; r < 8; r++) {
    rounds.push(...round512(v, r > 0 ? `t + ${r}` : "t"));

    v = rotate(v);
  }

  const body: Statement[] = [
    ...TEMPORARIES_512.map((name) => `let ${name} = 0;`),
    block("for (let t = 0; t < 16; t++)", ["WH[t] = w[offset + 2 * t];", "WL[t] = w[offset + 2 * t + 1];"]),
    block("for (let t = 16; t < 80; t++)", schedule512("WH", "WL")),
    ...loads512(LANE, "init"),
    block("for (let t = 0; t < 80; t += 8)", rounds),
    ...LANE.flatMap((name, i) => {
      const [high, low] = [2 * i, 2 * i + 1];

      return add64(`out[${high}]`, `out[${low}]`, `init[${high}]`, `init[${low}]`, `${name}h`, `${name}l`);
    }),
  ];

  return [
    "// The SHA-512 compression function on 32 words, the (high, low) halves of the 16 message words:",
    "// out = init + rounds(w[offset .. offset + 32]); init and out may be the same array. The 64-bit",
    "// additions carry between the halves with integer operations only.",
    ...func("block512", ["init: Int32Array", "w: Int32Array", "offset: number", "out: Int32Array"], true, body),
  ];
}

function block512x2(): string[] {
  const second = LANE.map((name) => `${name}2`);

  const rounds: Statement[] = [];

  let v = LANE;

  let u = second;

  for (let r = 0; r < 8; r++) {
    const t = r > 0 ? `t + ${r}` : "t";

    rounds.push(...round512Double(v, t, "WH", "WL"), ...round512Double(u, t, "XH", "XL"));

    v = rotate(v);

    u = rotate(u);
  }

  const finish = (lane: readonly string[], init: string, out: string) => {
    return lane.flatMap((name, i) => [
      `sum = (${init}[${2 * i + 1}] >>> 0) + (${name}l >>> 0);`,
      `${out}[${2 * i}] = (${init}[${2 * i}] + ${name}h + ((sum / TWO_32) | 0)) | 0;`,
      `${out}[${2 * i + 1}] = sum | 0;`,
    ]);
  };

  const body: Statement[] = [
    ...TEMPORARIES_512.map((name) => `let ${name} = 0;`),
    block("for (let t = 0; t < 16; t++)", [
      "WH[t] = w[offset + 2 * t];",
      "WL[t] = w[offset + 2 * t + 1];",
      "XH[t] = x[xOffset + 2 * t];",
      "XL[t] = x[xOffset + 2 * t + 1];",
    ]),
    block("for (let t = 16; t < 80; t++)", [...schedule512("WH", "WL"), ...schedule512("XH", "XL")]),
    ...loads512(LANE, "init"),
    ...loads512(second, "xInit"),
    block("for (let t = 0; t < 80; t += 8)", rounds),
    ...finish(LANE, "init", "out"),
    ...finish(second, "xInit", "xOut"),
  ];

  return [
    "// Two independent SHA-512 compressions with their rounds interleaved. With twice the work in flight,",
    "// the carries go through doubles: a sum of 32-bit halves divided by 2^32 gives its carry, in fewer",
    "// instructions than the integer formula.",
    ...func("block512x2", TWO_LANE_PARAMETERS, true, body),
  ];
}

function sha2(): string {
  const k256 = shaConstants(64, 32);

  return module([
    table("K256", k256),
    ["// The 64-bit constants as (high, low) pairs.", ...table("K512", shaConstants(80, 64))],
    ["const TWO_32 = 0x100000000;"],
    [
      "// The message schedules of the SHA-512 compressions, and the state passed between the halves of",
      "// block256x2.",
      "const WH = new Int32Array(80);",
      "",
      "const WL = new Int32Array(80);",
      "",
      "const XH = new Int32Array(80);",
      "",
      "const XL = new Int32Array(80);",
      "",
      "const HALF = new Int32Array(48);",
    ],
    block256(),
    block256x2(k256),
    block512(),
    block512x2(),
  ]);
}

// GF(2^255 - 19) with sixteen 16-bit limbs held in doubles, as in src/x25519.ts.

// The terms of limb k of a product: a_i b_j for i + j = k, then those for i + j = k + 16 times 38,
// since 2^256 = 38 modulo p. A square takes each cross product once, doubled through d_i = 2 a_i.
function productTerms(k: number, square: boolean): string[] {
  const low: string[] = [];

  const high: string[] = [];

  for (let i = 0; i < 16; i++) {
    for (let j = square ? i : 0; j < 16; j++) {
      const term = square ? `${i === j ? "a" : "d"}${i} * a${j}` : `a${i} * b${j}`;

      if (i + j === k) {
        low.push(term);
      } else if (i + j === k + 16) {
        high.push(term);
      }
    }
  }

  if (high.length > 0) {
    high[0] = `38 * (${high[0]}`;

    high[high.length - 1] += ")";
  }

  return [...low, ...high];
}

function carryLimb(i: number, into: string): string[] {
  return [`c = Math.floor(t${i} * LIMB_INVERSE);`, `t${i} -= c * LIMB;`, into];
}

function fieldProduct(name: string, square: boolean): string[] {
  const body: Statement[] = [
    ...range(16).map((i) => `const a${i} = a[${i}];`),
    ...range(16).map((i) => (square ? `const d${i} = 2 * a${i};` : `const b${i} = b[${i}];`)),
    ...range(16).map((k) => `let t${k} = ${productTerms(k, square).join(" + ")};`),
    "let c = 0;",
    ...range(16).flatMap((i) => carryLimb(i, i < 15 ? `t${i + 1} += c;` : "t0 += 38 * c;")),
    ...carryLimb(0, "t1 += c;"),
    ...carryLimb(1, "t2 += c;"),
    ...range(16).map((i) => `o[${i}] = t${i};`),
  ];

  const parameters = ["o: Float64Array", "a: Float64Array", ...(square ? [] : ["b: Float64Array"])];

  return func(name, parameters, true, body);
}

// The limb constants stay private: V8 folds a module's own constants into its optimized code, but
// reads an exported binding from memory, with a check, at every use.
function x25519(): string {
  return module([
    ["const LIMB = 65536;"],
    ["const LIMB_INVERSE = 2 ** -16;"],
    [
      "// The product, unrolled into one sum per limb with the terms of weight 2^256 and above folded in as",
      "// 2^256 = 38. Inputs have limbs below 2^19 in magnitude, so a sum stays below 2^48 and exact. One",
      "// full carry pass leaves every limb in [0, 2^16) except the first, which can reach 2^32; carrying it",
      "// twice more brings every limb into [-1, 2^16], as two full passes would.",
      ...fieldProduct("multiply", false),
    ],
    ["// The same for a square, in 136 products instead of 256.", ...fieldProduct("square", true)],
  ]);
}

// FIPS 204 bit packing, eight coefficients at a time: eight values of b bits fill exactly b bytes.

// The b bytes of eight b-bit values a0 .. a7, least significant bits first.
function packedBytes(bits: number): string[] {
  return range(bits).map((j) => {
    const terms: string[] = [];

    for (let c = 0; c < 8; c++) {
      const shift = c * bits - 8 * j;

      if (shift > -bits && shift < 8) {
        terms.push(shift === 0 ? `a${c}` : shift > 0 ? `a${c} << ${shift}` : `a${c} >> ${-shift}`);
      }
    }

    return terms.length === 1 ? terms[0] : terms.map((term) => (term.includes(" ") ? `(${term})` : term)).join(" | ");
  });
}

// SimpleBitPack (Algorithm 16) stores each coefficient; BitPack (Algorithm 17) stores b - w[i] for
// coefficients in [-a, b].
function packer(bits: number, simple: boolean): string[] {
  const value = (c: number) => `${simple ? "" : "b - "}w[i${c > 0 ? ` + ${c}` : ""}]`;

  const body: Statement[] = [
    block(`for (let i = 0, o = offset; i < 256; i += 8, o += ${bits})`, [
      ...range(8).map((c) => `const a${c} = ${value(c)};`),
      ...packedBytes(bits).map((expression, j) => `out[o${j > 0 ? ` + ${j}` : ""}] = ${expression};`),
    ]),
  ];

  const parameters = ["w: Int32Array", ...(simple ? [] : ["b: number"]), "out: Uint8Array", "offset: number"];

  return func(`${simple ? "simpleBitPack" : "bitPack"}${bits}`, parameters, true, body);
}

// The widths of key generation: t1 (10 bits), s1 and s2 (3 bits for eta = 2, 4 for eta = 4) and t0
// (13 bits).
function mldsaPack(): string {
  return module([
    [
      "// FIPS 204 SimpleBitPack (Algorithm 16) and BitPack (Algorithm 17) of the 256 coefficients of w into",
      "// out at offset, eight coefficients at a time: eight b-bit values fill exactly b bytes. BitPack stores",
      "// b - w[i], which lies in [0, 2^bits) for coefficients in [-a, b].",
      ...packer(10, true),
    ],
    packer(3, false),
    packer(4, false),
    packer(13, false),
  ]);
}

const MODULES: [string, () => string][] = [
  ["keccak-permute.ts", keccak],
  ["sha2-rounds.ts", sha2],
  ["x25519-field.ts", x25519],
  ["mldsa-pack.ts", mldsaPack],
];

const check = process.argv.includes("--check");

let stale = 0;

for (const [name, generate] of MODULES) {
  const path = new URL(name, SOURCE);

  const text = generate();

  let current: string | null = null;

  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = null;
  }

  if (current === text) {
    continue;
  }

  if (check) {
    console.error(`src/${name} differs from what tools/generate.ts produces`);

    stale++;
  } else {
    writeFileSync(path, text);

    console.log(`wrote src/${name}`);
  }
}

process.exitCode = stale > 0 ? 1 : 0;
