// Code generated by internal/asmgen. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

// MIDR_EL1, which Linux emulates for user space when it reports HWCAP_CPUID; elsewhere the
// instruction traps.
// func midr() uint64
TEXT ·midr(SB), NOSPLIT, $0-8
	MRS	MIDR_EL1, R0
	MOVD	R0, ret+0(FP)
	RET

// Sets PSTATE.DIT and reports whether it was set already; the CPU must have FEAT_DIT. MRS
// returns the bit in position 24.
// func ditSet() bool
TEXT ·ditSet(SB), NOSPLIT, $0-1
	MRS	DIT, R0
	UBFX	$24, R0, $1, R0
	MOVB	R0, ret+0(FP)
	MSR	$1, DIT
	RET

// Clears PSTATE.DIT.
// func ditClear()
TEXT ·ditClear(SB), NOSPLIT, $0-0
	MSR	$0, DIT
	RET
