// Code generated by internal/asmgen. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

// func cpuid(leaf, subleaf uint32) (eax, ebx, ecx, edx uint32)
TEXT ·cpuid(SB), NOSPLIT, $0-24
	MOVL	leaf+0(FP), AX
	MOVL	subleaf+4(FP), CX
	CPUID
	MOVL	AX, eax+8(FP)
	MOVL	BX, ebx+12(FP)
	MOVL	CX, ecx+16(FP)
	MOVL	DX, edx+20(FP)
	RET

// XCR0, the register states the operating system saves; the CPU must have OSXSAVE.
// func xgetbv() (eax, edx uint32)
TEXT ·xgetbv(SB), NOSPLIT, $0-8
	MOVL	$0, CX
	XGETBV
	MOVL	AX, eax+0(FP)
	MOVL	DX, edx+4(FP)
	RET
