// Code generated by internal/asmgen. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

// The NTT of ML-KEM (FIPS 203, Algorithm 9) of canonical coefficients, left canonical.
// func kemNTTARM(f *[256]uint16)
TEXT ·kemNTTARM(SB), NOSPLIT, $0-8
	MOVD	f+0(FP), R0
	MOVD	$kemConstants<>(SB), R4
	VLD1	(R4), [V2.H8, V3.H8, V4.H8]
	MOVD	$kemZetaLists<>(SB), R1
// Pass 1: layers 128, 64 and 32 on the vectors j, j + 4, ..., j + 28.
	VLD1.P	32(R1), [V0.H8, V1.H8]
	MOVD	R0, R2
	MOVD	$4, R3
outer:
	VLD1	(R2), [V16.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V17.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V18.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V19.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V20.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V21.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V22.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V23.H8]
	WORD	$0x4f408298 // mul v24.8h, v20.8h, v0.h[0]
	WORD	$0x2f41a299 // umull v25.4s, v20.4h, v1.h[0]
	WORD	$0x6f41a29a // umull2 v26.4s, v20.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V16.H8, V20.H8
	VADD	V3.H8, V20.H8, V20.H8
	VADD	V24.H8, V16.H8, V16.H8
	WORD	$0x4f4082b8 // mul v24.8h, v21.8h, v0.h[0]
	WORD	$0x2f41a2b9 // umull v25.4s, v21.4h, v1.h[0]
	WORD	$0x6f41a2ba // umull2 v26.4s, v21.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V17.H8, V21.H8
	VADD	V3.H8, V21.H8, V21.H8
	VADD	V24.H8, V17.H8, V17.H8
	WORD	$0x4f4082d8 // mul v24.8h, v22.8h, v0.h[0]
	WORD	$0x2f41a2d9 // umull v25.4s, v22.4h, v1.h[0]
	WORD	$0x6f41a2da // umull2 v26.4s, v22.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V18.H8, V22.H8
	VADD	V3.H8, V22.H8, V22.H8
	VADD	V24.H8, V18.H8, V18.H8
	WORD	$0x4f4082f8 // mul v24.8h, v23.8h, v0.h[0]
	WORD	$0x2f41a2f9 // umull v25.4s, v23.4h, v1.h[0]
	WORD	$0x6f41a2fa // umull2 v26.4s, v23.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V19.H8, V23.H8
	VADD	V3.H8, V23.H8, V23.H8
	VADD	V24.H8, V19.H8, V19.H8
	WORD	$0x4f508258 // mul v24.8h, v18.8h, v0.h[1]
	WORD	$0x2f51a259 // umull v25.4s, v18.4h, v1.h[1]
	WORD	$0x6f51a25a // umull2 v26.4s, v18.8h, v1.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V16.H8, V18.H8
	VADD	V3.H8, V18.H8, V18.H8
	VADD	V24.H8, V16.H8, V16.H8
	WORD	$0x4f508278 // mul v24.8h, v19.8h, v0.h[1]
	WORD	$0x2f51a279 // umull v25.4s, v19.4h, v1.h[1]
	WORD	$0x6f51a27a // umull2 v26.4s, v19.8h, v1.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V17.H8, V19.H8
	VADD	V3.H8, V19.H8, V19.H8
	VADD	V24.H8, V17.H8, V17.H8
	WORD	$0x4f6082d8 // mul v24.8h, v22.8h, v0.h[2]
	WORD	$0x2f61a2d9 // umull v25.4s, v22.4h, v1.h[2]
	WORD	$0x6f61a2da // umull2 v26.4s, v22.8h, v1.h[2]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V20.H8, V22.H8
	VADD	V3.H8, V22.H8, V22.H8
	VADD	V24.H8, V20.H8, V20.H8
	WORD	$0x4f6082f8 // mul v24.8h, v23.8h, v0.h[2]
	WORD	$0x2f61a2f9 // umull v25.4s, v23.4h, v1.h[2]
	WORD	$0x6f61a2fa // umull2 v26.4s, v23.8h, v1.h[2]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V21.H8, V23.H8
	VADD	V3.H8, V23.H8, V23.H8
	VADD	V24.H8, V21.H8, V21.H8
	WORD	$0x4f708238 // mul v24.8h, v17.8h, v0.h[3]
	WORD	$0x2f71a239 // umull v25.4s, v17.4h, v1.h[3]
	WORD	$0x6f71a23a // umull2 v26.4s, v17.8h, v1.h[3]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V16.H8, V17.H8
	VADD	V3.H8, V17.H8, V17.H8
	VADD	V24.H8, V16.H8, V16.H8
	WORD	$0x4f408a78 // mul v24.8h, v19.8h, v0.h[4]
	WORD	$0x2f41aa79 // umull v25.4s, v19.4h, v1.h[4]
	WORD	$0x6f41aa7a // umull2 v26.4s, v19.8h, v1.h[4]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V18.H8, V19.H8
	VADD	V3.H8, V19.H8, V19.H8
	VADD	V24.H8, V18.H8, V18.H8
	WORD	$0x4f508ab8 // mul v24.8h, v21.8h, v0.h[5]
	WORD	$0x2f51aab9 // umull v25.4s, v21.4h, v1.h[5]
	WORD	$0x6f51aaba // umull2 v26.4s, v21.8h, v1.h[5]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V20.H8, V21.H8
	VADD	V3.H8, V21.H8, V21.H8
	VADD	V24.H8, V20.H8, V20.H8
	WORD	$0x4f608af8 // mul v24.8h, v23.8h, v0.h[6]
	WORD	$0x2f61aaf9 // umull v25.4s, v23.4h, v1.h[6]
	WORD	$0x6f61aafa // umull2 v26.4s, v23.8h, v1.h[6]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V22.H8, V23.H8
	VADD	V3.H8, V23.H8, V23.H8
	VADD	V24.H8, V22.H8, V22.H8
	VST1	[V23.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V22.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V21.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V20.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V19.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V18.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V17.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V16.H8], (R2)
	ADD	$16, R2, R2
	SUBS	$1, R3, R3
	BNE	outer
// Pass 2: layers 16 and 8 on blocks of eight vectors, then 4 and 2 inside pairs of
// vectors, rearranged by 64-bit and 32-bit transpositions, and the final reduction.
	MOVD	R0, R2
	MOVD	$kemZetaLanes<>(SB), R5
	MOVD	$4, R3
inner:
	ADD	$64, R2, R7
	VLD1	(R2), [V16.H8, V17.H8, V18.H8, V19.H8]
	VLD1	(R7), [V20.H8, V21.H8, V22.H8, V23.H8]
	VLD1.P	32(R1), [V0.H8, V1.H8]
	WORD	$0x4f408258 // mul v24.8h, v18.8h, v0.h[0]
	WORD	$0x2f41a259 // umull v25.4s, v18.4h, v1.h[0]
	WORD	$0x6f41a25a // umull2 v26.4s, v18.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V16.H8, V18.H8
	VADD	V3.H8, V18.H8, V18.H8
	VADD	V24.H8, V16.H8, V16.H8
	WORD	$0x4f408278 // mul v24.8h, v19.8h, v0.h[0]
	WORD	$0x2f41a279 // umull v25.4s, v19.4h, v1.h[0]
	WORD	$0x6f41a27a // umull2 v26.4s, v19.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V17.H8, V19.H8
	VADD	V3.H8, V19.H8, V19.H8
	VADD	V24.H8, V17.H8, V17.H8
	WORD	$0x4f5082d8 // mul v24.8h, v22.8h, v0.h[1]
	WORD	$0x2f51a2d9 // umull v25.4s, v22.4h, v1.h[1]
	WORD	$0x6f51a2da // umull2 v26.4s, v22.8h, v1.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V20.H8, V22.H8
	VADD	V3.H8, V22.H8, V22.H8
	VADD	V24.H8, V20.H8, V20.H8
	WORD	$0x4f5082f8 // mul v24.8h, v23.8h, v0.h[1]
	WORD	$0x2f51a2f9 // umull v25.4s, v23.4h, v1.h[1]
	WORD	$0x6f51a2fa // umull2 v26.4s, v23.8h, v1.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V21.H8, V23.H8
	VADD	V3.H8, V23.H8, V23.H8
	VADD	V24.H8, V21.H8, V21.H8
	WORD	$0x4f608238 // mul v24.8h, v17.8h, v0.h[2]
	WORD	$0x2f61a239 // umull v25.4s, v17.4h, v1.h[2]
	WORD	$0x6f61a23a // umull2 v26.4s, v17.8h, v1.h[2]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V16.H8, V17.H8
	VADD	V3.H8, V17.H8, V17.H8
	VADD	V24.H8, V16.H8, V16.H8
	WORD	$0x4f708278 // mul v24.8h, v19.8h, v0.h[3]
	WORD	$0x2f71a279 // umull v25.4s, v19.4h, v1.h[3]
	WORD	$0x6f71a27a // umull2 v26.4s, v19.8h, v1.h[3]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V18.H8, V19.H8
	VADD	V3.H8, V19.H8, V19.H8
	VADD	V24.H8, V18.H8, V18.H8
	WORD	$0x4f408ab8 // mul v24.8h, v21.8h, v0.h[4]
	WORD	$0x2f41aab9 // umull v25.4s, v21.4h, v1.h[4]
	WORD	$0x6f41aaba // umull2 v26.4s, v21.8h, v1.h[4]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V20.H8, V21.H8
	VADD	V3.H8, V21.H8, V21.H8
	VADD	V24.H8, V20.H8, V20.H8
	WORD	$0x4f508af8 // mul v24.8h, v23.8h, v0.h[5]
	WORD	$0x2f51aaf9 // umull v25.4s, v23.4h, v1.h[5]
	WORD	$0x6f51aafa // umull2 v26.4s, v23.8h, v1.h[5]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V22.H8, V23.H8
	VADD	V3.H8, V23.H8, V23.H8
	VADD	V24.H8, V22.H8, V22.H8
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V17.D2, V16.D2, V12.D2
	VTRN2	V17.D2, V16.D2, V13.D2
	WORD	$0x4e7c9db8 // mul v24.8h, v13.8h, v28.8h
	WORD	$0x2e7dc1b9 // umull v25.4s, v13.4h, v29.4h
	WORD	$0x6e7dc1ba // umull2 v26.4s, v13.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V12.H8, V13.H8
	VADD	V3.H8, V13.H8, V13.H8
	VADD	V24.H8, V12.H8, V12.H8
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	WORD	$0x4e7e9df8 // mul v24.8h, v15.8h, v30.8h
	WORD	$0x2e7fc1f9 // umull v25.4s, v15.4h, v31.4h
	WORD	$0x6e7fc1fa // umull2 v26.4s, v15.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V14.H8, V15.H8
	VADD	V3.H8, V15.H8, V15.H8
	VADD	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1d9 // umull v25.4s, v14.4h, v2.h[1]
	WORD	$0x6f52a1da // umull2 v26.4s, v14.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432e // mls v14.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V14.H8, V24.H8
	VUMIN	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1f9 // umull v25.4s, v15.4h, v2.h[1]
	WORD	$0x6f52a1fa // umull2 v26.4s, v15.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432f // mls v15.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V15.H8, V24.H8
	VUMIN	V24.H8, V15.H8, V15.H8
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VTRN1	V13.D2, V12.D2, V16.D2
	VTRN2	V13.D2, V12.D2, V17.D2
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V19.D2, V18.D2, V12.D2
	VTRN2	V19.D2, V18.D2, V13.D2
	WORD	$0x4e7c9db8 // mul v24.8h, v13.8h, v28.8h
	WORD	$0x2e7dc1b9 // umull v25.4s, v13.4h, v29.4h
	WORD	$0x6e7dc1ba // umull2 v26.4s, v13.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V12.H8, V13.H8
	VADD	V3.H8, V13.H8, V13.H8
	VADD	V24.H8, V12.H8, V12.H8
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	WORD	$0x4e7e9df8 // mul v24.8h, v15.8h, v30.8h
	WORD	$0x2e7fc1f9 // umull v25.4s, v15.4h, v31.4h
	WORD	$0x6e7fc1fa // umull2 v26.4s, v15.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V14.H8, V15.H8
	VADD	V3.H8, V15.H8, V15.H8
	VADD	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1d9 // umull v25.4s, v14.4h, v2.h[1]
	WORD	$0x6f52a1da // umull2 v26.4s, v14.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432e // mls v14.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V14.H8, V24.H8
	VUMIN	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1f9 // umull v25.4s, v15.4h, v2.h[1]
	WORD	$0x6f52a1fa // umull2 v26.4s, v15.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432f // mls v15.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V15.H8, V24.H8
	VUMIN	V24.H8, V15.H8, V15.H8
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VTRN1	V13.D2, V12.D2, V18.D2
	VTRN2	V13.D2, V12.D2, V19.D2
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V21.D2, V20.D2, V12.D2
	VTRN2	V21.D2, V20.D2, V13.D2
	WORD	$0x4e7c9db8 // mul v24.8h, v13.8h, v28.8h
	WORD	$0x2e7dc1b9 // umull v25.4s, v13.4h, v29.4h
	WORD	$0x6e7dc1ba // umull2 v26.4s, v13.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V12.H8, V13.H8
	VADD	V3.H8, V13.H8, V13.H8
	VADD	V24.H8, V12.H8, V12.H8
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	WORD	$0x4e7e9df8 // mul v24.8h, v15.8h, v30.8h
	WORD	$0x2e7fc1f9 // umull v25.4s, v15.4h, v31.4h
	WORD	$0x6e7fc1fa // umull2 v26.4s, v15.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V14.H8, V15.H8
	VADD	V3.H8, V15.H8, V15.H8
	VADD	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1d9 // umull v25.4s, v14.4h, v2.h[1]
	WORD	$0x6f52a1da // umull2 v26.4s, v14.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432e // mls v14.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V14.H8, V24.H8
	VUMIN	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1f9 // umull v25.4s, v15.4h, v2.h[1]
	WORD	$0x6f52a1fa // umull2 v26.4s, v15.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432f // mls v15.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V15.H8, V24.H8
	VUMIN	V24.H8, V15.H8, V15.H8
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VTRN1	V13.D2, V12.D2, V20.D2
	VTRN2	V13.D2, V12.D2, V21.D2
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V23.D2, V22.D2, V12.D2
	VTRN2	V23.D2, V22.D2, V13.D2
	WORD	$0x4e7c9db8 // mul v24.8h, v13.8h, v28.8h
	WORD	$0x2e7dc1b9 // umull v25.4s, v13.4h, v29.4h
	WORD	$0x6e7dc1ba // umull2 v26.4s, v13.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V12.H8, V13.H8
	VADD	V3.H8, V13.H8, V13.H8
	VADD	V24.H8, V12.H8, V12.H8
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	WORD	$0x4e7e9df8 // mul v24.8h, v15.8h, v30.8h
	WORD	$0x2e7fc1f9 // umull v25.4s, v15.4h, v31.4h
	WORD	$0x6e7fc1fa // umull2 v26.4s, v15.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VSUB	V24.H8, V14.H8, V15.H8
	VADD	V3.H8, V15.H8, V15.H8
	VADD	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1d9 // umull v25.4s, v14.4h, v2.h[1]
	WORD	$0x6f52a1da // umull2 v26.4s, v14.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432e // mls v14.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V14.H8, V24.H8
	VUMIN	V24.H8, V14.H8, V14.H8
	WORD	$0x2f52a1f9 // umull v25.4s, v15.4h, v2.h[1]
	WORD	$0x6f52a1fa // umull2 v26.4s, v15.8h, v2.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	VUSHR	$10, V25.H8, V25.H8
	WORD	$0x6f42432f // mls v15.8h, v25.8h, v2.h[0]
	VSUB	V4.H8, V15.H8, V24.H8
	VUMIN	V24.H8, V15.H8, V15.H8
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VTRN1	V13.D2, V12.D2, V22.D2
	VTRN2	V13.D2, V12.D2, V23.D2
	VST1	[V16.H8, V17.H8, V18.H8, V19.H8], (R2)
	VST1	[V20.H8, V21.H8, V22.H8, V23.H8], (R7)
	ADD	$128, R2, R2
	SUBS	$1, R3, R3
	BNE	inner
	RET

// The inverse NTT of ML-KEM (FIPS 203, Algorithm 10) of canonical coefficients, left canonical.
// func kemInverseNTTARM(f *[256]uint16)
TEXT ·kemInverseNTTARM(SB), NOSPLIT, $0-8
	MOVD	f+0(FP), R0
	MOVD	$kemConstants<>(SB), R4
	VLD1	(R4), [V2.H8, V3.H8, V4.H8]
	MOVD	$kemZetaLists<>(SB), R1
	ADD	$160, R1, R1
	MOVD	$kemZetaLanes<>+1024(SB), R5
	MOVD	R0, R2
	MOVD	$4, R3
inner:
	ADD	$64, R2, R7
	VLD1	(R2), [V16.H8, V17.H8, V18.H8, V19.H8]
	VLD1	(R7), [V20.H8, V21.H8, V22.H8, V23.H8]
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V17.D2, V16.D2, V12.D2
	VTRN2	V17.D2, V16.D2, V13.D2
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	VSUB	V14.H8, V15.H8, V27.H8
	VADD	V15.H8, V14.H8, V14.H8
	VADD	V3.H8, V27.H8, V15.H8
	WORD	$0x4e7c9df8 // mul v24.8h, v15.8h, v28.8h
	WORD	$0x2e7dc1f9 // umull v25.4s, v15.4h, v29.4h
	WORD	$0x6e7dc1fa // umull2 v26.4s, v15.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V15.B16
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VSUB	V12.H8, V13.H8, V27.H8
	VADD	V13.H8, V12.H8, V12.H8
	VSUB	V3.H8, V12.H8, V24.H8
	VUMIN	V24.H8, V12.H8, V12.H8
	VADD	V3.H8, V27.H8, V13.H8
	WORD	$0x4e7e9db8 // mul v24.8h, v13.8h, v30.8h
	WORD	$0x2e7fc1b9 // umull v25.4s, v13.4h, v31.4h
	WORD	$0x6e7fc1ba // umull2 v26.4s, v13.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V13.B16
	VTRN1	V13.D2, V12.D2, V16.D2
	VTRN2	V13.D2, V12.D2, V17.D2
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V19.D2, V18.D2, V12.D2
	VTRN2	V19.D2, V18.D2, V13.D2
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	VSUB	V14.H8, V15.H8, V27.H8
	VADD	V15.H8, V14.H8, V14.H8
	VADD	V3.H8, V27.H8, V15.H8
	WORD	$0x4e7c9df8 // mul v24.8h, v15.8h, v28.8h
	WORD	$0x2e7dc1f9 // umull v25.4s, v15.4h, v29.4h
	WORD	$0x6e7dc1fa // umull2 v26.4s, v15.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V15.B16
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VSUB	V12.H8, V13.H8, V27.H8
	VADD	V13.H8, V12.H8, V12.H8
	VSUB	V3.H8, V12.H8, V24.H8
	VUMIN	V24.H8, V12.H8, V12.H8
	VADD	V3.H8, V27.H8, V13.H8
	WORD	$0x4e7e9db8 // mul v24.8h, v13.8h, v30.8h
	WORD	$0x2e7fc1b9 // umull v25.4s, v13.4h, v31.4h
	WORD	$0x6e7fc1ba // umull2 v26.4s, v13.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V13.B16
	VTRN1	V13.D2, V12.D2, V18.D2
	VTRN2	V13.D2, V12.D2, V19.D2
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V21.D2, V20.D2, V12.D2
	VTRN2	V21.D2, V20.D2, V13.D2
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	VSUB	V14.H8, V15.H8, V27.H8
	VADD	V15.H8, V14.H8, V14.H8
	VADD	V3.H8, V27.H8, V15.H8
	WORD	$0x4e7c9df8 // mul v24.8h, v15.8h, v28.8h
	WORD	$0x2e7dc1f9 // umull v25.4s, v15.4h, v29.4h
	WORD	$0x6e7dc1fa // umull2 v26.4s, v15.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V15.B16
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VSUB	V12.H8, V13.H8, V27.H8
	VADD	V13.H8, V12.H8, V12.H8
	VSUB	V3.H8, V12.H8, V24.H8
	VUMIN	V24.H8, V12.H8, V12.H8
	VADD	V3.H8, V27.H8, V13.H8
	WORD	$0x4e7e9db8 // mul v24.8h, v13.8h, v30.8h
	WORD	$0x2e7fc1b9 // umull v25.4s, v13.4h, v31.4h
	WORD	$0x6e7fc1ba // umull2 v26.4s, v13.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V13.B16
	VTRN1	V13.D2, V12.D2, V20.D2
	VTRN2	V13.D2, V12.D2, V21.D2
	VLD1.P	64(R5), [V28.H8, V29.H8, V30.H8, V31.H8]
	VTRN1	V23.D2, V22.D2, V12.D2
	VTRN2	V23.D2, V22.D2, V13.D2
	VTRN1	V13.S4, V12.S4, V14.S4
	VTRN2	V13.S4, V12.S4, V15.S4
	VSUB	V14.H8, V15.H8, V27.H8
	VADD	V15.H8, V14.H8, V14.H8
	VADD	V3.H8, V27.H8, V15.H8
	WORD	$0x4e7c9df8 // mul v24.8h, v15.8h, v28.8h
	WORD	$0x2e7dc1f9 // umull v25.4s, v15.4h, v29.4h
	WORD	$0x6e7dc1fa // umull2 v26.4s, v15.8h, v29.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V15.B16
	VTRN1	V15.S4, V14.S4, V12.S4
	VTRN2	V15.S4, V14.S4, V13.S4
	VSUB	V12.H8, V13.H8, V27.H8
	VADD	V13.H8, V12.H8, V12.H8
	VSUB	V3.H8, V12.H8, V24.H8
	VUMIN	V24.H8, V12.H8, V12.H8
	VADD	V3.H8, V27.H8, V13.H8
	WORD	$0x4e7e9db8 // mul v24.8h, v13.8h, v30.8h
	WORD	$0x2e7fc1b9 // umull v25.4s, v13.4h, v31.4h
	WORD	$0x6e7fc1ba // umull2 v26.4s, v13.8h, v31.8h
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V13.B16
	VTRN1	V13.D2, V12.D2, V22.D2
	VTRN2	V13.D2, V12.D2, V23.D2
	VLD1.P	32(R1), [V0.H8, V1.H8]
	VSUB	V16.H8, V17.H8, V27.H8
	VADD	V17.H8, V16.H8, V16.H8
	VSUB	V3.H8, V16.H8, V24.H8
	VUMIN	V24.H8, V16.H8, V16.H8
	VADD	V3.H8, V27.H8, V17.H8
	WORD	$0x4f408238 // mul v24.8h, v17.8h, v0.h[0]
	WORD	$0x2f41a239 // umull v25.4s, v17.4h, v1.h[0]
	WORD	$0x6f41a23a // umull2 v26.4s, v17.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V17.B16
	VSUB	V18.H8, V19.H8, V27.H8
	VADD	V19.H8, V18.H8, V18.H8
	VSUB	V3.H8, V18.H8, V24.H8
	VUMIN	V24.H8, V18.H8, V18.H8
	VADD	V3.H8, V27.H8, V19.H8
	WORD	$0x4f508278 // mul v24.8h, v19.8h, v0.h[1]
	WORD	$0x2f51a279 // umull v25.4s, v19.4h, v1.h[1]
	WORD	$0x6f51a27a // umull2 v26.4s, v19.8h, v1.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V19.B16
	VSUB	V20.H8, V21.H8, V27.H8
	VADD	V21.H8, V20.H8, V20.H8
	VSUB	V3.H8, V20.H8, V24.H8
	VUMIN	V24.H8, V20.H8, V20.H8
	VADD	V3.H8, V27.H8, V21.H8
	WORD	$0x4f6082b8 // mul v24.8h, v21.8h, v0.h[2]
	WORD	$0x2f61a2b9 // umull v25.4s, v21.4h, v1.h[2]
	WORD	$0x6f61a2ba // umull2 v26.4s, v21.8h, v1.h[2]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V21.B16
	VSUB	V22.H8, V23.H8, V27.H8
	VADD	V23.H8, V22.H8, V22.H8
	VSUB	V3.H8, V22.H8, V24.H8
	VUMIN	V24.H8, V22.H8, V22.H8
	VADD	V3.H8, V27.H8, V23.H8
	WORD	$0x4f7082f8 // mul v24.8h, v23.8h, v0.h[3]
	WORD	$0x2f71a2f9 // umull v25.4s, v23.4h, v1.h[3]
	WORD	$0x6f71a2fa // umull2 v26.4s, v23.8h, v1.h[3]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V23.B16
	VSUB	V16.H8, V18.H8, V27.H8
	VADD	V18.H8, V16.H8, V16.H8
	VSUB	V3.H8, V16.H8, V24.H8
	VUMIN	V24.H8, V16.H8, V16.H8
	VADD	V3.H8, V27.H8, V18.H8
	WORD	$0x4f408a58 // mul v24.8h, v18.8h, v0.h[4]
	WORD	$0x2f41aa59 // umull v25.4s, v18.4h, v1.h[4]
	WORD	$0x6f41aa5a // umull2 v26.4s, v18.8h, v1.h[4]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V18.B16
	VSUB	V17.H8, V19.H8, V27.H8
	VADD	V19.H8, V17.H8, V17.H8
	VSUB	V3.H8, V17.H8, V24.H8
	VUMIN	V24.H8, V17.H8, V17.H8
	VADD	V3.H8, V27.H8, V19.H8
	WORD	$0x4f408a78 // mul v24.8h, v19.8h, v0.h[4]
	WORD	$0x2f41aa79 // umull v25.4s, v19.4h, v1.h[4]
	WORD	$0x6f41aa7a // umull2 v26.4s, v19.8h, v1.h[4]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V19.B16
	VSUB	V20.H8, V22.H8, V27.H8
	VADD	V22.H8, V20.H8, V20.H8
	VSUB	V3.H8, V20.H8, V24.H8
	VUMIN	V24.H8, V20.H8, V20.H8
	VADD	V3.H8, V27.H8, V22.H8
	WORD	$0x4f508ad8 // mul v24.8h, v22.8h, v0.h[5]
	WORD	$0x2f51aad9 // umull v25.4s, v22.4h, v1.h[5]
	WORD	$0x6f51aada // umull2 v26.4s, v22.8h, v1.h[5]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V22.B16
	VSUB	V21.H8, V23.H8, V27.H8
	VADD	V23.H8, V21.H8, V21.H8
	VSUB	V3.H8, V21.H8, V24.H8
	VUMIN	V24.H8, V21.H8, V21.H8
	VADD	V3.H8, V27.H8, V23.H8
	WORD	$0x4f508af8 // mul v24.8h, v23.8h, v0.h[5]
	WORD	$0x2f51aaf9 // umull v25.4s, v23.4h, v1.h[5]
	WORD	$0x6f51aafa // umull2 v26.4s, v23.8h, v1.h[5]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V23.B16
	VST1	[V16.H8, V17.H8, V18.H8, V19.H8], (R2)
	VST1	[V20.H8, V21.H8, V22.H8, V23.H8], (R7)
	ADD	$128, R2, R2
	SUBS	$1, R3, R3
	BNE	inner
// Pass 2: layers 32 and 64, then 128 with the factor 1/128 folded into its zetas.
	VLD1.P	32(R1), [V0.H8, V1.H8]
	MOVD	R0, R2
	MOVD	$4, R3
outer:
	VLD1	(R2), [V16.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V17.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V18.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V19.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V20.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V21.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V22.H8]
	ADD	$64, R2, R2
	VLD1	(R2), [V23.H8]
	VSUB	V16.H8, V17.H8, V27.H8
	VADD	V17.H8, V16.H8, V16.H8
	VSUB	V3.H8, V16.H8, V24.H8
	VUMIN	V24.H8, V16.H8, V16.H8
	VADD	V3.H8, V27.H8, V17.H8
	WORD	$0x4f408238 // mul v24.8h, v17.8h, v0.h[0]
	WORD	$0x2f41a239 // umull v25.4s, v17.4h, v1.h[0]
	WORD	$0x6f41a23a // umull2 v26.4s, v17.8h, v1.h[0]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V17.B16
	VSUB	V18.H8, V19.H8, V27.H8
	VADD	V19.H8, V18.H8, V18.H8
	VSUB	V3.H8, V18.H8, V24.H8
	VUMIN	V24.H8, V18.H8, V18.H8
	VADD	V3.H8, V27.H8, V19.H8
	WORD	$0x4f508278 // mul v24.8h, v19.8h, v0.h[1]
	WORD	$0x2f51a279 // umull v25.4s, v19.4h, v1.h[1]
	WORD	$0x6f51a27a // umull2 v26.4s, v19.8h, v1.h[1]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V19.B16
	VSUB	V20.H8, V21.H8, V27.H8
	VADD	V21.H8, V20.H8, V20.H8
	VSUB	V3.H8, V20.H8, V24.H8
	VUMIN	V24.H8, V20.H8, V20.H8
	VADD	V3.H8, V27.H8, V21.H8
	WORD	$0x4f6082b8 // mul v24.8h, v21.8h, v0.h[2]
	WORD	$0x2f61a2b9 // umull v25.4s, v21.4h, v1.h[2]
	WORD	$0x6f61a2ba // umull2 v26.4s, v21.8h, v1.h[2]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V21.B16
	VSUB	V22.H8, V23.H8, V27.H8
	VADD	V23.H8, V22.H8, V22.H8
	VSUB	V3.H8, V22.H8, V24.H8
	VUMIN	V24.H8, V22.H8, V22.H8
	VADD	V3.H8, V27.H8, V23.H8
	WORD	$0x4f7082f8 // mul v24.8h, v23.8h, v0.h[3]
	WORD	$0x2f71a2f9 // umull v25.4s, v23.4h, v1.h[3]
	WORD	$0x6f71a2fa // umull2 v26.4s, v23.8h, v1.h[3]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V23.B16
	VSUB	V16.H8, V18.H8, V27.H8
	VADD	V18.H8, V16.H8, V16.H8
	VSUB	V3.H8, V16.H8, V24.H8
	VUMIN	V24.H8, V16.H8, V16.H8
	VADD	V3.H8, V27.H8, V18.H8
	WORD	$0x4f408a58 // mul v24.8h, v18.8h, v0.h[4]
	WORD	$0x2f41aa59 // umull v25.4s, v18.4h, v1.h[4]
	WORD	$0x6f41aa5a // umull2 v26.4s, v18.8h, v1.h[4]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V18.B16
	VSUB	V17.H8, V19.H8, V27.H8
	VADD	V19.H8, V17.H8, V17.H8
	VSUB	V3.H8, V17.H8, V24.H8
	VUMIN	V24.H8, V17.H8, V17.H8
	VADD	V3.H8, V27.H8, V19.H8
	WORD	$0x4f408a78 // mul v24.8h, v19.8h, v0.h[4]
	WORD	$0x2f41aa79 // umull v25.4s, v19.4h, v1.h[4]
	WORD	$0x6f41aa7a // umull2 v26.4s, v19.8h, v1.h[4]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V19.B16
	VSUB	V20.H8, V22.H8, V27.H8
	VADD	V22.H8, V20.H8, V20.H8
	VSUB	V3.H8, V20.H8, V24.H8
	VUMIN	V24.H8, V20.H8, V20.H8
	VADD	V3.H8, V27.H8, V22.H8
	WORD	$0x4f508ad8 // mul v24.8h, v22.8h, v0.h[5]
	WORD	$0x2f51aad9 // umull v25.4s, v22.4h, v1.h[5]
	WORD	$0x6f51aada // umull2 v26.4s, v22.8h, v1.h[5]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V22.B16
	VSUB	V21.H8, V23.H8, V27.H8
	VADD	V23.H8, V21.H8, V21.H8
	VSUB	V3.H8, V21.H8, V24.H8
	VUMIN	V24.H8, V21.H8, V21.H8
	VADD	V3.H8, V27.H8, V23.H8
	WORD	$0x4f508af8 // mul v24.8h, v23.8h, v0.h[5]
	WORD	$0x2f51aaf9 // umull v25.4s, v23.4h, v1.h[5]
	WORD	$0x6f51aafa // umull2 v26.4s, v23.8h, v1.h[5]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V23.B16
	VSUB	V16.H8, V20.H8, V27.H8
	VADD	V20.H8, V16.H8, V16.H8
	VADD	V3.H8, V27.H8, V20.H8
	WORD	$0x4f708a18 // mul v24.8h, v16.8h, v0.h[7]
	WORD	$0x2f71aa19 // umull v25.4s, v16.4h, v1.h[7]
	WORD	$0x6f71aa1a // umull2 v26.4s, v16.8h, v1.h[7]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V16.B16
	VSUB	V4.H8, V16.H8, V24.H8
	VUMIN	V24.H8, V16.H8, V16.H8
	WORD	$0x4f608a98 // mul v24.8h, v20.8h, v0.h[6]
	WORD	$0x2f61aa99 // umull v25.4s, v20.4h, v1.h[6]
	WORD	$0x6f61aa9a // umull2 v26.4s, v20.8h, v1.h[6]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V20.B16
	VSUB	V4.H8, V20.H8, V24.H8
	VUMIN	V24.H8, V20.H8, V20.H8
	VSUB	V17.H8, V21.H8, V27.H8
	VADD	V21.H8, V17.H8, V17.H8
	VADD	V3.H8, V27.H8, V21.H8
	WORD	$0x4f708a38 // mul v24.8h, v17.8h, v0.h[7]
	WORD	$0x2f71aa39 // umull v25.4s, v17.4h, v1.h[7]
	WORD	$0x6f71aa3a // umull2 v26.4s, v17.8h, v1.h[7]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V17.B16
	VSUB	V4.H8, V17.H8, V24.H8
	VUMIN	V24.H8, V17.H8, V17.H8
	WORD	$0x4f608ab8 // mul v24.8h, v21.8h, v0.h[6]
	WORD	$0x2f61aab9 // umull v25.4s, v21.4h, v1.h[6]
	WORD	$0x6f61aaba // umull2 v26.4s, v21.8h, v1.h[6]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V21.B16
	VSUB	V4.H8, V21.H8, V24.H8
	VUMIN	V24.H8, V21.H8, V21.H8
	VSUB	V18.H8, V22.H8, V27.H8
	VADD	V22.H8, V18.H8, V18.H8
	VADD	V3.H8, V27.H8, V22.H8
	WORD	$0x4f708a58 // mul v24.8h, v18.8h, v0.h[7]
	WORD	$0x2f71aa59 // umull v25.4s, v18.4h, v1.h[7]
	WORD	$0x6f71aa5a // umull2 v26.4s, v18.8h, v1.h[7]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V18.B16
	VSUB	V4.H8, V18.H8, V24.H8
	VUMIN	V24.H8, V18.H8, V18.H8
	WORD	$0x4f608ad8 // mul v24.8h, v22.8h, v0.h[6]
	WORD	$0x2f61aad9 // umull v25.4s, v22.4h, v1.h[6]
	WORD	$0x6f61aada // umull2 v26.4s, v22.8h, v1.h[6]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V22.B16
	VSUB	V4.H8, V22.H8, V24.H8
	VUMIN	V24.H8, V22.H8, V22.H8
	VSUB	V19.H8, V23.H8, V27.H8
	VADD	V23.H8, V19.H8, V19.H8
	VADD	V3.H8, V27.H8, V23.H8
	WORD	$0x4f708a78 // mul v24.8h, v19.8h, v0.h[7]
	WORD	$0x2f71aa79 // umull v25.4s, v19.4h, v1.h[7]
	WORD	$0x6f71aa7a // umull2 v26.4s, v19.8h, v1.h[7]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V19.B16
	VSUB	V4.H8, V19.H8, V24.H8
	VUMIN	V24.H8, V19.H8, V19.H8
	WORD	$0x4f608af8 // mul v24.8h, v23.8h, v0.h[6]
	WORD	$0x2f61aaf9 // umull v25.4s, v23.4h, v1.h[6]
	WORD	$0x6f61aafa // umull2 v26.4s, v23.8h, v1.h[6]
	VUZP2	V26.H8, V25.H8, V25.H8
	WORD	$0x6f424338 // mls v24.8h, v25.8h, v2.h[0]
	VMOV	V24.B16, V23.B16
	VSUB	V4.H8, V23.H8, V24.H8
	VUMIN	V24.H8, V23.H8, V23.H8
	VST1	[V23.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V22.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V21.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V20.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V19.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V18.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V17.H8], (R2)
	SUB	$64, R2, R2
	VST1	[V16.H8], (R2)
	ADD	$16, R2, R2
	SUBS	$1, R3, R3
	BNE	outer
	RET

DATA kemZetaLists<>+0(SB)/2, $0x0006c1
DATA kemZetaLists<>+2(SB)/2, $0x000a14
DATA kemZetaLists<>+4(SB)/2, $0x000cd9
DATA kemZetaLists<>+6(SB)/2, $0x000a52
DATA kemZetaLists<>+8(SB)/2, $0x000276
DATA kemZetaLists<>+10(SB)/2, $0x000769
DATA kemZetaLists<>+12(SB)/2, $0x000350
DATA kemZetaLists<>+14(SB)/2, $0x000000
DATA kemZetaLists<>+16(SB)/2, $0x0084f5
DATA kemZetaLists<>+18(SB)/2, $0x00c666
DATA kemZetaLists<>+20(SB)/2, $0x00fcec
DATA kemZetaLists<>+22(SB)/2, $0x00cb2b
DATA kemZetaLists<>+24(SB)/2, $0x003072
DATA kemZetaLists<>+26(SB)/2, $0x0091e1
DATA kemZetaLists<>+28(SB)/2, $0x004136
DATA kemZetaLists<>+30(SB)/2, $0x000000
DATA kemZetaLists<>+32(SB)/2, $0x000426
DATA kemZetaLists<>+34(SB)/2, $0x00077f
DATA kemZetaLists<>+36(SB)/2, $0x000128
DATA kemZetaLists<>+38(SB)/2, $0x00098f
DATA kemZetaLists<>+40(SB)/2, $0x00053b
DATA kemZetaLists<>+42(SB)/2, $0x0005c4
DATA kemZetaLists<>+44(SB)/2, $0x000000
DATA kemZetaLists<>+46(SB)/2, $0x000000
DATA kemZetaLists<>+48(SB)/2, $0x0051aa
DATA kemZetaLists<>+50(SB)/2, $0x009392
DATA kemZetaLists<>+52(SB)/2, $0x0016c3
DATA kemZetaLists<>+54(SB)/2, $0x00bc2c
DATA kemZetaLists<>+56(SB)/2, $0x0066f8
DATA kemZetaLists<>+58(SB)/2, $0x007181
DATA kemZetaLists<>+60(SB)/2, $0x000000
DATA kemZetaLists<>+62(SB)/2, $0x000000
DATA kemZetaLists<>+64(SB)/2, $0x0000c1
DATA kemZetaLists<>+66(SB)/2, $0x00031d
DATA kemZetaLists<>+68(SB)/2, $0x000be6
DATA kemZetaLists<>+70(SB)/2, $0x000038
DATA kemZetaLists<>+72(SB)/2, $0x0008c0
DATA kemZetaLists<>+74(SB)/2, $0x000535
DATA kemZetaLists<>+76(SB)/2, $0x000000
DATA kemZetaLists<>+78(SB)/2, $0x000000
DATA kemZetaLists<>+80(SB)/2, $0x000ed7
DATA kemZetaLists<>+82(SB)/2, $0x003d4a
DATA kemZetaLists<>+84(SB)/2, $0x00ea3c
DATA kemZetaLists<>+86(SB)/2, $0x00044e
DATA kemZetaLists<>+88(SB)/2, $0x00ac41
DATA kemZetaLists<>+90(SB)/2, $0x006681
DATA kemZetaLists<>+92(SB)/2, $0x000000
DATA kemZetaLists<>+94(SB)/2, $0x000000
DATA kemZetaLists<>+96(SB)/2, $0x000ae2
DATA kemZetaLists<>+98(SB)/2, $0x000cbc
DATA kemZetaLists<>+100(SB)/2, $0x000592
DATA kemZetaLists<>+102(SB)/2, $0x00082e
DATA kemZetaLists<>+104(SB)/2, $0x000217
DATA kemZetaLists<>+106(SB)/2, $0x000b42
DATA kemZetaLists<>+108(SB)/2, $0x000000
DATA kemZetaLists<>+110(SB)/2, $0x000000
DATA kemZetaLists<>+112(SB)/2, $0x00d63e
DATA kemZetaLists<>+114(SB)/2, $0x00fab1
DATA kemZetaLists<>+116(SB)/2, $0x006da8
DATA kemZetaLists<>+118(SB)/2, $0x00a107
DATA kemZetaLists<>+120(SB)/2, $0x002924
DATA kemZetaLists<>+122(SB)/2, $0x00dda0
DATA kemZetaLists<>+124(SB)/2, $0x000000
DATA kemZetaLists<>+126(SB)/2, $0x000000
DATA kemZetaLists<>+128(SB)/2, $0x000239
DATA kemZetaLists<>+130(SB)/2, $0x0006d2
DATA kemZetaLists<>+132(SB)/2, $0x000959
DATA kemZetaLists<>+134(SB)/2, $0x000b3f
DATA kemZetaLists<>+136(SB)/2, $0x0007b6
DATA kemZetaLists<>+138(SB)/2, $0x000335
DATA kemZetaLists<>+140(SB)/2, $0x000000
DATA kemZetaLists<>+142(SB)/2, $0x000000
DATA kemZetaLists<>+144(SB)/2, $0x002bc1
DATA kemZetaLists<>+146(SB)/2, $0x008644
DATA kemZetaLists<>+148(SB)/2, $0x00b805
DATA kemZetaLists<>+150(SB)/2, $0x00dd65
DATA kemZetaLists<>+152(SB)/2, $0x0097cc
DATA kemZetaLists<>+154(SB)/2, $0x003f22
DATA kemZetaLists<>+156(SB)/2, $0x000000
DATA kemZetaLists<>+158(SB)/2, $0x000000
DATA kemZetaLists<>+160(SB)/2, $0x000335
DATA kemZetaLists<>+162(SB)/2, $0x0007b6
DATA kemZetaLists<>+164(SB)/2, $0x000b3f
DATA kemZetaLists<>+166(SB)/2, $0x000959
DATA kemZetaLists<>+168(SB)/2, $0x0006d2
DATA kemZetaLists<>+170(SB)/2, $0x000239
DATA kemZetaLists<>+172(SB)/2, $0x000000
DATA kemZetaLists<>+174(SB)/2, $0x000000
DATA kemZetaLists<>+176(SB)/2, $0x003f22
DATA kemZetaLists<>+178(SB)/2, $0x0097cc
DATA kemZetaLists<>+180(SB)/2, $0x00dd65
DATA kemZetaLists<>+182(SB)/2, $0x00b805
DATA kemZetaLists<>+184(SB)/2, $0x008644
DATA kemZetaLists<>+186(SB)/2, $0x002bc1
DATA kemZetaLists<>+188(SB)/2, $0x000000
DATA kemZetaLists<>+190(SB)/2, $0x000000
DATA kemZetaLists<>+192(SB)/2, $0x000b42
DATA kemZetaLists<>+194(SB)/2, $0x000217
DATA kemZetaLists<>+196(SB)/2, $0x00082e
DATA kemZetaLists<>+198(SB)/2, $0x000592
DATA kemZetaLists<>+200(SB)/2, $0x000cbc
DATA kemZetaLists<>+202(SB)/2, $0x000ae2
DATA kemZetaLists<>+204(SB)/2, $0x000000
DATA kemZetaLists<>+206(SB)/2, $0x000000
DATA kemZetaLists<>+208(SB)/2, $0x00dda0
DATA kemZetaLists<>+210(SB)/2, $0x002924
DATA kemZetaLists<>+212(SB)/2, $0x00a107
DATA kemZetaLists<>+214(SB)/2, $0x006da8
DATA kemZetaLists<>+216(SB)/2, $0x00fab1
DATA kemZetaLists<>+218(SB)/2, $0x00d63e
DATA kemZetaLists<>+220(SB)/2, $0x000000
DATA kemZetaLists<>+222(SB)/2, $0x000000
DATA kemZetaLists<>+224(SB)/2, $0x000535
DATA kemZetaLists<>+226(SB)/2, $0x0008c0
DATA kemZetaLists<>+228(SB)/2, $0x000038
DATA kemZetaLists<>+230(SB)/2, $0x000be6
DATA kemZetaLists<>+232(SB)/2, $0x00031d
DATA kemZetaLists<>+234(SB)/2, $0x0000c1
DATA kemZetaLists<>+236(SB)/2, $0x000000
DATA kemZetaLists<>+238(SB)/2, $0x000000
DATA kemZetaLists<>+240(SB)/2, $0x006681
DATA kemZetaLists<>+242(SB)/2, $0x00ac41
DATA kemZetaLists<>+244(SB)/2, $0x00044e
DATA kemZetaLists<>+246(SB)/2, $0x00ea3c
DATA kemZetaLists<>+248(SB)/2, $0x003d4a
DATA kemZetaLists<>+250(SB)/2, $0x000ed7
DATA kemZetaLists<>+252(SB)/2, $0x000000
DATA kemZetaLists<>+254(SB)/2, $0x000000
DATA kemZetaLists<>+256(SB)/2, $0x0005c4
DATA kemZetaLists<>+258(SB)/2, $0x00053b
DATA kemZetaLists<>+260(SB)/2, $0x00098f
DATA kemZetaLists<>+262(SB)/2, $0x000128
DATA kemZetaLists<>+264(SB)/2, $0x00077f
DATA kemZetaLists<>+266(SB)/2, $0x000426
DATA kemZetaLists<>+268(SB)/2, $0x000000
DATA kemZetaLists<>+270(SB)/2, $0x000000
DATA kemZetaLists<>+272(SB)/2, $0x007181
DATA kemZetaLists<>+274(SB)/2, $0x0066f8
DATA kemZetaLists<>+276(SB)/2, $0x00bc2c
DATA kemZetaLists<>+278(SB)/2, $0x0016c3
DATA kemZetaLists<>+280(SB)/2, $0x009392
DATA kemZetaLists<>+282(SB)/2, $0x0051aa
DATA kemZetaLists<>+284(SB)/2, $0x000000
DATA kemZetaLists<>+286(SB)/2, $0x000000
DATA kemZetaLists<>+288(SB)/2, $0x000350
DATA kemZetaLists<>+290(SB)/2, $0x000769
DATA kemZetaLists<>+292(SB)/2, $0x000276
DATA kemZetaLists<>+294(SB)/2, $0x000a52
DATA kemZetaLists<>+296(SB)/2, $0x000cd9
DATA kemZetaLists<>+298(SB)/2, $0x000a14
DATA kemZetaLists<>+300(SB)/2, $0x000674
DATA kemZetaLists<>+302(SB)/2, $0x000ce7
DATA kemZetaLists<>+304(SB)/2, $0x004136
DATA kemZetaLists<>+306(SB)/2, $0x0091e1
DATA kemZetaLists<>+308(SB)/2, $0x003072
DATA kemZetaLists<>+310(SB)/2, $0x00cb2b
DATA kemZetaLists<>+312(SB)/2, $0x00fcec
DATA kemZetaLists<>+314(SB)/2, $0x00c666
DATA kemZetaLists<>+316(SB)/2, $0x007f09
DATA kemZetaLists<>+318(SB)/2, $0x00fe00
GLOBL kemZetaLists<>(SB), RODATA|NOPTR, $320

DATA kemZetaLanes<>+0(SB)/2, $0x000121
DATA kemZetaLanes<>+2(SB)/2, $0x000121
DATA kemZetaLanes<>+4(SB)/2, $0x000121
DATA kemZetaLanes<>+6(SB)/2, $0x000121
DATA kemZetaLanes<>+8(SB)/2, $0x00014b
DATA kemZetaLanes<>+10(SB)/2, $0x00014b
DATA kemZetaLanes<>+12(SB)/2, $0x00014b
DATA kemZetaLanes<>+14(SB)/2, $0x00014b
DATA kemZetaLanes<>+16(SB)/2, $0x001639
DATA kemZetaLanes<>+18(SB)/2, $0x001639
DATA kemZetaLanes<>+20(SB)/2, $0x001639
DATA kemZetaLanes<>+22(SB)/2, $0x001639
DATA kemZetaLanes<>+24(SB)/2, $0x001974
DATA kemZetaLanes<>+26(SB)/2, $0x001974
DATA kemZetaLanes<>+28(SB)/2, $0x001974
DATA kemZetaLanes<>+30(SB)/2, $0x001974
DATA kemZetaLanes<>+32(SB)/2, $0x000011
DATA kemZetaLanes<>+34(SB)/2, $0x000011
DATA kemZetaLanes<>+36(SB)/2, $0x000ac9
DATA kemZetaLanes<>+38(SB)/2, $0x000ac9
DATA kemZetaLanes<>+40(SB)/2, $0x000247
DATA kemZetaLanes<>+42(SB)/2, $0x000247
DATA kemZetaLanes<>+44(SB)/2, $0x000a59
DATA kemZetaLanes<>+46(SB)/2, $0x000a59
DATA kemZetaLanes<>+48(SB)/2, $0x00014e
DATA kemZetaLanes<>+50(SB)/2, $0x00014e
DATA kemZetaLanes<>+52(SB)/2, $0x00d452
DATA kemZetaLanes<>+54(SB)/2, $0x00d452
DATA kemZetaLanes<>+56(SB)/2, $0x002cd5
DATA kemZetaLanes<>+58(SB)/2, $0x002cd5
DATA kemZetaLanes<>+60(SB)/2, $0x00cbb5
DATA kemZetaLanes<>+62(SB)/2, $0x00cbb5
DATA kemZetaLanes<>+64(SB)/2, $0x000cb5
DATA kemZetaLanes<>+66(SB)/2, $0x000cb5
DATA kemZetaLanes<>+68(SB)/2, $0x000cb5
DATA kemZetaLanes<>+70(SB)/2, $0x000cb5
DATA kemZetaLanes<>+72(SB)/2, $0x0006dc
DATA kemZetaLanes<>+74(SB)/2, $0x0006dc
DATA kemZetaLanes<>+76(SB)/2, $0x0006dc
DATA kemZetaLanes<>+78(SB)/2, $0x0006dc
DATA kemZetaLanes<>+80(SB)/2, $0x00fa27
DATA kemZetaLanes<>+82(SB)/2, $0x00fa27
DATA kemZetaLanes<>+84(SB)/2, $0x00fa27
DATA kemZetaLanes<>+86(SB)/2, $0x00fa27
DATA kemZetaLanes<>+88(SB)/2, $0x008709
DATA kemZetaLanes<>+90(SB)/2, $0x008709
DATA kemZetaLanes<>+92(SB)/2, $0x008709
DATA kemZetaLanes<>+94(SB)/2, $0x008709
DATA kemZetaLanes<>+96(SB)/2, $0x000665
DATA kemZetaLanes<>+98(SB)/2, $0x000665
DATA kemZetaLanes<>+100(SB)/2, $0x0002d3
DATA kemZetaLanes<>+102(SB)/2, $0x0002d3
DATA kemZetaLanes<>+104(SB)/2, $0x0008f0
DATA kemZetaLanes<>+106(SB)/2, $0x0008f0
DATA kemZetaLanes<>+108(SB)/2, $0x00044c
DATA kemZetaLanes<>+110(SB)/2, $0x00044c
DATA kemZetaLanes<>+112(SB)/2, $0x007de2
DATA kemZetaLanes<>+114(SB)/2, $0x007de2
DATA kemZetaLanes<>+116(SB)/2, $0x003799
DATA kemZetaLanes<>+118(SB)/2, $0x003799
DATA kemZetaLanes<>+120(SB)/2, $0x00aff2
DATA kemZetaLanes<>+122(SB)/2, $0x00aff2
DATA kemZetaLanes<>+124(SB)/2, $0x005497
DATA kemZetaLanes<>+126(SB)/2, $0x005497
DATA kemZetaLanes<>+128(SB)/2, $0x0004ad
DATA kemZetaLanes<>+130(SB)/2, $0x0004ad
DATA kemZetaLanes<>+132(SB)/2, $0x0004ad
DATA kemZetaLanes<>+134(SB)/2, $0x0004ad
DATA kemZetaLanes<>+136(SB)/2, $0x000900
DATA kemZetaLanes<>+138(SB)/2, $0x000900
DATA kemZetaLanes<>+140(SB)/2, $0x000900
DATA kemZetaLanes<>+142(SB)/2, $0x000900
DATA kemZetaLanes<>+144(SB)/2, $0x005c0c
DATA kemZetaLanes<>+146(SB)/2, $0x005c0c
DATA kemZetaLanes<>+148(SB)/2, $0x005c0c
DATA kemZetaLanes<>+150(SB)/2, $0x005c0c
DATA kemZetaLanes<>+152(SB)/2, $0x00b12d
DATA kemZetaLanes<>+154(SB)/2, $0x00b12d
DATA kemZetaLanes<>+156(SB)/2, $0x00b12d
DATA kemZetaLanes<>+158(SB)/2, $0x00b12d
DATA kemZetaLanes<>+160(SB)/2, $0x000581
DATA kemZetaLanes<>+162(SB)/2, $0x000581
DATA kemZetaLanes<>+164(SB)/2, $0x000a66
DATA kemZetaLanes<>+166(SB)/2, $0x000a66
DATA kemZetaLanes<>+168(SB)/2, $0x000cd1
DATA kemZetaLanes<>+170(SB)/2, $0x000cd1
DATA kemZetaLanes<>+172(SB)/2, $0x0000e9
DATA kemZetaLanes<>+174(SB)/2, $0x0000e9
DATA kemZetaLanes<>+176(SB)/2, $0x006c5a
DATA kemZetaLanes<>+178(SB)/2, $0x006c5a
DATA kemZetaLanes<>+180(SB)/2, $0x00ccb5
DATA kemZetaLanes<>+182(SB)/2, $0x00ccb5
DATA kemZetaLanes<>+184(SB)/2, $0x00fc4f
DATA kemZetaLanes<>+186(SB)/2, $0x00fc4f
DATA kemZetaLanes<>+188(SB)/2, $0x0011ea
DATA kemZetaLanes<>+190(SB)/2, $0x0011ea
DATA kemZetaLanes<>+192(SB)/2, $0x0008e5
DATA kemZetaLanes<>+194(SB)/2, $0x0008e5
DATA kemZetaLanes<>+196(SB)/2, $0x0008e5
DATA kemZetaLanes<>+198(SB)/2, $0x0008e5
DATA kemZetaLanes<>+200(SB)/2, $0x000807
DATA kemZetaLanes<>+202(SB)/2, $0x000807
DATA kemZetaLanes<>+204(SB)/2, $0x000807
DATA kemZetaLanes<>+206(SB)/2, $0x000807
DATA kemZetaLanes<>+208(SB)/2, $0x00af19
DATA kemZetaLanes<>+210(SB)/2, $0x00af19
DATA kemZetaLanes<>+212(SB)/2, $0x00af19
DATA kemZetaLanes<>+214(SB)/2, $0x00af19
DATA kemZetaLanes<>+216(SB)/2, $0x009e07
DATA kemZetaLanes<>+218(SB)/2, $0x009e07
DATA kemZetaLanes<>+220(SB)/2, $0x009e07
DATA kemZetaLanes<>+222(SB)/2, $0x009e07
DATA kemZetaLanes<>+224(SB)/2, $0x0002f4
DATA kemZetaLanes<>+226(SB)/2, $0x0002f4
DATA kemZetaLanes<>+228(SB)/2, $0x00086c
DATA kemZetaLanes<>+230(SB)/2, $0x00086c
DATA kemZetaLanes<>+232(SB)/2, $0x000bc7
DATA kemZetaLanes<>+234(SB)/2, $0x000bc7
DATA kemZetaLanes<>+236(SB)/2, $0x000bea
DATA kemZetaLanes<>+238(SB)/2, $0x000bea
DATA kemZetaLanes<>+240(SB)/2, $0x003a22
DATA kemZetaLanes<>+242(SB)/2, $0x003a22
DATA kemZetaLanes<>+244(SB)/2, $0x00a5cb
DATA kemZetaLanes<>+246(SB)/2, $0x00a5cb
DATA kemZetaLanes<>+248(SB)/2, $0x00e7da
DATA kemZetaLanes<>+250(SB)/2, $0x00e7da
DATA kemZetaLanes<>+252(SB)/2, $0x00ea8b
DATA kemZetaLanes<>+254(SB)/2, $0x00ea8b
DATA kemZetaLanes<>+256(SB)/2, $0x00028a
DATA kemZetaLanes<>+258(SB)/2, $0x00028a
DATA kemZetaLanes<>+260(SB)/2, $0x00028a
DATA kemZetaLanes<>+262(SB)/2, $0x00028a
DATA kemZetaLanes<>+264(SB)/2, $0x0007b9
DATA kemZetaLanes<>+266(SB)/2, $0x0007b9
DATA kemZetaLanes<>+268(SB)/2, $0x0007b9
DATA kemZetaLanes<>+270(SB)/2, $0x0007b9
DATA kemZetaLanes<>+272(SB)/2, $0x0031fc
DATA kemZetaLanes<>+274(SB)/2, $0x0031fc
DATA kemZetaLanes<>+276(SB)/2, $0x0031fc
DATA kemZetaLanes<>+278(SB)/2, $0x0031fc
DATA kemZetaLanes<>+280(SB)/2, $0x009807
DATA kemZetaLanes<>+282(SB)/2, $0x009807
DATA kemZetaLanes<>+284(SB)/2, $0x009807
DATA kemZetaLanes<>+286(SB)/2, $0x009807
DATA kemZetaLanes<>+288(SB)/2, $0x0006a7
DATA kemZetaLanes<>+290(SB)/2, $0x0006a7
DATA kemZetaLanes<>+292(SB)/2, $0x000673
DATA kemZetaLanes<>+294(SB)/2, $0x000673
DATA kemZetaLanes<>+296(SB)/2, $0x000ae5
DATA kemZetaLanes<>+298(SB)/2, $0x000ae5
DATA kemZetaLanes<>+300(SB)/2, $0x0006fd
DATA kemZetaLanes<>+302(SB)/2, $0x0006fd
DATA kemZetaLanes<>+304(SB)/2, $0x0082f5
DATA kemZetaLanes<>+306(SB)/2, $0x0082f5
DATA kemZetaLanes<>+308(SB)/2, $0x007ef6
DATA kemZetaLanes<>+310(SB)/2, $0x007ef6
DATA kemZetaLanes<>+312(SB)/2, $0x00d679
DATA kemZetaLanes<>+314(SB)/2, $0x00d679
DATA kemZetaLanes<>+316(SB)/2, $0x008992
DATA kemZetaLanes<>+318(SB)/2, $0x008992
DATA kemZetaLanes<>+320(SB)/2, $0x0009d1
DATA kemZetaLanes<>+322(SB)/2, $0x0009d1
DATA kemZetaLanes<>+324(SB)/2, $0x0009d1
DATA kemZetaLanes<>+326(SB)/2, $0x0009d1
DATA kemZetaLanes<>+328(SB)/2, $0x000278
DATA kemZetaLanes<>+330(SB)/2, $0x000278
DATA kemZetaLanes<>+332(SB)/2, $0x000278
DATA kemZetaLanes<>+334(SB)/2, $0x000278
DATA kemZetaLanes<>+336(SB)/2, $0x00c13f
DATA kemZetaLanes<>+338(SB)/2, $0x00c13f
DATA kemZetaLanes<>+340(SB)/2, $0x00c13f
DATA kemZetaLanes<>+342(SB)/2, $0x00c13f
DATA kemZetaLanes<>+344(SB)/2, $0x003099
DATA kemZetaLanes<>+346(SB)/2, $0x003099
DATA kemZetaLanes<>+348(SB)/2, $0x003099
DATA kemZetaLanes<>+350(SB)/2, $0x003099
DATA kemZetaLanes<>+352(SB)/2, $0x000737
DATA kemZetaLanes<>+354(SB)/2, $0x000737
DATA kemZetaLanes<>+356(SB)/2, $0x0003b8
DATA kemZetaLanes<>+358(SB)/2, $0x0003b8
DATA kemZetaLanes<>+360(SB)/2, $0x0005b5
DATA kemZetaLanes<>+362(SB)/2, $0x0005b5
DATA kemZetaLanes<>+364(SB)/2, $0x000a7f
DATA kemZetaLanes<>+366(SB)/2, $0x000a7f
DATA kemZetaLanes<>+368(SB)/2, $0x008e08
DATA kemZetaLanes<>+370(SB)/2, $0x008e08
DATA kemZetaLanes<>+372(SB)/2, $0x004935
DATA kemZetaLanes<>+374(SB)/2, $0x004935
DATA kemZetaLanes<>+376(SB)/2, $0x007059
DATA kemZetaLanes<>+378(SB)/2, $0x007059
DATA kemZetaLanes<>+380(SB)/2, $0x00cea1
DATA kemZetaLanes<>+382(SB)/2, $0x00cea1
DATA kemZetaLanes<>+384(SB)/2, $0x000b31
DATA kemZetaLanes<>+386(SB)/2, $0x000b31
DATA kemZetaLanes<>+388(SB)/2, $0x000b31
DATA kemZetaLanes<>+390(SB)/2, $0x000b31
DATA kemZetaLanes<>+392(SB)/2, $0x000021
DATA kemZetaLanes<>+394(SB)/2, $0x000021
DATA kemZetaLanes<>+396(SB)/2, $0x000021
DATA kemZetaLanes<>+398(SB)/2, $0x000021
DATA kemZetaLanes<>+400(SB)/2, $0x00dc51
DATA kemZetaLanes<>+402(SB)/2, $0x00dc51
DATA kemZetaLanes<>+404(SB)/2, $0x00dc51
DATA kemZetaLanes<>+406(SB)/2, $0x00dc51
DATA kemZetaLanes<>+408(SB)/2, $0x000289
DATA kemZetaLanes<>+410(SB)/2, $0x000289
DATA kemZetaLanes<>+412(SB)/2, $0x000289
DATA kemZetaLanes<>+414(SB)/2, $0x000289
DATA kemZetaLanes<>+416(SB)/2, $0x0003ab
DATA kemZetaLanes<>+418(SB)/2, $0x0003ab
DATA kemZetaLanes<>+420(SB)/2, $0x000904
DATA kemZetaLanes<>+422(SB)/2, $0x000904
DATA kemZetaLanes<>+424(SB)/2, $0x000985
DATA kemZetaLanes<>+426(SB)/2, $0x000985
DATA kemZetaLanes<>+428(SB)/2, $0x000954
DATA kemZetaLanes<>+430(SB)/2, $0x000954
DATA kemZetaLanes<>+432(SB)/2, $0x004835
DATA kemZetaLanes<>+434(SB)/2, $0x004835
DATA kemZetaLanes<>+436(SB)/2, $0x00b17c
DATA kemZetaLanes<>+438(SB)/2, $0x00b17c
DATA kemZetaLanes<>+440(SB)/2, $0x00bb67
DATA kemZetaLanes<>+442(SB)/2, $0x00bb67
DATA kemZetaLanes<>+444(SB)/2, $0x00b7a3
DATA kemZetaLanes<>+446(SB)/2, $0x00b7a3
DATA kemZetaLanes<>+448(SB)/2, $0x000528
DATA kemZetaLanes<>+450(SB)/2, $0x000528
DATA kemZetaLanes<>+452(SB)/2, $0x000528
DATA kemZetaLanes<>+454(SB)/2, $0x000528
DATA kemZetaLanes<>+456(SB)/2, $0x00077b
DATA kemZetaLanes<>+458(SB)/2, $0x00077b
DATA kemZetaLanes<>+460(SB)/2, $0x00077b
DATA kemZetaLanes<>+462(SB)/2, $0x00077b
DATA kemZetaLanes<>+464(SB)/2, $0x006582
DATA kemZetaLanes<>+466(SB)/2, $0x006582
DATA kemZetaLanes<>+468(SB)/2, $0x006582
DATA kemZetaLanes<>+470(SB)/2, $0x006582
DATA kemZetaLanes<>+472(SB)/2, $0x009343
DATA kemZetaLanes<>+474(SB)/2, $0x009343
DATA kemZetaLanes<>+476(SB)/2, $0x009343
DATA kemZetaLanes<>+478(SB)/2, $0x009343
DATA kemZetaLanes<>+480(SB)/2, $0x0002dd
DATA kemZetaLanes<>+482(SB)/2, $0x0002dd
DATA kemZetaLanes<>+484(SB)/2, $0x000921
DATA kemZetaLanes<>+486(SB)/2, $0x000921
DATA kemZetaLanes<>+488(SB)/2, $0x00010c
DATA kemZetaLanes<>+490(SB)/2, $0x00010c
DATA kemZetaLanes<>+492(SB)/2, $0x000281
DATA kemZetaLanes<>+494(SB)/2, $0x000281
DATA kemZetaLanes<>+496(SB)/2, $0x00385e
DATA kemZetaLanes<>+498(SB)/2, $0x00385e
DATA kemZetaLanes<>+500(SB)/2, $0x00b3b7
DATA kemZetaLanes<>+502(SB)/2, $0x00b3b7
DATA kemZetaLanes<>+504(SB)/2, $0x00149b
DATA kemZetaLanes<>+506(SB)/2, $0x00149b
DATA kemZetaLanes<>+508(SB)/2, $0x00314a
DATA kemZetaLanes<>+510(SB)/2, $0x00314a
DATA kemZetaLanes<>+512(SB)/2, $0x00090f
DATA kemZetaLanes<>+514(SB)/2, $0x00090f
DATA kemZetaLanes<>+516(SB)/2, $0x00090f
DATA kemZetaLanes<>+518(SB)/2, $0x00090f
DATA kemZetaLanes<>+520(SB)/2, $0x00059b
DATA kemZetaLanes<>+522(SB)/2, $0x00059b
DATA kemZetaLanes<>+524(SB)/2, $0x00059b
DATA kemZetaLanes<>+526(SB)/2, $0x00059b
DATA kemZetaLanes<>+528(SB)/2, $0x00b254
DATA kemZetaLanes<>+530(SB)/2, $0x00b254
DATA kemZetaLanes<>+532(SB)/2, $0x00b254
DATA kemZetaLanes<>+534(SB)/2, $0x00b254
DATA kemZetaLanes<>+536(SB)/2, $0x006e59
DATA kemZetaLanes<>+538(SB)/2, $0x006e59
DATA kemZetaLanes<>+540(SB)/2, $0x006e59
DATA kemZetaLanes<>+542(SB)/2, $0x006e59
DATA kemZetaLanes<>+544(SB)/2, $0x000630
DATA kemZetaLanes<>+546(SB)/2, $0x000630
DATA kemZetaLanes<>+548(SB)/2, $0x0008fa
DATA kemZetaLanes<>+550(SB)/2, $0x0008fa
DATA kemZetaLanes<>+552(SB)/2, $0x0007f5
DATA kemZetaLanes<>+554(SB)/2, $0x0007f5
DATA kemZetaLanes<>+556(SB)/2, $0x000c94
DATA kemZetaLanes<>+558(SB)/2, $0x000c94
DATA kemZetaLanes<>+560(SB)/2, $0x0079cf
DATA kemZetaLanes<>+562(SB)/2, $0x0079cf
DATA kemZetaLanes<>+564(SB)/2, $0x00b0b7
DATA kemZetaLanes<>+566(SB)/2, $0x00b0b7
DATA kemZetaLanes<>+568(SB)/2, $0x009ca5
DATA kemZetaLanes<>+570(SB)/2, $0x009ca5
DATA kemZetaLanes<>+572(SB)/2, $0x00f79e
DATA kemZetaLanes<>+574(SB)/2, $0x00f79e
DATA kemZetaLanes<>+576(SB)/2, $0x000327
DATA kemZetaLanes<>+578(SB)/2, $0x000327
DATA kemZetaLanes<>+580(SB)/2, $0x000327
DATA kemZetaLanes<>+582(SB)/2, $0x000327
DATA kemZetaLanes<>+584(SB)/2, $0x0001c4
DATA kemZetaLanes<>+586(SB)/2, $0x0001c4
DATA kemZetaLanes<>+588(SB)/2, $0x0001c4
DATA kemZetaLanes<>+590(SB)/2, $0x0001c4
DATA kemZetaLanes<>+592(SB)/2, $0x003e0e
DATA kemZetaLanes<>+594(SB)/2, $0x003e0e
DATA kemZetaLanes<>+596(SB)/2, $0x003e0e
DATA kemZetaLanes<>+598(SB)/2, $0x003e0e
DATA kemZetaLanes<>+600(SB)/2, $0x0022c2
DATA kemZetaLanes<>+602(SB)/2, $0x0022c2
DATA kemZetaLanes<>+604(SB)/2, $0x0022c2
DATA kemZetaLanes<>+606(SB)/2, $0x0022c2
DATA kemZetaLanes<>+608(SB)/2, $0x000177
DATA kemZetaLanes<>+610(SB)/2, $0x000177
DATA kemZetaLanes<>+612(SB)/2, $0x0009f5
DATA kemZetaLanes<>+614(SB)/2, $0x0009f5
DATA kemZetaLanes<>+616(SB)/2, $0x00082a
DATA kemZetaLanes<>+618(SB)/2, $0x00082a
DATA kemZetaLanes<>+620(SB)/2, $0x00066d
DATA kemZetaLanes<>+622(SB)/2, $0x00066d
DATA kemZetaLanes<>+624(SB)/2, $0x001cd6
DATA kemZetaLanes<>+626(SB)/2, $0x001cd6
DATA kemZetaLanes<>+628(SB)/2, $0x00c404
DATA kemZetaLanes<>+630(SB)/2, $0x00c404
DATA kemZetaLanes<>+632(SB)/2, $0x00a0b8
DATA kemZetaLanes<>+634(SB)/2, $0x00a0b8
DATA kemZetaLanes<>+636(SB)/2, $0x007e80
DATA kemZetaLanes<>+638(SB)/2, $0x007e80
DATA kemZetaLanes<>+640(SB)/2, $0x00059e
DATA kemZetaLanes<>+642(SB)/2, $0x00059e
DATA kemZetaLanes<>+644(SB)/2, $0x00059e
DATA kemZetaLanes<>+646(SB)/2, $0x00059e
DATA kemZetaLanes<>+648(SB)/2, $0x000b34
DATA kemZetaLanes<>+650(SB)/2, $0x000b34
DATA kemZetaLanes<>+652(SB)/2, $0x000b34
DATA kemZetaLanes<>+654(SB)/2, $0x000b34
DATA kemZetaLanes<>+656(SB)/2, $0x006e95
DATA kemZetaLanes<>+658(SB)/2, $0x006e95
DATA kemZetaLanes<>+660(SB)/2, $0x006e95
DATA kemZetaLanes<>+662(SB)/2, $0x006e95
DATA kemZetaLanes<>+664(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+666(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+668(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+670(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+672(SB)/2, $0x000427
DATA kemZetaLanes<>+674(SB)/2, $0x000427
DATA kemZetaLanes<>+676(SB)/2, $0x00013f
DATA kemZetaLanes<>+678(SB)/2, $0x00013f
DATA kemZetaLanes<>+680(SB)/2, $0x000ad5
DATA kemZetaLanes<>+682(SB)/2, $0x000ad5
DATA kemZetaLanes<>+684(SB)/2, $0x0002f5
DATA kemZetaLanes<>+686(SB)/2, $0x0002f5
DATA kemZetaLanes<>+688(SB)/2, $0x0051be
DATA kemZetaLanes<>+690(SB)/2, $0x0051be
DATA kemZetaLanes<>+692(SB)/2, $0x001887
DATA kemZetaLanes<>+694(SB)/2, $0x001887
DATA kemZetaLanes<>+696(SB)/2, $0x00d53e
DATA kemZetaLanes<>+698(SB)/2, $0x00d53e
DATA kemZetaLanes<>+700(SB)/2, $0x003a36
DATA kemZetaLanes<>+702(SB)/2, $0x003a36
DATA kemZetaLanes<>+704(SB)/2, $0x0005fe
DATA kemZetaLanes<>+706(SB)/2, $0x0005fe
DATA kemZetaLanes<>+708(SB)/2, $0x0005fe
DATA kemZetaLanes<>+710(SB)/2, $0x0005fe
DATA kemZetaLanes<>+712(SB)/2, $0x000962
DATA kemZetaLanes<>+714(SB)/2, $0x000962
DATA kemZetaLanes<>+716(SB)/2, $0x000962
DATA kemZetaLanes<>+718(SB)/2, $0x000962
DATA kemZetaLanes<>+720(SB)/2, $0x0075f6
DATA kemZetaLanes<>+722(SB)/2, $0x0075f6
DATA kemZetaLanes<>+724(SB)/2, $0x0075f6
DATA kemZetaLanes<>+726(SB)/2, $0x0075f6
DATA kemZetaLanes<>+728(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+730(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+732(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+734(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+736(SB)/2, $0x000833
DATA kemZetaLanes<>+738(SB)/2, $0x000833
DATA kemZetaLanes<>+740(SB)/2, $0x000231
DATA kemZetaLanes<>+742(SB)/2, $0x000231
DATA kemZetaLanes<>+744(SB)/2, $0x0009a2
DATA kemZetaLanes<>+746(SB)/2, $0x0009a2
DATA kemZetaLanes<>+748(SB)/2, $0x000a22
DATA kemZetaLanes<>+750(SB)/2, $0x000a22
DATA kemZetaLanes<>+752(SB)/2, $0x00a169
DATA kemZetaLanes<>+754(SB)/2, $0x00a169
DATA kemZetaLanes<>+756(SB)/2, $0x002b24
DATA kemZetaLanes<>+758(SB)/2, $0x002b24
DATA kemZetaLanes<>+760(SB)/2, $0x00bda2
DATA kemZetaLanes<>+762(SB)/2, $0x00bda2
DATA kemZetaLanes<>+764(SB)/2, $0x00c77a
DATA kemZetaLanes<>+766(SB)/2, $0x00c77a
DATA kemZetaLanes<>+768(SB)/2, $0x000a57
DATA kemZetaLanes<>+770(SB)/2, $0x000a57
DATA kemZetaLanes<>+772(SB)/2, $0x000a57
DATA kemZetaLanes<>+774(SB)/2, $0x000a57
DATA kemZetaLanes<>+776(SB)/2, $0x000a39
DATA kemZetaLanes<>+778(SB)/2, $0x000a39
DATA kemZetaLanes<>+780(SB)/2, $0x000a39
DATA kemZetaLanes<>+782(SB)/2, $0x000a39
DATA kemZetaLanes<>+784(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+786(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+788(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+790(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+792(SB)/2, $0x00c93f
DATA kemZetaLanes<>+794(SB)/2, $0x00c93f
DATA kemZetaLanes<>+796(SB)/2, $0x00c93f
DATA kemZetaLanes<>+798(SB)/2, $0x00c93f
DATA kemZetaLanes<>+800(SB)/2, $0x000af4
DATA kemZetaLanes<>+802(SB)/2, $0x000af4
DATA kemZetaLanes<>+804(SB)/2, $0x000444
DATA kemZetaLanes<>+806(SB)/2, $0x000444
DATA kemZetaLanes<>+808(SB)/2, $0x000193
DATA kemZetaLanes<>+810(SB)/2, $0x000193
DATA kemZetaLanes<>+812(SB)/2, $0x000402
DATA kemZetaLanes<>+814(SB)/2, $0x000402
DATA kemZetaLanes<>+816(SB)/2, $0x00d7a0
DATA kemZetaLanes<>+818(SB)/2, $0x00d7a0
DATA kemZetaLanes<>+820(SB)/2, $0x0053f9
DATA kemZetaLanes<>+822(SB)/2, $0x0053f9
DATA kemZetaLanes<>+824(SB)/2, $0x001efd
DATA kemZetaLanes<>+826(SB)/2, $0x001efd
DATA kemZetaLanes<>+828(SB)/2, $0x004ee6
DATA kemZetaLanes<>+830(SB)/2, $0x004ee6
DATA kemZetaLanes<>+832(SB)/2, $0x0005c9
DATA kemZetaLanes<>+834(SB)/2, $0x0005c9
DATA kemZetaLanes<>+836(SB)/2, $0x0005c9
DATA kemZetaLanes<>+838(SB)/2, $0x0005c9
DATA kemZetaLanes<>+840(SB)/2, $0x000288
DATA kemZetaLanes<>+842(SB)/2, $0x000288
DATA kemZetaLanes<>+844(SB)/2, $0x000288
DATA kemZetaLanes<>+846(SB)/2, $0x000288
DATA kemZetaLanes<>+848(SB)/2, $0x0071e3
DATA kemZetaLanes<>+850(SB)/2, $0x0071e3
DATA kemZetaLanes<>+852(SB)/2, $0x0071e3
DATA kemZetaLanes<>+854(SB)/2, $0x0071e3
DATA kemZetaLanes<>+856(SB)/2, $0x0031d4
DATA kemZetaLanes<>+858(SB)/2, $0x0031d4
DATA kemZetaLanes<>+860(SB)/2, $0x0031d4
DATA kemZetaLanes<>+862(SB)/2, $0x0031d4
DATA kemZetaLanes<>+864(SB)/2, $0x000477
DATA kemZetaLanes<>+866(SB)/2, $0x000477
DATA kemZetaLanes<>+868(SB)/2, $0x000866
DATA kemZetaLanes<>+870(SB)/2, $0x000866
DATA kemZetaLanes<>+872(SB)/2, $0x000ad7
DATA kemZetaLanes<>+874(SB)/2, $0x000ad7
DATA kemZetaLanes<>+876(SB)/2, $0x000376
DATA kemZetaLanes<>+878(SB)/2, $0x000376
DATA kemZetaLanes<>+880(SB)/2, $0x0057e5
DATA kemZetaLanes<>+882(SB)/2, $0x0057e5
DATA kemZetaLanes<>+884(SB)/2, $0x00a555
DATA kemZetaLanes<>+886(SB)/2, $0x00a555
DATA kemZetaLanes<>+888(SB)/2, $0x00d565
DATA kemZetaLanes<>+890(SB)/2, $0x00d565
DATA kemZetaLanes<>+892(SB)/2, $0x004422
DATA kemZetaLanes<>+894(SB)/2, $0x004422
DATA kemZetaLanes<>+896(SB)/2, $0x0009aa
DATA kemZetaLanes<>+898(SB)/2, $0x0009aa
DATA kemZetaLanes<>+900(SB)/2, $0x0009aa
DATA kemZetaLanes<>+902(SB)/2, $0x0009aa
DATA kemZetaLanes<>+904(SB)/2, $0x000c26
DATA kemZetaLanes<>+906(SB)/2, $0x000c26
DATA kemZetaLanes<>+908(SB)/2, $0x000c26
DATA kemZetaLanes<>+910(SB)/2, $0x000c26
DATA kemZetaLanes<>+912(SB)/2, $0x00be40
DATA kemZetaLanes<>+914(SB)/2, $0x00be40
DATA kemZetaLanes<>+916(SB)/2, $0x00be40
DATA kemZetaLanes<>+918(SB)/2, $0x00be40
DATA kemZetaLanes<>+920(SB)/2, $0x00ef28
DATA kemZetaLanes<>+922(SB)/2, $0x00ef28
DATA kemZetaLanes<>+924(SB)/2, $0x00ef28
DATA kemZetaLanes<>+926(SB)/2, $0x00ef28
DATA kemZetaLanes<>+928(SB)/2, $0x0006ba
DATA kemZetaLanes<>+930(SB)/2, $0x0006ba
DATA kemZetaLanes<>+932(SB)/2, $0x0004bc
DATA kemZetaLanes<>+934(SB)/2, $0x0004bc
DATA kemZetaLanes<>+936(SB)/2, $0x000752
DATA kemZetaLanes<>+938(SB)/2, $0x000752
DATA kemZetaLanes<>+940(SB)/2, $0x000405
DATA kemZetaLanes<>+942(SB)/2, $0x000405
DATA kemZetaLanes<>+944(SB)/2, $0x00846b
DATA kemZetaLanes<>+946(SB)/2, $0x00846b
DATA kemZetaLanes<>+948(SB)/2, $0x005d33
DATA kemZetaLanes<>+950(SB)/2, $0x005d33
DATA kemZetaLanes<>+952(SB)/2, $0x00901c
DATA kemZetaLanes<>+954(SB)/2, $0x00901c
DATA kemZetaLanes<>+956(SB)/2, $0x004f21
DATA kemZetaLanes<>+958(SB)/2, $0x004f21
DATA kemZetaLanes<>+960(SB)/2, $0x0004cb
DATA kemZetaLanes<>+962(SB)/2, $0x0004cb
DATA kemZetaLanes<>+964(SB)/2, $0x0004cb
DATA kemZetaLanes<>+966(SB)/2, $0x0004cb
DATA kemZetaLanes<>+968(SB)/2, $0x00038e
DATA kemZetaLanes<>+970(SB)/2, $0x00038e
DATA kemZetaLanes<>+972(SB)/2, $0x00038e
DATA kemZetaLanes<>+974(SB)/2, $0x00038e
DATA kemZetaLanes<>+976(SB)/2, $0x005e5b
DATA kemZetaLanes<>+978(SB)/2, $0x005e5b
DATA kemZetaLanes<>+980(SB)/2, $0x005e5b
DATA kemZetaLanes<>+982(SB)/2, $0x005e5b
DATA kemZetaLanes<>+984(SB)/2, $0x0045fa
DATA kemZetaLanes<>+986(SB)/2, $0x0045fa
DATA kemZetaLanes<>+988(SB)/2, $0x0045fa
DATA kemZetaLanes<>+990(SB)/2, $0x0045fa
DATA kemZetaLanes<>+992(SB)/2, $0x00083e
DATA kemZetaLanes<>+994(SB)/2, $0x00083e
DATA kemZetaLanes<>+996(SB)/2, $0x000b77
DATA kemZetaLanes<>+998(SB)/2, $0x000b77
DATA kemZetaLanes<>+1000(SB)/2, $0x000375
DATA kemZetaLanes<>+1002(SB)/2, $0x000375
DATA kemZetaLanes<>+1004(SB)/2, $0x00086a
DATA kemZetaLanes<>+1006(SB)/2, $0x00086a
DATA kemZetaLanes<>+1008(SB)/2, $0x00a242
DATA kemZetaLanes<>+1010(SB)/2, $0x00a242
DATA kemZetaLanes<>+1012(SB)/2, $0x00e1b3
DATA kemZetaLanes<>+1014(SB)/2, $0x00e1b3
DATA kemZetaLanes<>+1016(SB)/2, $0x00440e
DATA kemZetaLanes<>+1018(SB)/2, $0x00440e
DATA kemZetaLanes<>+1020(SB)/2, $0x00a5a4
DATA kemZetaLanes<>+1022(SB)/2, $0x00a5a4
DATA kemZetaLanes<>+1024(SB)/2, $0x00086a
DATA kemZetaLanes<>+1026(SB)/2, $0x00086a
DATA kemZetaLanes<>+1028(SB)/2, $0x000375
DATA kemZetaLanes<>+1030(SB)/2, $0x000375
DATA kemZetaLanes<>+1032(SB)/2, $0x000b77
DATA kemZetaLanes<>+1034(SB)/2, $0x000b77
DATA kemZetaLanes<>+1036(SB)/2, $0x00083e
DATA kemZetaLanes<>+1038(SB)/2, $0x00083e
DATA kemZetaLanes<>+1040(SB)/2, $0x00a5a4
DATA kemZetaLanes<>+1042(SB)/2, $0x00a5a4
DATA kemZetaLanes<>+1044(SB)/2, $0x00440e
DATA kemZetaLanes<>+1046(SB)/2, $0x00440e
DATA kemZetaLanes<>+1048(SB)/2, $0x00e1b3
DATA kemZetaLanes<>+1050(SB)/2, $0x00e1b3
DATA kemZetaLanes<>+1052(SB)/2, $0x00a242
DATA kemZetaLanes<>+1054(SB)/2, $0x00a242
DATA kemZetaLanes<>+1056(SB)/2, $0x00038e
DATA kemZetaLanes<>+1058(SB)/2, $0x00038e
DATA kemZetaLanes<>+1060(SB)/2, $0x00038e
DATA kemZetaLanes<>+1062(SB)/2, $0x00038e
DATA kemZetaLanes<>+1064(SB)/2, $0x0004cb
DATA kemZetaLanes<>+1066(SB)/2, $0x0004cb
DATA kemZetaLanes<>+1068(SB)/2, $0x0004cb
DATA kemZetaLanes<>+1070(SB)/2, $0x0004cb
DATA kemZetaLanes<>+1072(SB)/2, $0x0045fa
DATA kemZetaLanes<>+1074(SB)/2, $0x0045fa
DATA kemZetaLanes<>+1076(SB)/2, $0x0045fa
DATA kemZetaLanes<>+1078(SB)/2, $0x0045fa
DATA kemZetaLanes<>+1080(SB)/2, $0x005e5b
DATA kemZetaLanes<>+1082(SB)/2, $0x005e5b
DATA kemZetaLanes<>+1084(SB)/2, $0x005e5b
DATA kemZetaLanes<>+1086(SB)/2, $0x005e5b
DATA kemZetaLanes<>+1088(SB)/2, $0x000405
DATA kemZetaLanes<>+1090(SB)/2, $0x000405
DATA kemZetaLanes<>+1092(SB)/2, $0x000752
DATA kemZetaLanes<>+1094(SB)/2, $0x000752
DATA kemZetaLanes<>+1096(SB)/2, $0x0004bc
DATA kemZetaLanes<>+1098(SB)/2, $0x0004bc
DATA kemZetaLanes<>+1100(SB)/2, $0x0006ba
DATA kemZetaLanes<>+1102(SB)/2, $0x0006ba
DATA kemZetaLanes<>+1104(SB)/2, $0x004f21
DATA kemZetaLanes<>+1106(SB)/2, $0x004f21
DATA kemZetaLanes<>+1108(SB)/2, $0x00901c
DATA kemZetaLanes<>+1110(SB)/2, $0x00901c
DATA kemZetaLanes<>+1112(SB)/2, $0x005d33
DATA kemZetaLanes<>+1114(SB)/2, $0x005d33
DATA kemZetaLanes<>+1116(SB)/2, $0x00846b
DATA kemZetaLanes<>+1118(SB)/2, $0x00846b
DATA kemZetaLanes<>+1120(SB)/2, $0x000c26
DATA kemZetaLanes<>+1122(SB)/2, $0x000c26
DATA kemZetaLanes<>+1124(SB)/2, $0x000c26
DATA kemZetaLanes<>+1126(SB)/2, $0x000c26
DATA kemZetaLanes<>+1128(SB)/2, $0x0009aa
DATA kemZetaLanes<>+1130(SB)/2, $0x0009aa
DATA kemZetaLanes<>+1132(SB)/2, $0x0009aa
DATA kemZetaLanes<>+1134(SB)/2, $0x0009aa
DATA kemZetaLanes<>+1136(SB)/2, $0x00ef28
DATA kemZetaLanes<>+1138(SB)/2, $0x00ef28
DATA kemZetaLanes<>+1140(SB)/2, $0x00ef28
DATA kemZetaLanes<>+1142(SB)/2, $0x00ef28
DATA kemZetaLanes<>+1144(SB)/2, $0x00be40
DATA kemZetaLanes<>+1146(SB)/2, $0x00be40
DATA kemZetaLanes<>+1148(SB)/2, $0x00be40
DATA kemZetaLanes<>+1150(SB)/2, $0x00be40
DATA kemZetaLanes<>+1152(SB)/2, $0x000376
DATA kemZetaLanes<>+1154(SB)/2, $0x000376
DATA kemZetaLanes<>+1156(SB)/2, $0x000ad7
DATA kemZetaLanes<>+1158(SB)/2, $0x000ad7
DATA kemZetaLanes<>+1160(SB)/2, $0x000866
DATA kemZetaLanes<>+1162(SB)/2, $0x000866
DATA kemZetaLanes<>+1164(SB)/2, $0x000477
DATA kemZetaLanes<>+1166(SB)/2, $0x000477
DATA kemZetaLanes<>+1168(SB)/2, $0x004422
DATA kemZetaLanes<>+1170(SB)/2, $0x004422
DATA kemZetaLanes<>+1172(SB)/2, $0x00d565
DATA kemZetaLanes<>+1174(SB)/2, $0x00d565
DATA kemZetaLanes<>+1176(SB)/2, $0x00a555
DATA kemZetaLanes<>+1178(SB)/2, $0x00a555
DATA kemZetaLanes<>+1180(SB)/2, $0x0057e5
DATA kemZetaLanes<>+1182(SB)/2, $0x0057e5
DATA kemZetaLanes<>+1184(SB)/2, $0x000288
DATA kemZetaLanes<>+1186(SB)/2, $0x000288
DATA kemZetaLanes<>+1188(SB)/2, $0x000288
DATA kemZetaLanes<>+1190(SB)/2, $0x000288
DATA kemZetaLanes<>+1192(SB)/2, $0x0005c9
DATA kemZetaLanes<>+1194(SB)/2, $0x0005c9
DATA kemZetaLanes<>+1196(SB)/2, $0x0005c9
DATA kemZetaLanes<>+1198(SB)/2, $0x0005c9
DATA kemZetaLanes<>+1200(SB)/2, $0x0031d4
DATA kemZetaLanes<>+1202(SB)/2, $0x0031d4
DATA kemZetaLanes<>+1204(SB)/2, $0x0031d4
DATA kemZetaLanes<>+1206(SB)/2, $0x0031d4
DATA kemZetaLanes<>+1208(SB)/2, $0x0071e3
DATA kemZetaLanes<>+1210(SB)/2, $0x0071e3
DATA kemZetaLanes<>+1212(SB)/2, $0x0071e3
DATA kemZetaLanes<>+1214(SB)/2, $0x0071e3
DATA kemZetaLanes<>+1216(SB)/2, $0x000402
DATA kemZetaLanes<>+1218(SB)/2, $0x000402
DATA kemZetaLanes<>+1220(SB)/2, $0x000193
DATA kemZetaLanes<>+1222(SB)/2, $0x000193
DATA kemZetaLanes<>+1224(SB)/2, $0x000444
DATA kemZetaLanes<>+1226(SB)/2, $0x000444
DATA kemZetaLanes<>+1228(SB)/2, $0x000af4
DATA kemZetaLanes<>+1230(SB)/2, $0x000af4
DATA kemZetaLanes<>+1232(SB)/2, $0x004ee6
DATA kemZetaLanes<>+1234(SB)/2, $0x004ee6
DATA kemZetaLanes<>+1236(SB)/2, $0x001efd
DATA kemZetaLanes<>+1238(SB)/2, $0x001efd
DATA kemZetaLanes<>+1240(SB)/2, $0x0053f9
DATA kemZetaLanes<>+1242(SB)/2, $0x0053f9
DATA kemZetaLanes<>+1244(SB)/2, $0x00d7a0
DATA kemZetaLanes<>+1246(SB)/2, $0x00d7a0
DATA kemZetaLanes<>+1248(SB)/2, $0x000a39
DATA kemZetaLanes<>+1250(SB)/2, $0x000a39
DATA kemZetaLanes<>+1252(SB)/2, $0x000a39
DATA kemZetaLanes<>+1254(SB)/2, $0x000a39
DATA kemZetaLanes<>+1256(SB)/2, $0x000a57
DATA kemZetaLanes<>+1258(SB)/2, $0x000a57
DATA kemZetaLanes<>+1260(SB)/2, $0x000a57
DATA kemZetaLanes<>+1262(SB)/2, $0x000a57
DATA kemZetaLanes<>+1264(SB)/2, $0x00c93f
DATA kemZetaLanes<>+1266(SB)/2, $0x00c93f
DATA kemZetaLanes<>+1268(SB)/2, $0x00c93f
DATA kemZetaLanes<>+1270(SB)/2, $0x00c93f
DATA kemZetaLanes<>+1272(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+1274(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+1276(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+1278(SB)/2, $0x00cb8d
DATA kemZetaLanes<>+1280(SB)/2, $0x000a22
DATA kemZetaLanes<>+1282(SB)/2, $0x000a22
DATA kemZetaLanes<>+1284(SB)/2, $0x0009a2
DATA kemZetaLanes<>+1286(SB)/2, $0x0009a2
DATA kemZetaLanes<>+1288(SB)/2, $0x000231
DATA kemZetaLanes<>+1290(SB)/2, $0x000231
DATA kemZetaLanes<>+1292(SB)/2, $0x000833
DATA kemZetaLanes<>+1294(SB)/2, $0x000833
DATA kemZetaLanes<>+1296(SB)/2, $0x00c77a
DATA kemZetaLanes<>+1298(SB)/2, $0x00c77a
DATA kemZetaLanes<>+1300(SB)/2, $0x00bda2
DATA kemZetaLanes<>+1302(SB)/2, $0x00bda2
DATA kemZetaLanes<>+1304(SB)/2, $0x002b24
DATA kemZetaLanes<>+1306(SB)/2, $0x002b24
DATA kemZetaLanes<>+1308(SB)/2, $0x00a169
DATA kemZetaLanes<>+1310(SB)/2, $0x00a169
DATA kemZetaLanes<>+1312(SB)/2, $0x000962
DATA kemZetaLanes<>+1314(SB)/2, $0x000962
DATA kemZetaLanes<>+1316(SB)/2, $0x000962
DATA kemZetaLanes<>+1318(SB)/2, $0x000962
DATA kemZetaLanes<>+1320(SB)/2, $0x0005fe
DATA kemZetaLanes<>+1322(SB)/2, $0x0005fe
DATA kemZetaLanes<>+1324(SB)/2, $0x0005fe
DATA kemZetaLanes<>+1326(SB)/2, $0x0005fe
DATA kemZetaLanes<>+1328(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+1330(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+1332(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+1334(SB)/2, $0x00b8b6
DATA kemZetaLanes<>+1336(SB)/2, $0x0075f6
DATA kemZetaLanes<>+1338(SB)/2, $0x0075f6
DATA kemZetaLanes<>+1340(SB)/2, $0x0075f6
DATA kemZetaLanes<>+1342(SB)/2, $0x0075f6
DATA kemZetaLanes<>+1344(SB)/2, $0x0002f5
DATA kemZetaLanes<>+1346(SB)/2, $0x0002f5
DATA kemZetaLanes<>+1348(SB)/2, $0x000ad5
DATA kemZetaLanes<>+1350(SB)/2, $0x000ad5
DATA kemZetaLanes<>+1352(SB)/2, $0x00013f
DATA kemZetaLanes<>+1354(SB)/2, $0x00013f
DATA kemZetaLanes<>+1356(SB)/2, $0x000427
DATA kemZetaLanes<>+1358(SB)/2, $0x000427
DATA kemZetaLanes<>+1360(SB)/2, $0x003a36
DATA kemZetaLanes<>+1362(SB)/2, $0x003a36
DATA kemZetaLanes<>+1364(SB)/2, $0x00d53e
DATA kemZetaLanes<>+1366(SB)/2, $0x00d53e
DATA kemZetaLanes<>+1368(SB)/2, $0x001887
DATA kemZetaLanes<>+1370(SB)/2, $0x001887
DATA kemZetaLanes<>+1372(SB)/2, $0x0051be
DATA kemZetaLanes<>+1374(SB)/2, $0x0051be
DATA kemZetaLanes<>+1376(SB)/2, $0x000b34
DATA kemZetaLanes<>+1378(SB)/2, $0x000b34
DATA kemZetaLanes<>+1380(SB)/2, $0x000b34
DATA kemZetaLanes<>+1382(SB)/2, $0x000b34
DATA kemZetaLanes<>+1384(SB)/2, $0x00059e
DATA kemZetaLanes<>+1386(SB)/2, $0x00059e
DATA kemZetaLanes<>+1388(SB)/2, $0x00059e
DATA kemZetaLanes<>+1390(SB)/2, $0x00059e
DATA kemZetaLanes<>+1392(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+1394(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+1396(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+1398(SB)/2, $0x00dc8c
DATA kemZetaLanes<>+1400(SB)/2, $0x006e95
DATA kemZetaLanes<>+1402(SB)/2, $0x006e95
DATA kemZetaLanes<>+1404(SB)/2, $0x006e95
DATA kemZetaLanes<>+1406(SB)/2, $0x006e95
DATA kemZetaLanes<>+1408(SB)/2, $0x00066d
DATA kemZetaLanes<>+1410(SB)/2, $0x00066d
DATA kemZetaLanes<>+1412(SB)/2, $0x00082a
DATA kemZetaLanes<>+1414(SB)/2, $0x00082a
DATA kemZetaLanes<>+1416(SB)/2, $0x0009f5
DATA kemZetaLanes<>+1418(SB)/2, $0x0009f5
DATA kemZetaLanes<>+1420(SB)/2, $0x000177
DATA kemZetaLanes<>+1422(SB)/2, $0x000177
DATA kemZetaLanes<>+1424(SB)/2, $0x007e80
DATA kemZetaLanes<>+1426(SB)/2, $0x007e80
DATA kemZetaLanes<>+1428(SB)/2, $0x00a0b8
DATA kemZetaLanes<>+1430(SB)/2, $0x00a0b8
DATA kemZetaLanes<>+1432(SB)/2, $0x00c404
DATA kemZetaLanes<>+1434(SB)/2, $0x00c404
DATA kemZetaLanes<>+1436(SB)/2, $0x001cd6
DATA kemZetaLanes<>+1438(SB)/2, $0x001cd6
DATA kemZetaLanes<>+1440(SB)/2, $0x0001c4
DATA kemZetaLanes<>+1442(SB)/2, $0x0001c4
DATA kemZetaLanes<>+1444(SB)/2, $0x0001c4
DATA kemZetaLanes<>+1446(SB)/2, $0x0001c4
DATA kemZetaLanes<>+1448(SB)/2, $0x000327
DATA kemZetaLanes<>+1450(SB)/2, $0x000327
DATA kemZetaLanes<>+1452(SB)/2, $0x000327
DATA kemZetaLanes<>+1454(SB)/2, $0x000327
DATA kemZetaLanes<>+1456(SB)/2, $0x0022c2
DATA kemZetaLanes<>+1458(SB)/2, $0x0022c2
DATA kemZetaLanes<>+1460(SB)/2, $0x0022c2
DATA kemZetaLanes<>+1462(SB)/2, $0x0022c2
DATA kemZetaLanes<>+1464(SB)/2, $0x003e0e
DATA kemZetaLanes<>+1466(SB)/2, $0x003e0e
DATA kemZetaLanes<>+1468(SB)/2, $0x003e0e
DATA kemZetaLanes<>+1470(SB)/2, $0x003e0e
DATA kemZetaLanes<>+1472(SB)/2, $0x000c94
DATA kemZetaLanes<>+1474(SB)/2, $0x000c94
DATA kemZetaLanes<>+1476(SB)/2, $0x0007f5
DATA kemZetaLanes<>+1478(SB)/2, $0x0007f5
DATA kemZetaLanes<>+1480(SB)/2, $0x0008fa
DATA kemZetaLanes<>+1482(SB)/2, $0x0008fa
DATA kemZetaLanes<>+1484(SB)/2, $0x000630
DATA kemZetaLanes<>+1486(SB)/2, $0x000630
DATA kemZetaLanes<>+1488(SB)/2, $0x00f79e
DATA kemZetaLanes<>+1490(SB)/2, $0x00f79e
DATA kemZetaLanes<>+1492(SB)/2, $0x009ca5
DATA kemZetaLanes<>+1494(SB)/2, $0x009ca5
DATA kemZetaLanes<>+1496(SB)/2, $0x00b0b7
DATA kemZetaLanes<>+1498(SB)/2, $0x00b0b7
DATA kemZetaLanes<>+1500(SB)/2, $0x0079cf
DATA kemZetaLanes<>+1502(SB)/2, $0x0079cf
DATA kemZetaLanes<>+1504(SB)/2, $0x00059b
DATA kemZetaLanes<>+1506(SB)/2, $0x00059b
DATA kemZetaLanes<>+1508(SB)/2, $0x00059b
DATA kemZetaLanes<>+1510(SB)/2, $0x00059b
DATA kemZetaLanes<>+1512(SB)/2, $0x00090f
DATA kemZetaLanes<>+1514(SB)/2, $0x00090f
DATA kemZetaLanes<>+1516(SB)/2, $0x00090f
DATA kemZetaLanes<>+1518(SB)/2, $0x00090f
DATA kemZetaLanes<>+1520(SB)/2, $0x006e59
DATA kemZetaLanes<>+1522(SB)/2, $0x006e59
DATA kemZetaLanes<>+1524(SB)/2, $0x006e59
DATA kemZetaLanes<>+1526(SB)/2, $0x006e59
DATA kemZetaLanes<>+1528(SB)/2, $0x00b254
DATA kemZetaLanes<>+1530(SB)/2, $0x00b254
DATA kemZetaLanes<>+1532(SB)/2, $0x00b254
DATA kemZetaLanes<>+1534(SB)/2, $0x00b254
DATA kemZetaLanes<>+1536(SB)/2, $0x000281
DATA kemZetaLanes<>+1538(SB)/2, $0x000281
DATA kemZetaLanes<>+1540(SB)/2, $0x00010c
DATA kemZetaLanes<>+1542(SB)/2, $0x00010c
DATA kemZetaLanes<>+1544(SB)/2, $0x000921
DATA kemZetaLanes<>+1546(SB)/2, $0x000921
DATA kemZetaLanes<>+1548(SB)/2, $0x0002dd
DATA kemZetaLanes<>+1550(SB)/2, $0x0002dd
DATA kemZetaLanes<>+1552(SB)/2, $0x00314a
DATA kemZetaLanes<>+1554(SB)/2, $0x00314a
DATA kemZetaLanes<>+1556(SB)/2, $0x00149b
DATA kemZetaLanes<>+1558(SB)/2, $0x00149b
DATA kemZetaLanes<>+1560(SB)/2, $0x00b3b7
DATA kemZetaLanes<>+1562(SB)/2, $0x00b3b7
DATA kemZetaLanes<>+1564(SB)/2, $0x00385e
DATA kemZetaLanes<>+1566(SB)/2, $0x00385e
DATA kemZetaLanes<>+1568(SB)/2, $0x00077b
DATA kemZetaLanes<>+1570(SB)/2, $0x00077b
DATA kemZetaLanes<>+1572(SB)/2, $0x00077b
DATA kemZetaLanes<>+1574(SB)/2, $0x00077b
DATA kemZetaLanes<>+1576(SB)/2, $0x000528
DATA kemZetaLanes<>+1578(SB)/2, $0x000528
DATA kemZetaLanes<>+1580(SB)/2, $0x000528
DATA kemZetaLanes<>+1582(SB)/2, $0x000528
DATA kemZetaLanes<>+1584(SB)/2, $0x009343
DATA kemZetaLanes<>+1586(SB)/2, $0x009343
DATA kemZetaLanes<>+1588(SB)/2, $0x009343
DATA kemZetaLanes<>+1590(SB)/2, $0x009343
DATA kemZetaLanes<>+1592(SB)/2, $0x006582
DATA kemZetaLanes<>+1594(SB)/2, $0x006582
DATA kemZetaLanes<>+1596(SB)/2, $0x006582
DATA kemZetaLanes<>+1598(SB)/2, $0x006582
DATA kemZetaLanes<>+1600(SB)/2, $0x000954
DATA kemZetaLanes<>+1602(SB)/2, $0x000954
DATA kemZetaLanes<>+1604(SB)/2, $0x000985
DATA kemZetaLanes<>+1606(SB)/2, $0x000985
DATA kemZetaLanes<>+1608(SB)/2, $0x000904
DATA kemZetaLanes<>+1610(SB)/2, $0x000904
DATA kemZetaLanes<>+1612(SB)/2, $0x0003ab
DATA kemZetaLanes<>+1614(SB)/2, $0x0003ab
DATA kemZetaLanes<>+1616(SB)/2, $0x00b7a3
DATA kemZetaLanes<>+1618(SB)/2, $0x00b7a3
DATA kemZetaLanes<>+1620(SB)/2, $0x00bb67
DATA kemZetaLanes<>+1622(SB)/2, $0x00bb67
DATA kemZetaLanes<>+1624(SB)/2, $0x00b17c
DATA kemZetaLanes<>+1626(SB)/2, $0x00b17c
DATA kemZetaLanes<>+1628(SB)/2, $0x004835
DATA kemZetaLanes<>+1630(SB)/2, $0x004835
DATA kemZetaLanes<>+1632(SB)/2, $0x000021
DATA kemZetaLanes<>+1634(SB)/2, $0x000021
DATA kemZetaLanes<>+1636(SB)/2, $0x000021
DATA kemZetaLanes<>+1638(SB)/2, $0x000021
DATA kemZetaLanes<>+1640(SB)/2, $0x000b31
DATA kemZetaLanes<>+1642(SB)/2, $0x000b31
DATA kemZetaLanes<>+1644(SB)/2, $0x000b31
DATA kemZetaLanes<>+1646(SB)/2, $0x000b31
DATA kemZetaLanes<>+1648(SB)/2, $0x000289
DATA kemZetaLanes<>+1650(SB)/2, $0x000289
DATA kemZetaLanes<>+1652(SB)/2, $0x000289
DATA kemZetaLanes<>+1654(SB)/2, $0x000289
DATA kemZetaLanes<>+1656(SB)/2, $0x00dc51
DATA kemZetaLanes<>+1658(SB)/2, $0x00dc51
DATA kemZetaLanes<>+1660(SB)/2, $0x00dc51
DATA kemZetaLanes<>+1662(SB)/2, $0x00dc51
DATA kemZetaLanes<>+1664(SB)/2, $0x000a7f
DATA kemZetaLanes<>+1666(SB)/2, $0x000a7f
DATA kemZetaLanes<>+1668(SB)/2, $0x0005b5
DATA kemZetaLanes<>+1670(SB)/2, $0x0005b5
DATA kemZetaLanes<>+1672(SB)/2, $0x0003b8
DATA kemZetaLanes<>+1674(SB)/2, $0x0003b8
DATA kemZetaLanes<>+1676(SB)/2, $0x000737
DATA kemZetaLanes<>+1678(SB)/2, $0x000737
DATA kemZetaLanes<>+1680(SB)/2, $0x00cea1
DATA kemZetaLanes<>+1682(SB)/2, $0x00cea1
DATA kemZetaLanes<>+1684(SB)/2, $0x007059
DATA kemZetaLanes<>+1686(SB)/2, $0x007059
DATA kemZetaLanes<>+1688(SB)/2, $0x004935
DATA kemZetaLanes<>+1690(SB)/2, $0x004935
DATA kemZetaLanes<>+1692(SB)/2, $0x008e08
DATA kemZetaLanes<>+1694(SB)/2, $0x008e08
DATA kemZetaLanes<>+1696(SB)/2, $0x000278
DATA kemZetaLanes<>+1698(SB)/2, $0x000278
DATA kemZetaLanes<>+1700(SB)/2, $0x000278
DATA kemZetaLanes<>+1702(SB)/2, $0x000278
DATA kemZetaLanes<>+1704(SB)/2, $0x0009d1
DATA kemZetaLanes<>+1706(SB)/2, $0x0009d1
DATA kemZetaLanes<>+1708(SB)/2, $0x0009d1
DATA kemZetaLanes<>+1710(SB)/2, $0x0009d1
DATA kemZetaLanes<>+1712(SB)/2, $0x003099
DATA kemZetaLanes<>+1714(SB)/2, $0x003099
DATA kemZetaLanes<>+1716(SB)/2, $0x003099
DATA kemZetaLanes<>+1718(SB)/2, $0x003099
DATA kemZetaLanes<>+1720(SB)/2, $0x00c13f
DATA kemZetaLanes<>+1722(SB)/2, $0x00c13f
DATA kemZetaLanes<>+1724(SB)/2, $0x00c13f
DATA kemZetaLanes<>+1726(SB)/2, $0x00c13f
DATA kemZetaLanes<>+1728(SB)/2, $0x0006fd
DATA kemZetaLanes<>+1730(SB)/2, $0x0006fd
DATA kemZetaLanes<>+1732(SB)/2, $0x000ae5
DATA kemZetaLanes<>+1734(SB)/2, $0x000ae5
DATA kemZetaLanes<>+1736(SB)/2, $0x000673
DATA kemZetaLanes<>+1738(SB)/2, $0x000673
DATA kemZetaLanes<>+1740(SB)/2, $0x0006a7
DATA kemZetaLanes<>+1742(SB)/2, $0x0006a7
DATA kemZetaLanes<>+1744(SB)/2, $0x008992
DATA kemZetaLanes<>+1746(SB)/2, $0x008992
DATA kemZetaLanes<>+1748(SB)/2, $0x00d679
DATA kemZetaLanes<>+1750(SB)/2, $0x00d679
DATA kemZetaLanes<>+1752(SB)/2, $0x007ef6
DATA kemZetaLanes<>+1754(SB)/2, $0x007ef6
DATA kemZetaLanes<>+1756(SB)/2, $0x0082f5
DATA kemZetaLanes<>+1758(SB)/2, $0x0082f5
DATA kemZetaLanes<>+1760(SB)/2, $0x0007b9
DATA kemZetaLanes<>+1762(SB)/2, $0x0007b9
DATA kemZetaLanes<>+1764(SB)/2, $0x0007b9
DATA kemZetaLanes<>+1766(SB)/2, $0x0007b9
DATA kemZetaLanes<>+1768(SB)/2, $0x00028a
DATA kemZetaLanes<>+1770(SB)/2, $0x00028a
DATA kemZetaLanes<>+1772(SB)/2, $0x00028a
DATA kemZetaLanes<>+1774(SB)/2, $0x00028a
DATA kemZetaLanes<>+1776(SB)/2, $0x009807
DATA kemZetaLanes<>+1778(SB)/2, $0x009807
DATA kemZetaLanes<>+1780(SB)/2, $0x009807
DATA kemZetaLanes<>+1782(SB)/2, $0x009807
DATA kemZetaLanes<>+1784(SB)/2, $0x0031fc
DATA kemZetaLanes<>+1786(SB)/2, $0x0031fc
DATA kemZetaLanes<>+1788(SB)/2, $0x0031fc
DATA kemZetaLanes<>+1790(SB)/2, $0x0031fc
DATA kemZetaLanes<>+1792(SB)/2, $0x000bea
DATA kemZetaLanes<>+1794(SB)/2, $0x000bea
DATA kemZetaLanes<>+1796(SB)/2, $0x000bc7
DATA kemZetaLanes<>+1798(SB)/2, $0x000bc7
DATA kemZetaLanes<>+1800(SB)/2, $0x00086c
DATA kemZetaLanes<>+1802(SB)/2, $0x00086c
DATA kemZetaLanes<>+1804(SB)/2, $0x0002f4
DATA kemZetaLanes<>+1806(SB)/2, $0x0002f4
DATA kemZetaLanes<>+1808(SB)/2, $0x00ea8b
DATA kemZetaLanes<>+1810(SB)/2, $0x00ea8b
DATA kemZetaLanes<>+1812(SB)/2, $0x00e7da
DATA kemZetaLanes<>+1814(SB)/2, $0x00e7da
DATA kemZetaLanes<>+1816(SB)/2, $0x00a5cb
DATA kemZetaLanes<>+1818(SB)/2, $0x00a5cb
DATA kemZetaLanes<>+1820(SB)/2, $0x003a22
DATA kemZetaLanes<>+1822(SB)/2, $0x003a22
DATA kemZetaLanes<>+1824(SB)/2, $0x000807
DATA kemZetaLanes<>+1826(SB)/2, $0x000807
DATA kemZetaLanes<>+1828(SB)/2, $0x000807
DATA kemZetaLanes<>+1830(SB)/2, $0x000807
DATA kemZetaLanes<>+1832(SB)/2, $0x0008e5
DATA kemZetaLanes<>+1834(SB)/2, $0x0008e5
DATA kemZetaLanes<>+1836(SB)/2, $0x0008e5
DATA kemZetaLanes<>+1838(SB)/2, $0x0008e5
DATA kemZetaLanes<>+1840(SB)/2, $0x009e07
DATA kemZetaLanes<>+1842(SB)/2, $0x009e07
DATA kemZetaLanes<>+1844(SB)/2, $0x009e07
DATA kemZetaLanes<>+1846(SB)/2, $0x009e07
DATA kemZetaLanes<>+1848(SB)/2, $0x00af19
DATA kemZetaLanes<>+1850(SB)/2, $0x00af19
DATA kemZetaLanes<>+1852(SB)/2, $0x00af19
DATA kemZetaLanes<>+1854(SB)/2, $0x00af19
DATA kemZetaLanes<>+1856(SB)/2, $0x0000e9
DATA kemZetaLanes<>+1858(SB)/2, $0x0000e9
DATA kemZetaLanes<>+1860(SB)/2, $0x000cd1
DATA kemZetaLanes<>+1862(SB)/2, $0x000cd1
DATA kemZetaLanes<>+1864(SB)/2, $0x000a66
DATA kemZetaLanes<>+1866(SB)/2, $0x000a66
DATA kemZetaLanes<>+1868(SB)/2, $0x000581
DATA kemZetaLanes<>+1870(SB)/2, $0x000581
DATA kemZetaLanes<>+1872(SB)/2, $0x0011ea
DATA kemZetaLanes<>+1874(SB)/2, $0x0011ea
DATA kemZetaLanes<>+1876(SB)/2, $0x00fc4f
DATA kemZetaLanes<>+1878(SB)/2, $0x00fc4f
DATA kemZetaLanes<>+1880(SB)/2, $0x00ccb5
DATA kemZetaLanes<>+1882(SB)/2, $0x00ccb5
DATA kemZetaLanes<>+1884(SB)/2, $0x006c5a
DATA kemZetaLanes<>+1886(SB)/2, $0x006c5a
DATA kemZetaLanes<>+1888(SB)/2, $0x000900
DATA kemZetaLanes<>+1890(SB)/2, $0x000900
DATA kemZetaLanes<>+1892(SB)/2, $0x000900
DATA kemZetaLanes<>+1894(SB)/2, $0x000900
DATA kemZetaLanes<>+1896(SB)/2, $0x0004ad
DATA kemZetaLanes<>+1898(SB)/2, $0x0004ad
DATA kemZetaLanes<>+1900(SB)/2, $0x0004ad
DATA kemZetaLanes<>+1902(SB)/2, $0x0004ad
DATA kemZetaLanes<>+1904(SB)/2, $0x00b12d
DATA kemZetaLanes<>+1906(SB)/2, $0x00b12d
DATA kemZetaLanes<>+1908(SB)/2, $0x00b12d
DATA kemZetaLanes<>+1910(SB)/2, $0x00b12d
DATA kemZetaLanes<>+1912(SB)/2, $0x005c0c
DATA kemZetaLanes<>+1914(SB)/2, $0x005c0c
DATA kemZetaLanes<>+1916(SB)/2, $0x005c0c
DATA kemZetaLanes<>+1918(SB)/2, $0x005c0c
DATA kemZetaLanes<>+1920(SB)/2, $0x00044c
DATA kemZetaLanes<>+1922(SB)/2, $0x00044c
DATA kemZetaLanes<>+1924(SB)/2, $0x0008f0
DATA kemZetaLanes<>+1926(SB)/2, $0x0008f0
DATA kemZetaLanes<>+1928(SB)/2, $0x0002d3
DATA kemZetaLanes<>+1930(SB)/2, $0x0002d3
DATA kemZetaLanes<>+1932(SB)/2, $0x000665
DATA kemZetaLanes<>+1934(SB)/2, $0x000665
DATA kemZetaLanes<>+1936(SB)/2, $0x005497
DATA kemZetaLanes<>+1938(SB)/2, $0x005497
DATA kemZetaLanes<>+1940(SB)/2, $0x00aff2
DATA kemZetaLanes<>+1942(SB)/2, $0x00aff2
DATA kemZetaLanes<>+1944(SB)/2, $0x003799
DATA kemZetaLanes<>+1946(SB)/2, $0x003799
DATA kemZetaLanes<>+1948(SB)/2, $0x007de2
DATA kemZetaLanes<>+1950(SB)/2, $0x007de2
DATA kemZetaLanes<>+1952(SB)/2, $0x0006dc
DATA kemZetaLanes<>+1954(SB)/2, $0x0006dc
DATA kemZetaLanes<>+1956(SB)/2, $0x0006dc
DATA kemZetaLanes<>+1958(SB)/2, $0x0006dc
DATA kemZetaLanes<>+1960(SB)/2, $0x000cb5
DATA kemZetaLanes<>+1962(SB)/2, $0x000cb5
DATA kemZetaLanes<>+1964(SB)/2, $0x000cb5
DATA kemZetaLanes<>+1966(SB)/2, $0x000cb5
DATA kemZetaLanes<>+1968(SB)/2, $0x008709
DATA kemZetaLanes<>+1970(SB)/2, $0x008709
DATA kemZetaLanes<>+1972(SB)/2, $0x008709
DATA kemZetaLanes<>+1974(SB)/2, $0x008709
DATA kemZetaLanes<>+1976(SB)/2, $0x00fa27
DATA kemZetaLanes<>+1978(SB)/2, $0x00fa27
DATA kemZetaLanes<>+1980(SB)/2, $0x00fa27
DATA kemZetaLanes<>+1982(SB)/2, $0x00fa27
DATA kemZetaLanes<>+1984(SB)/2, $0x000a59
DATA kemZetaLanes<>+1986(SB)/2, $0x000a59
DATA kemZetaLanes<>+1988(SB)/2, $0x000247
DATA kemZetaLanes<>+1990(SB)/2, $0x000247
DATA kemZetaLanes<>+1992(SB)/2, $0x000ac9
DATA kemZetaLanes<>+1994(SB)/2, $0x000ac9
DATA kemZetaLanes<>+1996(SB)/2, $0x000011
DATA kemZetaLanes<>+1998(SB)/2, $0x000011
DATA kemZetaLanes<>+2000(SB)/2, $0x00cbb5
DATA kemZetaLanes<>+2002(SB)/2, $0x00cbb5
DATA kemZetaLanes<>+2004(SB)/2, $0x002cd5
DATA kemZetaLanes<>+2006(SB)/2, $0x002cd5
DATA kemZetaLanes<>+2008(SB)/2, $0x00d452
DATA kemZetaLanes<>+2010(SB)/2, $0x00d452
DATA kemZetaLanes<>+2012(SB)/2, $0x00014e
DATA kemZetaLanes<>+2014(SB)/2, $0x00014e
DATA kemZetaLanes<>+2016(SB)/2, $0x00014b
DATA kemZetaLanes<>+2018(SB)/2, $0x00014b
DATA kemZetaLanes<>+2020(SB)/2, $0x00014b
DATA kemZetaLanes<>+2022(SB)/2, $0x00014b
DATA kemZetaLanes<>+2024(SB)/2, $0x000121
DATA kemZetaLanes<>+2026(SB)/2, $0x000121
DATA kemZetaLanes<>+2028(SB)/2, $0x000121
DATA kemZetaLanes<>+2030(SB)/2, $0x000121
DATA kemZetaLanes<>+2032(SB)/2, $0x001974
DATA kemZetaLanes<>+2034(SB)/2, $0x001974
DATA kemZetaLanes<>+2036(SB)/2, $0x001974
DATA kemZetaLanes<>+2038(SB)/2, $0x001974
DATA kemZetaLanes<>+2040(SB)/2, $0x001639
DATA kemZetaLanes<>+2042(SB)/2, $0x001639
DATA kemZetaLanes<>+2044(SB)/2, $0x001639
DATA kemZetaLanes<>+2046(SB)/2, $0x001639
GLOBL kemZetaLanes<>(SB), RODATA|NOPTR, $2048

DATA kemConstants<>+0(SB)/2, $0x000d01
DATA kemConstants<>+2(SB)/2, $0x004ebe
DATA kemConstants<>+4(SB)/2, $0x000000
DATA kemConstants<>+6(SB)/2, $0x000000
DATA kemConstants<>+8(SB)/2, $0x000000
DATA kemConstants<>+10(SB)/2, $0x000000
DATA kemConstants<>+12(SB)/2, $0x000000
DATA kemConstants<>+14(SB)/2, $0x000000
DATA kemConstants<>+16(SB)/2, $0x001a02
DATA kemConstants<>+18(SB)/2, $0x001a02
DATA kemConstants<>+20(SB)/2, $0x001a02
DATA kemConstants<>+22(SB)/2, $0x001a02
DATA kemConstants<>+24(SB)/2, $0x001a02
DATA kemConstants<>+26(SB)/2, $0x001a02
DATA kemConstants<>+28(SB)/2, $0x001a02
DATA kemConstants<>+30(SB)/2, $0x001a02
DATA kemConstants<>+32(SB)/2, $0x000d01
DATA kemConstants<>+34(SB)/2, $0x000d01
DATA kemConstants<>+36(SB)/2, $0x000d01
DATA kemConstants<>+38(SB)/2, $0x000d01
DATA kemConstants<>+40(SB)/2, $0x000d01
DATA kemConstants<>+42(SB)/2, $0x000d01
DATA kemConstants<>+44(SB)/2, $0x000d01
DATA kemConstants<>+46(SB)/2, $0x000d01
GLOBL kemConstants<>(SB), RODATA|NOPTR, $48
