// Code generated by internal/asmgen. DO NOT EDIT.

//go:build !purego

#include "textflag.h"

// The NTT of ML-DSA (FIPS 204, Algorithm 41) of canonical coefficients, left canonical.
// func dsaNTTARM(w *[256]uint32)
TEXT ·dsaNTTARM(SB), NOSPLIT, $0-8
	MOVD	w+0(FP), R0
	MOVD	$dsaConstants<>(SB), R4
	VLD1	(R4), [V16.S4, V17.S4]
// Pass 1: layers 128, 64 and 32 on the vectors j, j + 8, ..., j + 56.
	MOVD	$dsaForwardZetas<>(SB), R1
	VLD1.P	32(R1), [V11.S4, V12.S4]
	VLD1.P	32(R1), [V13.S4, V14.S4]
	MOVD	R0, R2
	MOVD	$8, R3
outer:
	VLD1	(R2), [V0.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V1.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V2.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V3.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V4.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V5.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V6.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V7.S4]
	WORD	$0x4f8b8088 // mul v8.4s, v4.4s, v11.s[0]
	WORD	$0x2f8da089 // umull v9.2d, v4.2s, v13.s[0]
	WORD	$0x6f8da08a // umull2 v10.2d, v4.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V4.S4
	VADD	V17.S4, V4.S4, V4.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4f8b80a8 // mul v8.4s, v5.4s, v11.s[0]
	WORD	$0x2f8da0a9 // umull v9.2d, v5.2s, v13.s[0]
	WORD	$0x6f8da0aa // umull2 v10.2d, v5.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V1.S4, V5.S4
	VADD	V17.S4, V5.S4, V5.S4
	VADD	V8.S4, V1.S4, V1.S4
	WORD	$0x4f8b80c8 // mul v8.4s, v6.4s, v11.s[0]
	WORD	$0x2f8da0c9 // umull v9.2d, v6.2s, v13.s[0]
	WORD	$0x6f8da0ca // umull2 v10.2d, v6.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V2.S4, V6.S4
	VADD	V17.S4, V6.S4, V6.S4
	VADD	V8.S4, V2.S4, V2.S4
	WORD	$0x4f8b80e8 // mul v8.4s, v7.4s, v11.s[0]
	WORD	$0x2f8da0e9 // umull v9.2d, v7.2s, v13.s[0]
	WORD	$0x6f8da0ea // umull2 v10.2d, v7.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V3.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V3.S4, V3.S4
	WORD	$0x4fab8048 // mul v8.4s, v2.4s, v11.s[1]
	WORD	$0x2fada049 // umull v9.2d, v2.2s, v13.s[1]
	WORD	$0x6fada04a // umull2 v10.2d, v2.4s, v13.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V2.S4
	VADD	V17.S4, V2.S4, V2.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4fab8068 // mul v8.4s, v3.4s, v11.s[1]
	WORD	$0x2fada069 // umull v9.2d, v3.2s, v13.s[1]
	WORD	$0x6fada06a // umull2 v10.2d, v3.4s, v13.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V1.S4, V3.S4
	VADD	V17.S4, V3.S4, V3.S4
	VADD	V8.S4, V1.S4, V1.S4
	WORD	$0x4f8b88c8 // mul v8.4s, v6.4s, v11.s[2]
	WORD	$0x2f8da8c9 // umull v9.2d, v6.2s, v13.s[2]
	WORD	$0x6f8da8ca // umull2 v10.2d, v6.4s, v13.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V4.S4, V6.S4
	VADD	V17.S4, V6.S4, V6.S4
	VADD	V8.S4, V4.S4, V4.S4
	WORD	$0x4f8b88e8 // mul v8.4s, v7.4s, v11.s[2]
	WORD	$0x2f8da8e9 // umull v9.2d, v7.2s, v13.s[2]
	WORD	$0x6f8da8ea // umull2 v10.2d, v7.4s, v13.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V5.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V5.S4, V5.S4
	WORD	$0x4fab8828 // mul v8.4s, v1.4s, v11.s[3]
	WORD	$0x2fada829 // umull v9.2d, v1.2s, v13.s[3]
	WORD	$0x6fada82a // umull2 v10.2d, v1.4s, v13.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V1.S4
	VADD	V17.S4, V1.S4, V1.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4f8c8068 // mul v8.4s, v3.4s, v12.s[0]
	WORD	$0x2f8ea069 // umull v9.2d, v3.2s, v14.s[0]
	WORD	$0x6f8ea06a // umull2 v10.2d, v3.4s, v14.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V2.S4, V3.S4
	VADD	V17.S4, V3.S4, V3.S4
	VADD	V8.S4, V2.S4, V2.S4
	WORD	$0x4fac80a8 // mul v8.4s, v5.4s, v12.s[1]
	WORD	$0x2faea0a9 // umull v9.2d, v5.2s, v14.s[1]
	WORD	$0x6faea0aa // umull2 v10.2d, v5.4s, v14.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V4.S4, V5.S4
	VADD	V17.S4, V5.S4, V5.S4
	VADD	V8.S4, V4.S4, V4.S4
	WORD	$0x4f8c88e8 // mul v8.4s, v7.4s, v12.s[2]
	WORD	$0x2f8ea8e9 // umull v9.2d, v7.2s, v14.s[2]
	WORD	$0x6f8ea8ea // umull2 v10.2d, v7.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V6.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V6.S4, V6.S4
	VST1	[V7.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V6.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V5.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V4.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V3.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V2.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V1.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V0.S4], (R2)
	ADD	$16, R2, R2
	SUBS	$1, R3, R3
	BNE	outer
// Pass 2: layers 16, 8 and 4 on blocks of eight vectors, then 2 and 1 inside the
// vectors, transposed four at a time, the final reduction below q, and back.
	MOVD	R0, R2
	MOVD	$dsaZetas<>+256(SB), R5
	MOVD	$dsaShoups<>+256(SB), R6
	MOVD	$dsaZetas<>+512(SB), R8
	MOVD	$dsaShoups<>+512(SB), R9
	MOVD	$8, R3
inner:
	ADD	$64, R2, R7
	VLD1	(R2), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1	(R7), [V4.S4, V5.S4, V6.S4, V7.S4]
	VLD1.P	32(R1), [V11.S4, V12.S4]
	VLD1.P	32(R1), [V13.S4, V14.S4]
	WORD	$0x4f8b8088 // mul v8.4s, v4.4s, v11.s[0]
	WORD	$0x2f8da089 // umull v9.2d, v4.2s, v13.s[0]
	WORD	$0x6f8da08a // umull2 v10.2d, v4.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V4.S4
	VADD	V17.S4, V4.S4, V4.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4f8b80a8 // mul v8.4s, v5.4s, v11.s[0]
	WORD	$0x2f8da0a9 // umull v9.2d, v5.2s, v13.s[0]
	WORD	$0x6f8da0aa // umull2 v10.2d, v5.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V1.S4, V5.S4
	VADD	V17.S4, V5.S4, V5.S4
	VADD	V8.S4, V1.S4, V1.S4
	WORD	$0x4f8b80c8 // mul v8.4s, v6.4s, v11.s[0]
	WORD	$0x2f8da0c9 // umull v9.2d, v6.2s, v13.s[0]
	WORD	$0x6f8da0ca // umull2 v10.2d, v6.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V2.S4, V6.S4
	VADD	V17.S4, V6.S4, V6.S4
	VADD	V8.S4, V2.S4, V2.S4
	WORD	$0x4f8b80e8 // mul v8.4s, v7.4s, v11.s[0]
	WORD	$0x2f8da0e9 // umull v9.2d, v7.2s, v13.s[0]
	WORD	$0x6f8da0ea // umull2 v10.2d, v7.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V3.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V3.S4, V3.S4
	WORD	$0x4fab8048 // mul v8.4s, v2.4s, v11.s[1]
	WORD	$0x2fada049 // umull v9.2d, v2.2s, v13.s[1]
	WORD	$0x6fada04a // umull2 v10.2d, v2.4s, v13.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V2.S4
	VADD	V17.S4, V2.S4, V2.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4fab8068 // mul v8.4s, v3.4s, v11.s[1]
	WORD	$0x2fada069 // umull v9.2d, v3.2s, v13.s[1]
	WORD	$0x6fada06a // umull2 v10.2d, v3.4s, v13.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V1.S4, V3.S4
	VADD	V17.S4, V3.S4, V3.S4
	VADD	V8.S4, V1.S4, V1.S4
	WORD	$0x4f8b88c8 // mul v8.4s, v6.4s, v11.s[2]
	WORD	$0x2f8da8c9 // umull v9.2d, v6.2s, v13.s[2]
	WORD	$0x6f8da8ca // umull2 v10.2d, v6.4s, v13.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V4.S4, V6.S4
	VADD	V17.S4, V6.S4, V6.S4
	VADD	V8.S4, V4.S4, V4.S4
	WORD	$0x4f8b88e8 // mul v8.4s, v7.4s, v11.s[2]
	WORD	$0x2f8da8e9 // umull v9.2d, v7.2s, v13.s[2]
	WORD	$0x6f8da8ea // umull2 v10.2d, v7.4s, v13.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V5.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V5.S4, V5.S4
	WORD	$0x4fab8828 // mul v8.4s, v1.4s, v11.s[3]
	WORD	$0x2fada829 // umull v9.2d, v1.2s, v13.s[3]
	WORD	$0x6fada82a // umull2 v10.2d, v1.4s, v13.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V1.S4
	VADD	V17.S4, V1.S4, V1.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4f8c8068 // mul v8.4s, v3.4s, v12.s[0]
	WORD	$0x2f8ea069 // umull v9.2d, v3.2s, v14.s[0]
	WORD	$0x6f8ea06a // umull2 v10.2d, v3.4s, v14.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V2.S4, V3.S4
	VADD	V17.S4, V3.S4, V3.S4
	VADD	V8.S4, V2.S4, V2.S4
	WORD	$0x4fac80a8 // mul v8.4s, v5.4s, v12.s[1]
	WORD	$0x2faea0a9 // umull v9.2d, v5.2s, v14.s[1]
	WORD	$0x6faea0aa // umull2 v10.2d, v5.4s, v14.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V4.S4, V5.S4
	VADD	V17.S4, V5.S4, V5.S4
	VADD	V8.S4, V4.S4, V4.S4
	WORD	$0x4f8c88e8 // mul v8.4s, v7.4s, v12.s[2]
	WORD	$0x2f8ea8e9 // umull v9.2d, v7.2s, v14.s[2]
	WORD	$0x6f8ea8ea // umull2 v10.2d, v7.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V6.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V6.S4, V6.S4
	VTRN1	V1.S4, V0.S4, V18.S4
	VTRN2	V1.S4, V0.S4, V19.S4
	VTRN1	V3.S4, V2.S4, V20.S4
	VTRN2	V3.S4, V2.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V0.D2
	VTRN2	V20.D2, V18.D2, V2.D2
	VTRN1	V21.D2, V19.D2, V1.D2
	VTRN2	V21.D2, V19.D2, V3.D2
	VLD1.P	16(R5), [V22.S4]
	VLD1.P	16(R6), [V23.S4]
	VLD1.P	32(R8), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V24.S4
	VUZP2	V29.S4, V28.S4, V25.S4
	VLD1.P	32(R9), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V26.S4
	VUZP2	V29.S4, V28.S4, V27.S4
	WORD	$0x4eb69c48 // mul v8.4s, v2.4s, v22.4s
	WORD	$0x2eb7c049 // umull v9.2d, v2.2s, v23.2s
	WORD	$0x6eb7c04a // umull2 v10.2d, v2.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V2.S4
	VADD	V17.S4, V2.S4, V2.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4eb69c68 // mul v8.4s, v3.4s, v22.4s
	WORD	$0x2eb7c069 // umull v9.2d, v3.2s, v23.2s
	WORD	$0x6eb7c06a // umull2 v10.2d, v3.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V1.S4, V3.S4
	VADD	V17.S4, V3.S4, V3.S4
	VADD	V8.S4, V1.S4, V1.S4
	WORD	$0x4eb89c28 // mul v8.4s, v1.4s, v24.4s
	WORD	$0x2ebac029 // umull v9.2d, v1.2s, v26.2s
	WORD	$0x6ebac02a // umull2 v10.2d, v1.4s, v26.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V0.S4, V1.S4
	VADD	V17.S4, V1.S4, V1.S4
	VADD	V8.S4, V0.S4, V0.S4
	WORD	$0x4eb99c68 // mul v8.4s, v3.4s, v25.4s
	WORD	$0x2ebbc069 // umull v9.2d, v3.2s, v27.2s
	WORD	$0x6ebbc06a // umull2 v10.2d, v3.4s, v27.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V2.S4, V3.S4
	VADD	V17.S4, V3.S4, V3.S4
	VADD	V8.S4, V2.S4, V2.S4
	VUSHR	$23, V0.S4, V9.S4
	WORD	$0x6f904120 // mls v0.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V0.S4, V8.S4
	VUMIN	V8.S4, V0.S4, V0.S4
	VUSHR	$23, V1.S4, V9.S4
	WORD	$0x6f904121 // mls v1.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V1.S4, V8.S4
	VUMIN	V8.S4, V1.S4, V1.S4
	VUSHR	$23, V2.S4, V9.S4
	WORD	$0x6f904122 // mls v2.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V2.S4, V8.S4
	VUMIN	V8.S4, V2.S4, V2.S4
	VUSHR	$23, V3.S4, V9.S4
	WORD	$0x6f904123 // mls v3.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V3.S4, V8.S4
	VUMIN	V8.S4, V3.S4, V3.S4
	VTRN1	V1.S4, V0.S4, V18.S4
	VTRN2	V1.S4, V0.S4, V19.S4
	VTRN1	V3.S4, V2.S4, V20.S4
	VTRN2	V3.S4, V2.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V0.D2
	VTRN2	V20.D2, V18.D2, V2.D2
	VTRN1	V21.D2, V19.D2, V1.D2
	VTRN2	V21.D2, V19.D2, V3.D2
	VTRN1	V5.S4, V4.S4, V18.S4
	VTRN2	V5.S4, V4.S4, V19.S4
	VTRN1	V7.S4, V6.S4, V20.S4
	VTRN2	V7.S4, V6.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V4.D2
	VTRN2	V20.D2, V18.D2, V6.D2
	VTRN1	V21.D2, V19.D2, V5.D2
	VTRN2	V21.D2, V19.D2, V7.D2
	VLD1.P	16(R5), [V22.S4]
	VLD1.P	16(R6), [V23.S4]
	VLD1.P	32(R8), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V24.S4
	VUZP2	V29.S4, V28.S4, V25.S4
	VLD1.P	32(R9), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V26.S4
	VUZP2	V29.S4, V28.S4, V27.S4
	WORD	$0x4eb69cc8 // mul v8.4s, v6.4s, v22.4s
	WORD	$0x2eb7c0c9 // umull v9.2d, v6.2s, v23.2s
	WORD	$0x6eb7c0ca // umull2 v10.2d, v6.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V4.S4, V6.S4
	VADD	V17.S4, V6.S4, V6.S4
	VADD	V8.S4, V4.S4, V4.S4
	WORD	$0x4eb69ce8 // mul v8.4s, v7.4s, v22.4s
	WORD	$0x2eb7c0e9 // umull v9.2d, v7.2s, v23.2s
	WORD	$0x6eb7c0ea // umull2 v10.2d, v7.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V5.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V5.S4, V5.S4
	WORD	$0x4eb89ca8 // mul v8.4s, v5.4s, v24.4s
	WORD	$0x2ebac0a9 // umull v9.2d, v5.2s, v26.2s
	WORD	$0x6ebac0aa // umull2 v10.2d, v5.4s, v26.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V4.S4, V5.S4
	VADD	V17.S4, V5.S4, V5.S4
	VADD	V8.S4, V4.S4, V4.S4
	WORD	$0x4eb99ce8 // mul v8.4s, v7.4s, v25.4s
	WORD	$0x2ebbc0e9 // umull v9.2d, v7.2s, v27.2s
	WORD	$0x6ebbc0ea // umull2 v10.2d, v7.4s, v27.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VSUB	V8.S4, V6.S4, V7.S4
	VADD	V17.S4, V7.S4, V7.S4
	VADD	V8.S4, V6.S4, V6.S4
	VUSHR	$23, V4.S4, V9.S4
	WORD	$0x6f904124 // mls v4.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V4.S4, V8.S4
	VUMIN	V8.S4, V4.S4, V4.S4
	VUSHR	$23, V5.S4, V9.S4
	WORD	$0x6f904125 // mls v5.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V5.S4, V8.S4
	VUMIN	V8.S4, V5.S4, V5.S4
	VUSHR	$23, V6.S4, V9.S4
	WORD	$0x6f904126 // mls v6.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V6.S4, V8.S4
	VUMIN	V8.S4, V6.S4, V6.S4
	VUSHR	$23, V7.S4, V9.S4
	WORD	$0x6f904127 // mls v7.4s, v9.4s, v16.s[0]
	VSUB	V16.S4, V7.S4, V8.S4
	VUMIN	V8.S4, V7.S4, V7.S4
	VTRN1	V5.S4, V4.S4, V18.S4
	VTRN2	V5.S4, V4.S4, V19.S4
	VTRN1	V7.S4, V6.S4, V20.S4
	VTRN2	V7.S4, V6.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V4.D2
	VTRN2	V20.D2, V18.D2, V6.D2
	VTRN1	V21.D2, V19.D2, V5.D2
	VTRN2	V21.D2, V19.D2, V7.D2
	VST1	[V0.S4, V1.S4, V2.S4, V3.S4], (R2)
	VST1	[V4.S4, V5.S4, V6.S4, V7.S4], (R7)
	ADD	$128, R2, R2
	SUBS	$1, R3, R3
	BNE	inner
	RET

// The inverse NTT of ML-DSA (FIPS 204, Algorithm 42) of canonical coefficients, left canonical.
// func dsaInverseNTTARM(w *[256]uint32)
TEXT ·dsaInverseNTTARM(SB), NOSPLIT, $0-8
	MOVD	w+0(FP), R0
	MOVD	$dsaConstants<>(SB), R4
	VLD1	(R4), [V16.S4, V17.S4]
	MOVD	$dsaInverseZetas<>(SB), R1
	MOVD	R0, R2
	MOVD	$dsaZetasReversed<>+512(SB), R5
	MOVD	$dsaShoupsReversed<>+512(SB), R6
	MOVD	$dsaZetasReversed<>(SB), R8
	MOVD	$dsaShoupsReversed<>(SB), R9
	MOVD	$8, R3
inner:
	ADD	$64, R2, R7
	VLD1	(R2), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1	(R7), [V4.S4, V5.S4, V6.S4, V7.S4]
	VTRN1	V1.S4, V0.S4, V18.S4
	VTRN2	V1.S4, V0.S4, V19.S4
	VTRN1	V3.S4, V2.S4, V20.S4
	VTRN2	V3.S4, V2.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V0.D2
	VTRN2	V20.D2, V18.D2, V2.D2
	VTRN1	V21.D2, V19.D2, V1.D2
	VTRN2	V21.D2, V19.D2, V3.D2
	VLD1.P	16(R5), [V22.S4]
	VLD1.P	16(R6), [V23.S4]
	VLD1.P	32(R8), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V24.S4
	VUZP2	V29.S4, V28.S4, V25.S4
	VLD1.P	32(R9), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V26.S4
	VUZP2	V29.S4, V28.S4, V27.S4
	MOVD	$dsaConstants<>+32(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V1.S4, V8.S4
	VADD	V1.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V1.S4
	WORD	$0x4eb89c28 // mul v8.4s, v1.4s, v24.4s
	WORD	$0x2ebac029 // umull v9.2d, v1.2s, v26.2s
	WORD	$0x6ebac02a // umull2 v10.2d, v1.4s, v26.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V1.B16
	VSUB	V2.S4, V3.S4, V8.S4
	VADD	V3.S4, V2.S4, V2.S4
	VADD	V30.S4, V8.S4, V3.S4
	WORD	$0x4eb99c68 // mul v8.4s, v3.4s, v25.4s
	WORD	$0x2ebbc069 // umull v9.2d, v3.2s, v27.2s
	WORD	$0x6ebbc06a // umull2 v10.2d, v3.4s, v27.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	MOVD	$dsaConstants<>+48(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V2.S4, V8.S4
	VADD	V2.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V2.S4
	WORD	$0x4eb69c48 // mul v8.4s, v2.4s, v22.4s
	WORD	$0x2eb7c049 // umull v9.2d, v2.2s, v23.2s
	WORD	$0x6eb7c04a // umull2 v10.2d, v2.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V2.B16
	VSUB	V1.S4, V3.S4, V8.S4
	VADD	V3.S4, V1.S4, V1.S4
	VADD	V30.S4, V8.S4, V3.S4
	WORD	$0x4eb69c68 // mul v8.4s, v3.4s, v22.4s
	WORD	$0x2eb7c069 // umull v9.2d, v3.2s, v23.2s
	WORD	$0x6eb7c06a // umull2 v10.2d, v3.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	VTRN1	V1.S4, V0.S4, V18.S4
	VTRN2	V1.S4, V0.S4, V19.S4
	VTRN1	V3.S4, V2.S4, V20.S4
	VTRN2	V3.S4, V2.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V0.D2
	VTRN2	V20.D2, V18.D2, V2.D2
	VTRN1	V21.D2, V19.D2, V1.D2
	VTRN2	V21.D2, V19.D2, V3.D2
	VTRN1	V5.S4, V4.S4, V18.S4
	VTRN2	V5.S4, V4.S4, V19.S4
	VTRN1	V7.S4, V6.S4, V20.S4
	VTRN2	V7.S4, V6.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V4.D2
	VTRN2	V20.D2, V18.D2, V6.D2
	VTRN1	V21.D2, V19.D2, V5.D2
	VTRN2	V21.D2, V19.D2, V7.D2
	VLD1.P	16(R5), [V22.S4]
	VLD1.P	16(R6), [V23.S4]
	VLD1.P	32(R8), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V24.S4
	VUZP2	V29.S4, V28.S4, V25.S4
	VLD1.P	32(R9), [V28.S4, V29.S4]
	VUZP1	V29.S4, V28.S4, V26.S4
	VUZP2	V29.S4, V28.S4, V27.S4
	MOVD	$dsaConstants<>+32(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V4.S4, V5.S4, V8.S4
	VADD	V5.S4, V4.S4, V4.S4
	VADD	V30.S4, V8.S4, V5.S4
	WORD	$0x4eb89ca8 // mul v8.4s, v5.4s, v24.4s
	WORD	$0x2ebac0a9 // umull v9.2d, v5.2s, v26.2s
	WORD	$0x6ebac0aa // umull2 v10.2d, v5.4s, v26.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V5.B16
	VSUB	V6.S4, V7.S4, V8.S4
	VADD	V7.S4, V6.S4, V6.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4eb99ce8 // mul v8.4s, v7.4s, v25.4s
	WORD	$0x2ebbc0e9 // umull v9.2d, v7.2s, v27.2s
	WORD	$0x6ebbc0ea // umull2 v10.2d, v7.4s, v27.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	MOVD	$dsaConstants<>+48(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V4.S4, V6.S4, V8.S4
	VADD	V6.S4, V4.S4, V4.S4
	VADD	V30.S4, V8.S4, V6.S4
	WORD	$0x4eb69cc8 // mul v8.4s, v6.4s, v22.4s
	WORD	$0x2eb7c0c9 // umull v9.2d, v6.2s, v23.2s
	WORD	$0x6eb7c0ca // umull2 v10.2d, v6.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V6.B16
	VSUB	V5.S4, V7.S4, V8.S4
	VADD	V7.S4, V5.S4, V5.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4eb69ce8 // mul v8.4s, v7.4s, v22.4s
	WORD	$0x2eb7c0e9 // umull v9.2d, v7.2s, v23.2s
	WORD	$0x6eb7c0ea // umull2 v10.2d, v7.4s, v23.4s
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	VTRN1	V5.S4, V4.S4, V18.S4
	VTRN2	V5.S4, V4.S4, V19.S4
	VTRN1	V7.S4, V6.S4, V20.S4
	VTRN2	V7.S4, V6.S4, V21.S4
	VTRN1	V20.D2, V18.D2, V4.D2
	VTRN2	V20.D2, V18.D2, V6.D2
	VTRN1	V21.D2, V19.D2, V5.D2
	VTRN2	V21.D2, V19.D2, V7.D2
	VLD1.P	32(R1), [V11.S4, V12.S4]
	VLD1.P	32(R1), [V13.S4, V14.S4]
	MOVD	$dsaConstants<>+64(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V1.S4, V8.S4
	VADD	V1.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V1.S4
	WORD	$0x4f8b8028 // mul v8.4s, v1.4s, v11.s[0]
	WORD	$0x2f8da029 // umull v9.2d, v1.2s, v13.s[0]
	WORD	$0x6f8da02a // umull2 v10.2d, v1.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V1.B16
	VSUB	V2.S4, V3.S4, V8.S4
	VADD	V3.S4, V2.S4, V2.S4
	VADD	V30.S4, V8.S4, V3.S4
	WORD	$0x4fab8068 // mul v8.4s, v3.4s, v11.s[1]
	WORD	$0x2fada069 // umull v9.2d, v3.2s, v13.s[1]
	WORD	$0x6fada06a // umull2 v10.2d, v3.4s, v13.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	VSUB	V4.S4, V5.S4, V8.S4
	VADD	V5.S4, V4.S4, V4.S4
	VADD	V30.S4, V8.S4, V5.S4
	WORD	$0x4f8b88a8 // mul v8.4s, v5.4s, v11.s[2]
	WORD	$0x2f8da8a9 // umull v9.2d, v5.2s, v13.s[2]
	WORD	$0x6f8da8aa // umull2 v10.2d, v5.4s, v13.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V5.B16
	VSUB	V6.S4, V7.S4, V8.S4
	VADD	V7.S4, V6.S4, V6.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4fab88e8 // mul v8.4s, v7.4s, v11.s[3]
	WORD	$0x2fada8e9 // umull v9.2d, v7.2s, v13.s[3]
	WORD	$0x6fada8ea // umull2 v10.2d, v7.4s, v13.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	MOVD	$dsaConstants<>+80(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V2.S4, V8.S4
	VADD	V2.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V2.S4
	WORD	$0x4f8c8048 // mul v8.4s, v2.4s, v12.s[0]
	WORD	$0x2f8ea049 // umull v9.2d, v2.2s, v14.s[0]
	WORD	$0x6f8ea04a // umull2 v10.2d, v2.4s, v14.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V2.B16
	VSUB	V1.S4, V3.S4, V8.S4
	VADD	V3.S4, V1.S4, V1.S4
	VADD	V30.S4, V8.S4, V3.S4
	WORD	$0x4f8c8068 // mul v8.4s, v3.4s, v12.s[0]
	WORD	$0x2f8ea069 // umull v9.2d, v3.2s, v14.s[0]
	WORD	$0x6f8ea06a // umull2 v10.2d, v3.4s, v14.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	VSUB	V4.S4, V6.S4, V8.S4
	VADD	V6.S4, V4.S4, V4.S4
	VADD	V30.S4, V8.S4, V6.S4
	WORD	$0x4fac80c8 // mul v8.4s, v6.4s, v12.s[1]
	WORD	$0x2faea0c9 // umull v9.2d, v6.2s, v14.s[1]
	WORD	$0x6faea0ca // umull2 v10.2d, v6.4s, v14.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V6.B16
	VSUB	V5.S4, V7.S4, V8.S4
	VADD	V7.S4, V5.S4, V5.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4fac80e8 // mul v8.4s, v7.4s, v12.s[1]
	WORD	$0x2faea0e9 // umull v9.2d, v7.2s, v14.s[1]
	WORD	$0x6faea0ea // umull2 v10.2d, v7.4s, v14.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	MOVD	$dsaConstants<>+96(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V4.S4, V8.S4
	VADD	V4.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V4.S4
	WORD	$0x4f8c8888 // mul v8.4s, v4.4s, v12.s[2]
	WORD	$0x2f8ea889 // umull v9.2d, v4.2s, v14.s[2]
	WORD	$0x6f8ea88a // umull2 v10.2d, v4.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V4.B16
	VSUB	V1.S4, V5.S4, V8.S4
	VADD	V5.S4, V1.S4, V1.S4
	VADD	V30.S4, V8.S4, V5.S4
	WORD	$0x4f8c88a8 // mul v8.4s, v5.4s, v12.s[2]
	WORD	$0x2f8ea8a9 // umull v9.2d, v5.2s, v14.s[2]
	WORD	$0x6f8ea8aa // umull2 v10.2d, v5.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V5.B16
	VSUB	V2.S4, V6.S4, V8.S4
	VADD	V6.S4, V2.S4, V2.S4
	VADD	V30.S4, V8.S4, V6.S4
	WORD	$0x4f8c88c8 // mul v8.4s, v6.4s, v12.s[2]
	WORD	$0x2f8ea8c9 // umull v9.2d, v6.2s, v14.s[2]
	WORD	$0x6f8ea8ca // umull2 v10.2d, v6.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V6.B16
	VSUB	V3.S4, V7.S4, V8.S4
	VADD	V7.S4, V3.S4, V3.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4f8c88e8 // mul v8.4s, v7.4s, v12.s[2]
	WORD	$0x2f8ea8e9 // umull v9.2d, v7.2s, v14.s[2]
	WORD	$0x6f8ea8ea // umull2 v10.2d, v7.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	VST1	[V0.S4, V1.S4, V2.S4, V3.S4], (R2)
	VST1	[V4.S4, V5.S4, V6.S4, V7.S4], (R7)
	ADD	$128, R2, R2
	SUBS	$1, R3, R3
	BNE	inner
// Pass 2: layers 32 and 64, then 128 with the factor 1/256 folded into its zetas.
	VLD1.P	32(R1), [V11.S4, V12.S4]
	VLD1.P	32(R1), [V13.S4, V14.S4]
	MOVD	R0, R2
	MOVD	$8, R3
outer:
	VLD1	(R2), [V0.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V1.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V2.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V3.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V4.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V5.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V6.S4]
	ADD	$128, R2, R2
	VLD1	(R2), [V7.S4]
	MOVD	$dsaConstants<>+112(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V1.S4, V8.S4
	VADD	V1.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V1.S4
	WORD	$0x4f8b8028 // mul v8.4s, v1.4s, v11.s[0]
	WORD	$0x2f8da029 // umull v9.2d, v1.2s, v13.s[0]
	WORD	$0x6f8da02a // umull2 v10.2d, v1.4s, v13.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V1.B16
	VSUB	V2.S4, V3.S4, V8.S4
	VADD	V3.S4, V2.S4, V2.S4
	VADD	V30.S4, V8.S4, V3.S4
	WORD	$0x4fab8068 // mul v8.4s, v3.4s, v11.s[1]
	WORD	$0x2fada069 // umull v9.2d, v3.2s, v13.s[1]
	WORD	$0x6fada06a // umull2 v10.2d, v3.4s, v13.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	VSUB	V4.S4, V5.S4, V8.S4
	VADD	V5.S4, V4.S4, V4.S4
	VADD	V30.S4, V8.S4, V5.S4
	WORD	$0x4f8b88a8 // mul v8.4s, v5.4s, v11.s[2]
	WORD	$0x2f8da8a9 // umull v9.2d, v5.2s, v13.s[2]
	WORD	$0x6f8da8aa // umull2 v10.2d, v5.4s, v13.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V5.B16
	VSUB	V6.S4, V7.S4, V8.S4
	VADD	V7.S4, V6.S4, V6.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4fab88e8 // mul v8.4s, v7.4s, v11.s[3]
	WORD	$0x2fada8e9 // umull v9.2d, v7.2s, v13.s[3]
	WORD	$0x6fada8ea // umull2 v10.2d, v7.4s, v13.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	MOVD	$dsaConstants<>+128(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V2.S4, V8.S4
	VADD	V2.S4, V0.S4, V0.S4
	VADD	V30.S4, V8.S4, V2.S4
	WORD	$0x4f8c8048 // mul v8.4s, v2.4s, v12.s[0]
	WORD	$0x2f8ea049 // umull v9.2d, v2.2s, v14.s[0]
	WORD	$0x6f8ea04a // umull2 v10.2d, v2.4s, v14.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V2.B16
	VSUB	V1.S4, V3.S4, V8.S4
	VADD	V3.S4, V1.S4, V1.S4
	VADD	V30.S4, V8.S4, V3.S4
	WORD	$0x4f8c8068 // mul v8.4s, v3.4s, v12.s[0]
	WORD	$0x2f8ea069 // umull v9.2d, v3.2s, v14.s[0]
	WORD	$0x6f8ea06a // umull2 v10.2d, v3.4s, v14.s[0]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	VSUB	V4.S4, V6.S4, V8.S4
	VADD	V6.S4, V4.S4, V4.S4
	VADD	V30.S4, V8.S4, V6.S4
	WORD	$0x4fac80c8 // mul v8.4s, v6.4s, v12.s[1]
	WORD	$0x2faea0c9 // umull v9.2d, v6.2s, v14.s[1]
	WORD	$0x6faea0ca // umull2 v10.2d, v6.4s, v14.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V6.B16
	VSUB	V5.S4, V7.S4, V8.S4
	VADD	V7.S4, V5.S4, V5.S4
	VADD	V30.S4, V8.S4, V7.S4
	WORD	$0x4fac80e8 // mul v8.4s, v7.4s, v12.s[1]
	WORD	$0x2faea0e9 // umull v9.2d, v7.2s, v14.s[1]
	WORD	$0x6faea0ea // umull2 v10.2d, v7.4s, v14.s[1]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	MOVD	$dsaConstants<>+144(SB), R4
	VLD1	(R4), [V30.S4]
	VSUB	V0.S4, V4.S4, V31.S4
	VADD	V4.S4, V0.S4, V0.S4
	VADD	V30.S4, V31.S4, V4.S4
	WORD	$0x4fac8808 // mul v8.4s, v0.4s, v12.s[3]
	WORD	$0x2faea809 // umull v9.2d, v0.2s, v14.s[3]
	WORD	$0x6faea80a // umull2 v10.2d, v0.4s, v14.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V0.B16
	VSUB	V16.S4, V0.S4, V8.S4
	VUMIN	V8.S4, V0.S4, V0.S4
	WORD	$0x4f8c8888 // mul v8.4s, v4.4s, v12.s[2]
	WORD	$0x2f8ea889 // umull v9.2d, v4.2s, v14.s[2]
	WORD	$0x6f8ea88a // umull2 v10.2d, v4.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V4.B16
	VSUB	V16.S4, V4.S4, V8.S4
	VUMIN	V8.S4, V4.S4, V4.S4
	VSUB	V1.S4, V5.S4, V31.S4
	VADD	V5.S4, V1.S4, V1.S4
	VADD	V30.S4, V31.S4, V5.S4
	WORD	$0x4fac8828 // mul v8.4s, v1.4s, v12.s[3]
	WORD	$0x2faea829 // umull v9.2d, v1.2s, v14.s[3]
	WORD	$0x6faea82a // umull2 v10.2d, v1.4s, v14.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V1.B16
	VSUB	V16.S4, V1.S4, V8.S4
	VUMIN	V8.S4, V1.S4, V1.S4
	WORD	$0x4f8c88a8 // mul v8.4s, v5.4s, v12.s[2]
	WORD	$0x2f8ea8a9 // umull v9.2d, v5.2s, v14.s[2]
	WORD	$0x6f8ea8aa // umull2 v10.2d, v5.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V5.B16
	VSUB	V16.S4, V5.S4, V8.S4
	VUMIN	V8.S4, V5.S4, V5.S4
	VSUB	V2.S4, V6.S4, V31.S4
	VADD	V6.S4, V2.S4, V2.S4
	VADD	V30.S4, V31.S4, V6.S4
	WORD	$0x4fac8848 // mul v8.4s, v2.4s, v12.s[3]
	WORD	$0x2faea849 // umull v9.2d, v2.2s, v14.s[3]
	WORD	$0x6faea84a // umull2 v10.2d, v2.4s, v14.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V2.B16
	VSUB	V16.S4, V2.S4, V8.S4
	VUMIN	V8.S4, V2.S4, V2.S4
	WORD	$0x4f8c88c8 // mul v8.4s, v6.4s, v12.s[2]
	WORD	$0x2f8ea8c9 // umull v9.2d, v6.2s, v14.s[2]
	WORD	$0x6f8ea8ca // umull2 v10.2d, v6.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V6.B16
	VSUB	V16.S4, V6.S4, V8.S4
	VUMIN	V8.S4, V6.S4, V6.S4
	VSUB	V3.S4, V7.S4, V31.S4
	VADD	V7.S4, V3.S4, V3.S4
	VADD	V30.S4, V31.S4, V7.S4
	WORD	$0x4fac8868 // mul v8.4s, v3.4s, v12.s[3]
	WORD	$0x2faea869 // umull v9.2d, v3.2s, v14.s[3]
	WORD	$0x6faea86a // umull2 v10.2d, v3.4s, v14.s[3]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V3.B16
	VSUB	V16.S4, V3.S4, V8.S4
	VUMIN	V8.S4, V3.S4, V3.S4
	WORD	$0x4f8c88e8 // mul v8.4s, v7.4s, v12.s[2]
	WORD	$0x2f8ea8e9 // umull v9.2d, v7.2s, v14.s[2]
	WORD	$0x6f8ea8ea // umull2 v10.2d, v7.4s, v14.s[2]
	VUZP2	V10.S4, V9.S4, V9.S4
	WORD	$0x6f904128 // mls v8.4s, v9.4s, v16.s[0]
	VMOV	V8.B16, V7.B16
	VSUB	V16.S4, V7.S4, V8.S4
	VUMIN	V8.S4, V7.S4, V7.S4
	VST1	[V7.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V6.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V5.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V4.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V3.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V2.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V1.S4], (R2)
	SUB	$128, R2, R2
	VST1	[V0.S4], (R2)
	ADD	$16, R2, R2
	SUBS	$1, R3, R3
	BNE	outer
	RET

DATA dsaZetas<>+0(SB)/4, $0x0000000001
DATA dsaZetas<>+4(SB)/4, $0x0000495e02
DATA dsaZetas<>+8(SB)/4, $0x0000397567
DATA dsaZetas<>+12(SB)/4, $0x0000396569
DATA dsaZetas<>+16(SB)/4, $0x00004f062b
DATA dsaZetas<>+20(SB)/4, $0x000053df73
DATA dsaZetas<>+24(SB)/4, $0x00004fe033
DATA dsaZetas<>+28(SB)/4, $0x00004f066b
DATA dsaZetas<>+32(SB)/4, $0x000076b1ae
DATA dsaZetas<>+36(SB)/4, $0x0000360dd5
DATA dsaZetas<>+40(SB)/4, $0x000028edb0
DATA dsaZetas<>+44(SB)/4, $0x0000207fe4
DATA dsaZetas<>+48(SB)/4, $0x0000397283
DATA dsaZetas<>+52(SB)/4, $0x000070894a
DATA dsaZetas<>+56(SB)/4, $0x0000088192
DATA dsaZetas<>+60(SB)/4, $0x00006d3dc8
DATA dsaZetas<>+64(SB)/4, $0x00004c7294
DATA dsaZetas<>+68(SB)/4, $0x000041e0b4
DATA dsaZetas<>+72(SB)/4, $0x000028a3d2
DATA dsaZetas<>+76(SB)/4, $0x000066528a
DATA dsaZetas<>+80(SB)/4, $0x00004a18a7
DATA dsaZetas<>+84(SB)/4, $0x0000794034
DATA dsaZetas<>+88(SB)/4, $0x00000a52ee
DATA dsaZetas<>+92(SB)/4, $0x00006b7d81
DATA dsaZetas<>+96(SB)/4, $0x00004e9f1d
DATA dsaZetas<>+100(SB)/4, $0x00001a2877
DATA dsaZetas<>+104(SB)/4, $0x00002571df
DATA dsaZetas<>+108(SB)/4, $0x00001649ee
DATA dsaZetas<>+112(SB)/4, $0x00007611bd
DATA dsaZetas<>+116(SB)/4, $0x0000492bb7
DATA dsaZetas<>+120(SB)/4, $0x00002af697
DATA dsaZetas<>+124(SB)/4, $0x000022d8d5
DATA dsaZetas<>+128(SB)/4, $0x000036f72a
DATA dsaZetas<>+132(SB)/4, $0x000030911e
DATA dsaZetas<>+136(SB)/4, $0x000029d13f
DATA dsaZetas<>+140(SB)/4, $0x0000492673
DATA dsaZetas<>+144(SB)/4, $0x000050685f
DATA dsaZetas<>+148(SB)/4, $0x00002010a2
DATA dsaZetas<>+152(SB)/4, $0x00003887f7
DATA dsaZetas<>+156(SB)/4, $0x000011b2c3
DATA dsaZetas<>+160(SB)/4, $0x00000603a4
DATA dsaZetas<>+164(SB)/4, $0x00000e2bed
DATA dsaZetas<>+168(SB)/4, $0x000010b72c
DATA dsaZetas<>+172(SB)/4, $0x00004a5f35
DATA dsaZetas<>+176(SB)/4, $0x00001f9d15
DATA dsaZetas<>+180(SB)/4, $0x0000428cd4
DATA dsaZetas<>+184(SB)/4, $0x00003177f4
DATA dsaZetas<>+188(SB)/4, $0x000020e612
DATA dsaZetas<>+192(SB)/4, $0x0000341c1d
DATA dsaZetas<>+196(SB)/4, $0x00001ad873
DATA dsaZetas<>+200(SB)/4, $0x0000736681
DATA dsaZetas<>+204(SB)/4, $0x000049553f
DATA dsaZetas<>+208(SB)/4, $0x00003952f6
DATA dsaZetas<>+212(SB)/4, $0x000062564a
DATA dsaZetas<>+216(SB)/4, $0x000065ad05
DATA dsaZetas<>+220(SB)/4, $0x0000439a1c
DATA dsaZetas<>+224(SB)/4, $0x000053aa5f
DATA dsaZetas<>+228(SB)/4, $0x000030b622
DATA dsaZetas<>+232(SB)/4, $0x0000087f38
DATA dsaZetas<>+236(SB)/4, $0x00003b0e6d
DATA dsaZetas<>+240(SB)/4, $0x00002c83da
DATA dsaZetas<>+244(SB)/4, $0x00001c496e
DATA dsaZetas<>+248(SB)/4, $0x0000330e2b
DATA dsaZetas<>+252(SB)/4, $0x00001c5b70
DATA dsaZetas<>+256(SB)/4, $0x00002ee3f1
DATA dsaZetas<>+260(SB)/4, $0x0000137eb9
DATA dsaZetas<>+264(SB)/4, $0x000057a930
DATA dsaZetas<>+268(SB)/4, $0x00003ac6ef
DATA dsaZetas<>+272(SB)/4, $0x00003fd54c
DATA dsaZetas<>+276(SB)/4, $0x00004eb2ea
DATA dsaZetas<>+280(SB)/4, $0x0000503ee1
DATA dsaZetas<>+284(SB)/4, $0x00007bb175
DATA dsaZetas<>+288(SB)/4, $0x00002648b4
DATA dsaZetas<>+292(SB)/4, $0x00001ef256
DATA dsaZetas<>+296(SB)/4, $0x00001d90a2
DATA dsaZetas<>+300(SB)/4, $0x000045a6d4
DATA dsaZetas<>+304(SB)/4, $0x00002ae59b
DATA dsaZetas<>+308(SB)/4, $0x000052589c
DATA dsaZetas<>+312(SB)/4, $0x00006ef1f5
DATA dsaZetas<>+316(SB)/4, $0x00003f7288
DATA dsaZetas<>+320(SB)/4, $0x0000175102
DATA dsaZetas<>+324(SB)/4, $0x0000075d59
DATA dsaZetas<>+328(SB)/4, $0x00001187ba
DATA dsaZetas<>+332(SB)/4, $0x000052aca9
DATA dsaZetas<>+336(SB)/4, $0x0000773e9e
DATA dsaZetas<>+340(SB)/4, $0x00000296d8
DATA dsaZetas<>+344(SB)/4, $0x00002592ec
DATA dsaZetas<>+348(SB)/4, $0x00004cff12
DATA dsaZetas<>+352(SB)/4, $0x0000404ce8
DATA dsaZetas<>+356(SB)/4, $0x00004aa582
DATA dsaZetas<>+360(SB)/4, $0x00001e54e6
DATA dsaZetas<>+364(SB)/4, $0x00004f16c1
DATA dsaZetas<>+368(SB)/4, $0x00001a7e79
DATA dsaZetas<>+372(SB)/4, $0x000003978f
DATA dsaZetas<>+376(SB)/4, $0x00004e4817
DATA dsaZetas<>+380(SB)/4, $0x000031b859
DATA dsaZetas<>+384(SB)/4, $0x00005884cc
DATA dsaZetas<>+388(SB)/4, $0x00001b4827
DATA dsaZetas<>+392(SB)/4, $0x00005b63d0
DATA dsaZetas<>+396(SB)/4, $0x00005d787a
DATA dsaZetas<>+400(SB)/4, $0x000035225e
DATA dsaZetas<>+404(SB)/4, $0x0000400c7e
DATA dsaZetas<>+408(SB)/4, $0x00006c09d1
DATA dsaZetas<>+412(SB)/4, $0x00005bd532
DATA dsaZetas<>+416(SB)/4, $0x00006bc4d3
DATA dsaZetas<>+420(SB)/4, $0x0000258ecb
DATA dsaZetas<>+424(SB)/4, $0x00002e534c
DATA dsaZetas<>+428(SB)/4, $0x0000097a6c
DATA dsaZetas<>+432(SB)/4, $0x00003b8820
DATA dsaZetas<>+436(SB)/4, $0x00006d285c
DATA dsaZetas<>+440(SB)/4, $0x00002ca4f8
DATA dsaZetas<>+444(SB)/4, $0x0000337caa
DATA dsaZetas<>+448(SB)/4, $0x000014b2a0
DATA dsaZetas<>+452(SB)/4, $0x0000558536
DATA dsaZetas<>+456(SB)/4, $0x000028f186
DATA dsaZetas<>+460(SB)/4, $0x000055795d
DATA dsaZetas<>+464(SB)/4, $0x00004af670
DATA dsaZetas<>+468(SB)/4, $0x0000234a86
DATA dsaZetas<>+472(SB)/4, $0x000075e826
DATA dsaZetas<>+476(SB)/4, $0x000078de66
DATA dsaZetas<>+480(SB)/4, $0x000005528c
DATA dsaZetas<>+484(SB)/4, $0x00007adf59
DATA dsaZetas<>+488(SB)/4, $0x00000f6e17
DATA dsaZetas<>+492(SB)/4, $0x00005bf3da
DATA dsaZetas<>+496(SB)/4, $0x0000459b7e
DATA dsaZetas<>+500(SB)/4, $0x0000628b34
DATA dsaZetas<>+504(SB)/4, $0x00005dbecb
DATA dsaZetas<>+508(SB)/4, $0x00001a9e7b
DATA dsaZetas<>+512(SB)/4, $0x00000006d9
DATA dsaZetas<>+516(SB)/4, $0x00006257c5
DATA dsaZetas<>+520(SB)/4, $0x0000574b3c
DATA dsaZetas<>+524(SB)/4, $0x000069a8ef
DATA dsaZetas<>+528(SB)/4, $0x0000289838
DATA dsaZetas<>+532(SB)/4, $0x000064b5fe
DATA dsaZetas<>+536(SB)/4, $0x00007ef8f5
DATA dsaZetas<>+540(SB)/4, $0x00002a4e78
DATA dsaZetas<>+544(SB)/4, $0x0000120a23
DATA dsaZetas<>+548(SB)/4, $0x00000154a8
DATA dsaZetas<>+552(SB)/4, $0x000009b7ff
DATA dsaZetas<>+556(SB)/4, $0x0000435e87
DATA dsaZetas<>+560(SB)/4, $0x0000437ff8
DATA dsaZetas<>+564(SB)/4, $0x00005cd5b4
DATA dsaZetas<>+568(SB)/4, $0x00004dc04e
DATA dsaZetas<>+572(SB)/4, $0x00004728af
DATA dsaZetas<>+576(SB)/4, $0x00007f735d
DATA dsaZetas<>+580(SB)/4, $0x00000c8d0d
DATA dsaZetas<>+584(SB)/4, $0x00000f66d5
DATA dsaZetas<>+588(SB)/4, $0x00005a6d80
DATA dsaZetas<>+592(SB)/4, $0x000061ab98
DATA dsaZetas<>+596(SB)/4, $0x0000185d96
DATA dsaZetas<>+600(SB)/4, $0x0000437f31
DATA dsaZetas<>+604(SB)/4, $0x0000468298
DATA dsaZetas<>+608(SB)/4, $0x0000662960
DATA dsaZetas<>+612(SB)/4, $0x00004bd579
DATA dsaZetas<>+616(SB)/4, $0x000028de06
DATA dsaZetas<>+620(SB)/4, $0x0000465d8d
DATA dsaZetas<>+624(SB)/4, $0x000049b0e3
DATA dsaZetas<>+628(SB)/4, $0x000009b434
DATA dsaZetas<>+632(SB)/4, $0x00007c0db3
DATA dsaZetas<>+636(SB)/4, $0x00005a68b0
DATA dsaZetas<>+640(SB)/4, $0x0000409ba9
DATA dsaZetas<>+644(SB)/4, $0x000064d3d5
DATA dsaZetas<>+648(SB)/4, $0x000021762a
DATA dsaZetas<>+652(SB)/4, $0x0000658591
DATA dsaZetas<>+656(SB)/4, $0x0000246e39
DATA dsaZetas<>+660(SB)/4, $0x000048c39b
DATA dsaZetas<>+664(SB)/4, $0x00007bc759
DATA dsaZetas<>+668(SB)/4, $0x00004f5859
DATA dsaZetas<>+672(SB)/4, $0x0000392db2
DATA dsaZetas<>+676(SB)/4, $0x0000230923
DATA dsaZetas<>+680(SB)/4, $0x000012eb67
DATA dsaZetas<>+684(SB)/4, $0x0000454df2
DATA dsaZetas<>+688(SB)/4, $0x000030c31c
DATA dsaZetas<>+692(SB)/4, $0x0000285424
DATA dsaZetas<>+696(SB)/4, $0x000013232e
DATA dsaZetas<>+700(SB)/4, $0x00007faf80
DATA dsaZetas<>+704(SB)/4, $0x00002dbfcb
DATA dsaZetas<>+708(SB)/4, $0x0000022a0b
DATA dsaZetas<>+712(SB)/4, $0x00007e832c
DATA dsaZetas<>+716(SB)/4, $0x000026587a
DATA dsaZetas<>+720(SB)/4, $0x00006b3375
DATA dsaZetas<>+724(SB)/4, $0x0000095b76
DATA dsaZetas<>+728(SB)/4, $0x00006be1cc
DATA dsaZetas<>+732(SB)/4, $0x00005e061e
DATA dsaZetas<>+736(SB)/4, $0x000078e00d
DATA dsaZetas<>+740(SB)/4, $0x0000628c37
DATA dsaZetas<>+744(SB)/4, $0x00003da604
DATA dsaZetas<>+748(SB)/4, $0x00004ae53c
DATA dsaZetas<>+752(SB)/4, $0x00001f1d68
DATA dsaZetas<>+756(SB)/4, $0x00006330bb
DATA dsaZetas<>+760(SB)/4, $0x00007361b8
DATA dsaZetas<>+764(SB)/4, $0x00005ea06c
DATA dsaZetas<>+768(SB)/4, $0x0000671ac7
DATA dsaZetas<>+772(SB)/4, $0x0000201fc6
DATA dsaZetas<>+776(SB)/4, $0x00005ba4ff
DATA dsaZetas<>+780(SB)/4, $0x000060d772
DATA dsaZetas<>+784(SB)/4, $0x000008f201
DATA dsaZetas<>+788(SB)/4, $0x00006de024
DATA dsaZetas<>+792(SB)/4, $0x0000080e6d
DATA dsaZetas<>+796(SB)/4, $0x000056038e
DATA dsaZetas<>+800(SB)/4, $0x0000695688
DATA dsaZetas<>+804(SB)/4, $0x00001e6d3e
DATA dsaZetas<>+808(SB)/4, $0x00002603bd
DATA dsaZetas<>+812(SB)/4, $0x00006a9dfa
DATA dsaZetas<>+816(SB)/4, $0x000007c017
DATA dsaZetas<>+820(SB)/4, $0x00006dbfd4
DATA dsaZetas<>+824(SB)/4, $0x000074d0bd
DATA dsaZetas<>+828(SB)/4, $0x000063e1e3
DATA dsaZetas<>+832(SB)/4, $0x0000519573
DATA dsaZetas<>+836(SB)/4, $0x00007ab60d
DATA dsaZetas<>+840(SB)/4, $0x00002867ba
DATA dsaZetas<>+844(SB)/4, $0x00002decd4
DATA dsaZetas<>+848(SB)/4, $0x000058018c
DATA dsaZetas<>+852(SB)/4, $0x00003f4cf5
DATA dsaZetas<>+856(SB)/4, $0x00000b7009
DATA dsaZetas<>+860(SB)/4, $0x0000427e23
DATA dsaZetas<>+864(SB)/4, $0x00003cbd37
DATA dsaZetas<>+868(SB)/4, $0x0000273333
DATA dsaZetas<>+872(SB)/4, $0x0000673957
DATA dsaZetas<>+876(SB)/4, $0x00001a4b5d
DATA dsaZetas<>+880(SB)/4, $0x0000196926
DATA dsaZetas<>+884(SB)/4, $0x00001ef206
DATA dsaZetas<>+888(SB)/4, $0x000011c14e
DATA dsaZetas<>+892(SB)/4, $0x00004c76c8
DATA dsaZetas<>+896(SB)/4, $0x00003cf42f
DATA dsaZetas<>+900(SB)/4, $0x00007fb19a
DATA dsaZetas<>+904(SB)/4, $0x00006af66c
DATA dsaZetas<>+908(SB)/4, $0x00002e1669
DATA dsaZetas<>+912(SB)/4, $0x00003352d6
DATA dsaZetas<>+916(SB)/4, $0x0000034760
DATA dsaZetas<>+920(SB)/4, $0x0000085260
DATA dsaZetas<>+924(SB)/4, $0x0000741e78
DATA dsaZetas<>+928(SB)/4, $0x00002f6316
DATA dsaZetas<>+932(SB)/4, $0x00006f0a11
DATA dsaZetas<>+936(SB)/4, $0x000007c0f1
DATA dsaZetas<>+940(SB)/4, $0x0000776d0b
DATA dsaZetas<>+944(SB)/4, $0x00000d1ff0
DATA dsaZetas<>+948(SB)/4, $0x0000345824
DATA dsaZetas<>+952(SB)/4, $0x00000223d4
DATA dsaZetas<>+956(SB)/4, $0x000068c559
DATA dsaZetas<>+960(SB)/4, $0x00005e8885
DATA dsaZetas<>+964(SB)/4, $0x00002faa32
DATA dsaZetas<>+968(SB)/4, $0x000023fc65
DATA dsaZetas<>+972(SB)/4, $0x00005e6942
DATA dsaZetas<>+976(SB)/4, $0x000051e0ed
DATA dsaZetas<>+980(SB)/4, $0x000065adb3
DATA dsaZetas<>+984(SB)/4, $0x00002ca5e6
DATA dsaZetas<>+988(SB)/4, $0x000079e1fe
DATA dsaZetas<>+992(SB)/4, $0x00007b4064
DATA dsaZetas<>+996(SB)/4, $0x000035e1dd
DATA dsaZetas<>+1000(SB)/4, $0x0000433aac
DATA dsaZetas<>+1004(SB)/4, $0x0000464ade
DATA dsaZetas<>+1008(SB)/4, $0x00001cfe14
DATA dsaZetas<>+1012(SB)/4, $0x000073f1ce
DATA dsaZetas<>+1016(SB)/4, $0x000010170e
DATA dsaZetas<>+1020(SB)/4, $0x000074b6d7
GLOBL dsaZetas<>(SB), RODATA|NOPTR, $1024

DATA dsaShoups<>+0(SB)/4, $0x0000000200
DATA dsaShoups<>+4(SB)/4, $0x0092e0bb09
DATA dsaShoups<>+8(SB)/4, $0x0073078efd
DATA dsaShoups<>+12(SB)/4, $0x0072e78afc
DATA dsaShoups<>+16(SB)/4, $0x009e33e1bc
DATA dsaShoups<>+20(SB)/4, $0x00a7e8dee7
DATA dsaShoups<>+24(SB)/4, $0x009fe85ed7
DATA dsaShoups<>+28(SB)/4, $0x009e3461dc
DATA dsaShoups<>+32(SB)/4, $0x00ed9ec1d5
DATA dsaShoups<>+36(SB)/4, $0x006c36b6d5
DATA dsaShoups<>+40(SB)/4, $0x0051efdb52
DATA dsaShoups<>+44(SB)/4, $0x0041100b80
DATA dsaShoups<>+48(SB)/4, $0x007301c58b
DATA dsaShoups<>+52(SB)/4, $0x00e14ae4f6
DATA dsaShoups<>+56(SB)/4, $0x00110765b7
DATA dsaShoups<>+60(SB)/4, $0x00dab23ad9
DATA dsaShoups<>+64(SB)/4, $0x00990b69a8
DATA dsaShoups<>+68(SB)/4, $0x0083e25f90
DATA dsaShoups<>+72(SB)/4, $0x00515bfa5b
DATA dsaShoups<>+76(SB)/4, $0x00ccd84878
DATA dsaShoups<>+80(SB)/4, $0x009456626f
DATA dsaShoups<>+84(SB)/4, $0x00f2bd155f
DATA dsaShoups<>+88(SB)/4, $0x0014ab0698
DATA dsaShoups<>+92(SB)/4, $0x00d730cc84
DATA dsaShoups<>+96(SB)/4, $0x009d659229
DATA dsaShoups<>+100(SB)/4, $0x00345e0518
DATA dsaShoups<>+104(SB)/4, $0x004af67b08
DATA dsaShoups<>+108(SB)/4, $0x002c9f0367
DATA dsaShoups<>+112(SB)/4, $0x00ec5e8fcb
DATA dsaShoups<>+116(SB)/4, $0x00927c0bdd
DATA dsaShoups<>+120(SB)/4, $0x005602adff
DATA dsaShoups<>+124(SB)/4, $0x0045c31a3b
DATA dsaShoups<>+128(SB)/4, $0x006e09d599
DATA dsaShoups<>+132(SB)/4, $0x00613a89e0
DATA dsaShoups<>+136(SB)/4, $0x0053b76b33
DATA dsaShoups<>+140(SB)/4, $0x009271813b
DATA dsaShoups<>+144(SB)/4, $0x00a0f8fafc
DATA dsaShoups<>+148(SB)/4, $0x0040314fd3
DATA dsaShoups<>+152(SB)/4, $0x00712c382b
DATA dsaShoups<>+156(SB)/4, $0x00236e6151
DATA dsaShoups<>+160(SB)/4, $0x000c0a4a7a
DATA dsaShoups<>+164(SB)/4, $0x001c5ef183
DATA dsaShoups<>+168(SB)/4, $0x002176b56a
DATA dsaShoups<>+172(SB)/4, $0x0094e3a1be
DATA dsaShoups<>+176(SB)/4, $0x003f49fc00
DATA dsaShoups<>+180(SB)/4, $0x00853af5b2
DATA dsaShoups<>+184(SB)/4, $0x006308a964
DATA dsaShoups<>+188(SB)/4, $0x0041dc9aa2
DATA dsaShoups<>+192(SB)/4, $0x0068524dc2
DATA dsaShoups<>+196(SB)/4, $0x0035be5529
DATA dsaShoups<>+200(SB)/4, $0x00e706c1e2
DATA dsaShoups<>+204(SB)/4, $0x0092cf30a6
DATA dsaShoups<>+208(SB)/4, $0x0072c29bc1
DATA dsaShoups<>+212(SB)/4, $0x00c4ddc9e8
DATA dsaShoups<>+216(SB)/4, $0x00cb8ceba3
DATA dsaShoups<>+220(SB)/4, $0x0087560c74
DATA dsaShoups<>+224(SB)/4, $0x00a77e9c58
DATA dsaShoups<>+228(SB)/4, $0x006184a466
DATA dsaShoups<>+232(SB)/4, $0x001102b08a
DATA dsaShoups<>+236(SB)/4, $0x00763a67ad
DATA dsaShoups<>+240(SB)/4, $0x00591dfacc
DATA dsaShoups<>+244(SB)/4, $0x0038a103cf
DATA dsaShoups<>+248(SB)/4, $0x006635e2ac
DATA dsaShoups<>+252(SB)/4, $0x0038c510d2
DATA dsaShoups<>+256(SB)/4, $0x005ddf591a
DATA dsaShoups<>+260(SB)/4, $0x002707337e
DATA dsaShoups<>+264(SB)/4, $0x00af7e3e30
DATA dsaShoups<>+268(SB)/4, $0x0075ab47e6
DATA dsaShoups<>+272(SB)/4, $0x007fca89a2
DATA dsaShoups<>+276(SB)/4, $0x009d8d3612
DATA dsaShoups<>+280(SB)/4, $0x00a0a5ea39
DATA dsaShoups<>+284(SB)/4, $0x00f7a0d044
DATA dsaShoups<>+288(SB)/4, $0x004ca4908a
DATA dsaShoups<>+292(SB)/4, $0x003df4288e
DATA dsaShoups<>+296(SB)/4, $0x003b300f8d
DATA dsaShoups<>+300(SB)/4, $0x008b708309
DATA dsaShoups<>+304(SB)/4, $0x0055e0ad7f
DATA dsaShoups<>+308(SB)/4, $0x00a4da6d51
DATA dsaShoups<>+312(SB)/4, $0x00de1b6f1f
DATA dsaShoups<>+316(SB)/4, $0x007f04d036
DATA dsaShoups<>+320(SB)/4, $0x002eadaf0e
DATA dsaShoups<>+324(SB)/4, $0x000ebe617a
DATA dsaShoups<>+328(SB)/4, $0x00231839c8
DATA dsaShoups<>+332(SB)/4, $0x00a582b161
DATA dsaShoups<>+336(SB)/4, $0x00eeb8e85c
DATA dsaShoups<>+340(SB)/4, $0x00052efbb4
DATA dsaShoups<>+344(SB)/4, $0x004b38a592
DATA dsaShoups<>+348(SB)/4, $0x009a24abf6
DATA dsaShoups<>+352(SB)/4, $0x0080b9fd7d
DATA dsaShoups<>+356(SB)/4, $0x0095705eec
DATA dsaShoups<>+360(SB)/4, $0x003cb8f9c4
DATA dsaShoups<>+364(SB)/4, $0x009e551608
DATA dsaShoups<>+368(SB)/4, $0x00350a3422
DATA dsaShoups<>+372(SB)/4, $0x000730ea2c
DATA dsaShoups<>+376(SB)/4, $0x009cb75a9d
DATA dsaShoups<>+380(SB)/4, $0x006389939d
DATA dsaShoups<>+384(SB)/4, $0x00b135e416
DATA dsaShoups<>+388(SB)/4, $0x00369df510
DATA dsaShoups<>+392(SB)/4, $0x00b6f55be9
DATA dsaShoups<>+396(SB)/4, $0x00bb1fba78
DATA dsaShoups<>+400(SB)/4, $0x006a5f5300
DATA dsaShoups<>+404(SB)/4, $0x0080390941
DATA dsaShoups<>+408(SB)/4, $0x00d849b2bc
DATA dsaShoups<>+412(SB)/4, $0x00b7d858a6
DATA dsaShoups<>+416(SB)/4, $0x00d7bf9435
DATA dsaShoups<>+420(SB)/4, $0x004b306181
DATA dsaShoups<>+424(SB)/4, $0x005cbdc6b8
DATA dsaShoups<>+428(SB)/4, $0x0012f9963f
DATA dsaShoups<>+432(SB)/4, $0x00772e0a94
DATA dsaShoups<>+436(SB)/4, $0x00da875820
DATA dsaShoups<>+440(SB)/4, $0x005960475f
DATA dsaShoups<>+444(SB)/4, $0x00671317f7
DATA dsaShoups<>+448(SB)/4, $0x00296f9b94
DATA dsaShoups<>+452(SB)/4, $0x00ab3537f7
DATA dsaShoups<>+456(SB)/4, $0x0051f7893e
DATA dsaShoups<>+460(SB)/4, $0x00ab1d8009
DATA dsaShoups<>+464(SB)/4, $0x009612636c
DATA dsaShoups<>+468(SB)/4, $0x0046a6b51f
DATA dsaShoups<>+472(SB)/4, $0x00ec0b4cfb
DATA dsaShoups<>+476(SB)/4, $0x00f1f9486e
DATA dsaShoups<>+480(SB)/4, $0x000aa7c1db
DATA dsaShoups<>+484(SB)/4, $0x00f5fc2f1f
DATA dsaShoups<>+488(SB)/4, $0x001ee3e6bb
DATA dsaShoups<>+492(SB)/4, $0x00b815b7fd
DATA dsaShoups<>+496(SB)/4, $0x008b59d15d
DATA dsaShoups<>+500(SB)/4, $0x00c547b863
DATA dsaShoups<>+504(SB)/4, $0x00bbac7fa8
DATA dsaShoups<>+508(SB)/4, $0x00354a4827
DATA dsaShoups<>+512(SB)/4, $0x00000db56d
DATA dsaShoups<>+516(SB)/4, $0x00c4e0c0a6
DATA dsaShoups<>+520(SB)/4, $0x00aec2272c
DATA dsaShoups<>+524(SB)/4, $0x00d386be08
DATA dsaShoups<>+528(SB)/4, $0x005144c08d
DATA dsaShoups<>+532(SB)/4, $0x00c99e6205
DATA dsaShoups<>+536(SB)/4, $0x00fe317460
DATA dsaShoups<>+540(SB)/4, $0x0054b21bdd
DATA dsaShoups<>+544(SB)/4, $0x00241d4d0b
DATA dsaShoups<>+548(SB)/4, $0x0002a9fa79
DATA dsaShoups<>+552(SB)/4, $0x001374db0f
DATA dsaShoups<>+556(SB)/4, $0x0086dec4a3
DATA dsaShoups<>+560(SB)/4, $0x008721b75f
DATA dsaShoups<>+564(SB)/4, $0x00b9d9dd03
DATA dsaShoups<>+568(SB)/4, $0x009ba784a9
DATA dsaShoups<>+572(SB)/4, $0x008e74fa21
DATA dsaShoups<>+576(SB)/4, $0x00ff2681a2
DATA dsaShoups<>+580(SB)/4, $0x00192061e6
DATA dsaShoups<>+584(SB)/4, $0x001ed55f1a
DATA dsaShoups<>+588(SB)/4, $0x00b50840a6
DATA dsaShoups<>+592(SB)/4, $0x00c388107d
DATA dsaShoups<>+596(SB)/4, $0x0030c75d75
DATA dsaShoups<>+600(SB)/4, $0x00872028fb
DATA dsaShoups<>+604(SB)/4, $0x008d287903
DATA dsaShoups<>+608(SB)/4, $0x00cc85dfde
DATA dsaShoups<>+612(SB)/4, $0x0097d0e509
DATA dsaShoups<>+616(SB)/4, $0x0051d07f7c
DATA dsaShoups<>+620(SB)/4, $0x008cde507a
DATA dsaShoups<>+624(SB)/4, $0x009386a682
DATA dsaShoups<>+628(SB)/4, $0x00136d4329
DATA dsaShoups<>+632(SB)/4, $0x00f8597a6d
DATA dsaShoups<>+636(SB)/4, $0x00b4fe9e3d
DATA dsaShoups<>+640(SB)/4, $0x008157a6e7
DATA dsaShoups<>+644(SB)/4, $0x00c9da1ef4
DATA dsaShoups<>+648(SB)/4, $0x0042fd12be
DATA dsaShoups<>+652(SB)/4, $0x00cb3defe5
DATA dsaShoups<>+656(SB)/4, $0x0048eead19
DATA dsaShoups<>+660(SB)/4, $0x0091ab9fc4
DATA dsaShoups<>+664(SB)/4, $0x00f7cca339
DATA dsaShoups<>+668(SB)/4, $0x009ed866dc
DATA dsaShoups<>+672(SB)/4, $0x007278011b
DATA dsaShoups<>+676(SB)/4, $0x004623ce67
DATA dsaShoups<>+680(SB)/4, $0x0025e045c5
DATA dsaShoups<>+684(SB)/4, $0x008abe928f
DATA dsaShoups<>+688(SB)/4, $0x00619e9ee4
DATA dsaShoups<>+692(SB)/4, $0x0050bc767c
DATA dsaShoups<>+696(SB)/4, $0x00264fefaf
DATA dsaShoups<>+700(SB)/4, $0x00ff9ee5ba
DATA dsaShoups<>+704(SB)/4, $0x005b967ae7
DATA dsaShoups<>+708(SB)/4, $0x0004552b42
DATA dsaShoups<>+712(SB)/4, $0x00fd45a76f
DATA dsaShoups<>+716(SB)/4, $0x004cc4246f
DATA dsaShoups<>+720(SB)/4, $0x00d69c8f76
DATA dsaShoups<>+724(SB)/4, $0x0012bb9ac1
DATA dsaShoups<>+728(SB)/4, $0x00d7f994b5
DATA dsaShoups<>+732(SB)/4, $0x00bc3b4959
DATA dsaShoups<>+736(SB)/4, $0x00f1fc9741
DATA dsaShoups<>+740(SB)/4, $0x00c549bee5
DATA dsaShoups<>+744(SB)/4, $0x007b6ae1c1
DATA dsaShoups<>+748(SB)/4, $0x0095eff2d0
DATA dsaShoups<>+752(SB)/4, $0x003e4a621b
DATA dsaShoups<>+756(SB)/4, $0x00c6931939
DATA dsaShoups<>+760(SB)/4, $0x00e6fd2d7d
DATA dsaShoups<>+764(SB)/4, $0x00bd703291
DATA dsaShoups<>+768(SB)/4, $0x00ce6926ac
DATA dsaShoups<>+772(SB)/4, $0x00404f9f67
DATA dsaShoups<>+776(SB)/4, $0x00b777da87
DATA dsaShoups<>+780(SB)/4, $0x00c1df5a52
DATA dsaShoups<>+784(SB)/4, $0x0011e87bfb
DATA dsaShoups<>+788(SB)/4, $0x00dbf74419
DATA dsaShoups<>+792(SB)/4, $0x001020e218
DATA dsaShoups<>+796(SB)/4, $0x00ac322731
DATA dsaShoups<>+800(SB)/4, $0x00d2e1c6cb
DATA dsaShoups<>+804(SB)/4, $0x003ce9b5f3
DATA dsaShoups<>+808(SB)/4, $0x004c1a8007
DATA dsaShoups<>+812(SB)/4, $0x00d5714ea8
DATA dsaShoups<>+816(SB)/4, $0x000f840ee4
DATA dsaShoups<>+820(SB)/4, $0x00dbb693ed
DATA dsaShoups<>+824(SB)/4, $0x00e9dbef28
DATA dsaShoups<>+828(SB)/4, $0x00c7f5c1e0
DATA dsaShoups<>+832(SB)/4, $0x00a353b9a7
DATA dsaShoups<>+836(SB)/4, $0x00f5a98275
DATA dsaShoups<>+840(SB)/4, $0x0050e3ac49
DATA dsaShoups<>+844(SB)/4, $0x005bf0a370
DATA dsaShoups<>+848(SB)/4, $0x00b02f2268
DATA dsaShoups<>+852(SB)/4, $0x007eb99768
DATA dsaShoups<>+856(SB)/4, $0x0016e5cb45
DATA dsaShoups<>+860(SB)/4, $0x00851d8c58
DATA dsaShoups<>+864(SB)/4, $0x007998d341
DATA dsaShoups<>+868(SB)/4, $0x004e7a03e4
DATA dsaShoups<>+872(SB)/4, $0x00cea655f8
DATA dsaShoups<>+876(SB)/4, $0x0034a3e28f
DATA dsaShoups<>+880(SB)/4, $0x0032df035b
DATA dsaShoups<>+884(SB)/4, $0x003df38866
DATA dsaShoups<>+888(SB)/4, $0x00238b7e98
DATA dsaShoups<>+892(SB)/4, $0x009913d3c2
DATA dsaShoups<>+896(SB)/4, $0x007a06dec3
DATA dsaShoups<>+900(SB)/4, $0x00ffa31ac7
DATA dsaShoups<>+904(SB)/4, $0x00d6225eeb
DATA dsaShoups<>+908(SB)/4, $0x005c43e240
DATA dsaShoups<>+912(SB)/4, $0x0066bf5b09
DATA dsaShoups<>+916(SB)/4, $0x000690640b
DATA dsaShoups<>+920(SB)/4, $0x0010a8ea19
DATA dsaShoups<>+924(SB)/4, $0x00e8770bf2
DATA dsaShoups<>+928(SB)/4, $0x005edde2ba
DATA dsaShoups<>+932(SB)/4, $0x00de4bb330
DATA dsaShoups<>+936(SB)/4, $0x000f85c351
DATA dsaShoups<>+940(SB)/4, $0x00ef15d998
DATA dsaShoups<>+944(SB)/4, $0x001a467167
DATA dsaShoups<>+948(SB)/4, $0x0068ca79cc
DATA dsaShoups<>+952(SB)/4, $0x000448ba25
DATA dsaShoups<>+956(SB)/4, $0x00d1bf2024
DATA dsaShoups<>+960(SB)/4, $0x00bd40589b
DATA dsaShoups<>+964(SB)/4, $0x005f6c3e50
DATA dsaShoups<>+968(SB)/4, $0x00480acc22
DATA dsaShoups<>+972(SB)/4, $0x00bd01c2f6
DATA dsaShoups<>+976(SB)/4, $0x00a3ead36d
DATA dsaShoups<>+980(SB)/4, $0x00cb8e47fa
DATA dsaShoups<>+984(SB)/4, $0x00596223d6
DATA dsaShoups<>+988(SB)/4, $0x00f400fa56
DATA dsaShoups<>+992(SB)/4, $0x00f6be75af
DATA dsaShoups<>+996(SB)/4, $0x006bdeb0d4
DATA dsaShoups<>+1000(SB)/4, $0x008696fcb1
DATA dsaShoups<>+1004(SB)/4, $0x008cb8e920
DATA dsaShoups<>+1008(SB)/4, $0x003a0aaa36
DATA dsaShoups<>+1012(SB)/4, $0x00e81da198
DATA dsaShoups<>+1016(SB)/4, $0x0020362949
DATA dsaShoups<>+1020(SB)/4, $0x00e9a81632
GLOBL dsaShoups<>(SB), RODATA|NOPTR, $1024

DATA dsaZetasReversed<>+0(SB)/4, $0x000074b6d7
DATA dsaZetasReversed<>+4(SB)/4, $0x000010170e
DATA dsaZetasReversed<>+8(SB)/4, $0x000073f1ce
DATA dsaZetasReversed<>+12(SB)/4, $0x00001cfe14
DATA dsaZetasReversed<>+16(SB)/4, $0x0000464ade
DATA dsaZetasReversed<>+20(SB)/4, $0x0000433aac
DATA dsaZetasReversed<>+24(SB)/4, $0x000035e1dd
DATA dsaZetasReversed<>+28(SB)/4, $0x00007b4064
DATA dsaZetasReversed<>+32(SB)/4, $0x000079e1fe
DATA dsaZetasReversed<>+36(SB)/4, $0x00002ca5e6
DATA dsaZetasReversed<>+40(SB)/4, $0x000065adb3
DATA dsaZetasReversed<>+44(SB)/4, $0x000051e0ed
DATA dsaZetasReversed<>+48(SB)/4, $0x00005e6942
DATA dsaZetasReversed<>+52(SB)/4, $0x000023fc65
DATA dsaZetasReversed<>+56(SB)/4, $0x00002faa32
DATA dsaZetasReversed<>+60(SB)/4, $0x00005e8885
DATA dsaZetasReversed<>+64(SB)/4, $0x000068c559
DATA dsaZetasReversed<>+68(SB)/4, $0x00000223d4
DATA dsaZetasReversed<>+72(SB)/4, $0x0000345824
DATA dsaZetasReversed<>+76(SB)/4, $0x00000d1ff0
DATA dsaZetasReversed<>+80(SB)/4, $0x0000776d0b
DATA dsaZetasReversed<>+84(SB)/4, $0x000007c0f1
DATA dsaZetasReversed<>+88(SB)/4, $0x00006f0a11
DATA dsaZetasReversed<>+92(SB)/4, $0x00002f6316
DATA dsaZetasReversed<>+96(SB)/4, $0x0000741e78
DATA dsaZetasReversed<>+100(SB)/4, $0x0000085260
DATA dsaZetasReversed<>+104(SB)/4, $0x0000034760
DATA dsaZetasReversed<>+108(SB)/4, $0x00003352d6
DATA dsaZetasReversed<>+112(SB)/4, $0x00002e1669
DATA dsaZetasReversed<>+116(SB)/4, $0x00006af66c
DATA dsaZetasReversed<>+120(SB)/4, $0x00007fb19a
DATA dsaZetasReversed<>+124(SB)/4, $0x00003cf42f
DATA dsaZetasReversed<>+128(SB)/4, $0x00004c76c8
DATA dsaZetasReversed<>+132(SB)/4, $0x000011c14e
DATA dsaZetasReversed<>+136(SB)/4, $0x00001ef206
DATA dsaZetasReversed<>+140(SB)/4, $0x0000196926
DATA dsaZetasReversed<>+144(SB)/4, $0x00001a4b5d
DATA dsaZetasReversed<>+148(SB)/4, $0x0000673957
DATA dsaZetasReversed<>+152(SB)/4, $0x0000273333
DATA dsaZetasReversed<>+156(SB)/4, $0x00003cbd37
DATA dsaZetasReversed<>+160(SB)/4, $0x0000427e23
DATA dsaZetasReversed<>+164(SB)/4, $0x00000b7009
DATA dsaZetasReversed<>+168(SB)/4, $0x00003f4cf5
DATA dsaZetasReversed<>+172(SB)/4, $0x000058018c
DATA dsaZetasReversed<>+176(SB)/4, $0x00002decd4
DATA dsaZetasReversed<>+180(SB)/4, $0x00002867ba
DATA dsaZetasReversed<>+184(SB)/4, $0x00007ab60d
DATA dsaZetasReversed<>+188(SB)/4, $0x0000519573
DATA dsaZetasReversed<>+192(SB)/4, $0x000063e1e3
DATA dsaZetasReversed<>+196(SB)/4, $0x000074d0bd
DATA dsaZetasReversed<>+200(SB)/4, $0x00006dbfd4
DATA dsaZetasReversed<>+204(SB)/4, $0x000007c017
DATA dsaZetasReversed<>+208(SB)/4, $0x00006a9dfa
DATA dsaZetasReversed<>+212(SB)/4, $0x00002603bd
DATA dsaZetasReversed<>+216(SB)/4, $0x00001e6d3e
DATA dsaZetasReversed<>+220(SB)/4, $0x0000695688
DATA dsaZetasReversed<>+224(SB)/4, $0x000056038e
DATA dsaZetasReversed<>+228(SB)/4, $0x0000080e6d
DATA dsaZetasReversed<>+232(SB)/4, $0x00006de024
DATA dsaZetasReversed<>+236(SB)/4, $0x000008f201
DATA dsaZetasReversed<>+240(SB)/4, $0x000060d772
DATA dsaZetasReversed<>+244(SB)/4, $0x00005ba4ff
DATA dsaZetasReversed<>+248(SB)/4, $0x0000201fc6
DATA dsaZetasReversed<>+252(SB)/4, $0x0000671ac7
DATA dsaZetasReversed<>+256(SB)/4, $0x00005ea06c
DATA dsaZetasReversed<>+260(SB)/4, $0x00007361b8
DATA dsaZetasReversed<>+264(SB)/4, $0x00006330bb
DATA dsaZetasReversed<>+268(SB)/4, $0x00001f1d68
DATA dsaZetasReversed<>+272(SB)/4, $0x00004ae53c
DATA dsaZetasReversed<>+276(SB)/4, $0x00003da604
DATA dsaZetasReversed<>+280(SB)/4, $0x0000628c37
DATA dsaZetasReversed<>+284(SB)/4, $0x000078e00d
DATA dsaZetasReversed<>+288(SB)/4, $0x00005e061e
DATA dsaZetasReversed<>+292(SB)/4, $0x00006be1cc
DATA dsaZetasReversed<>+296(SB)/4, $0x0000095b76
DATA dsaZetasReversed<>+300(SB)/4, $0x00006b3375
DATA dsaZetasReversed<>+304(SB)/4, $0x000026587a
DATA dsaZetasReversed<>+308(SB)/4, $0x00007e832c
DATA dsaZetasReversed<>+312(SB)/4, $0x0000022a0b
DATA dsaZetasReversed<>+316(SB)/4, $0x00002dbfcb
DATA dsaZetasReversed<>+320(SB)/4, $0x00007faf80
DATA dsaZetasReversed<>+324(SB)/4, $0x000013232e
DATA dsaZetasReversed<>+328(SB)/4, $0x0000285424
DATA dsaZetasReversed<>+332(SB)/4, $0x000030c31c
DATA dsaZetasReversed<>+336(SB)/4, $0x0000454df2
DATA dsaZetasReversed<>+340(SB)/4, $0x000012eb67
DATA dsaZetasReversed<>+344(SB)/4, $0x0000230923
DATA dsaZetasReversed<>+348(SB)/4, $0x0000392db2
DATA dsaZetasReversed<>+352(SB)/4, $0x00004f5859
DATA dsaZetasReversed<>+356(SB)/4, $0x00007bc759
DATA dsaZetasReversed<>+360(SB)/4, $0x000048c39b
DATA dsaZetasReversed<>+364(SB)/4, $0x0000246e39
DATA dsaZetasReversed<>+368(SB)/4, $0x0000658591
DATA dsaZetasReversed<>+372(SB)/4, $0x000021762a
DATA dsaZetasReversed<>+376(SB)/4, $0x000064d3d5
DATA dsaZetasReversed<>+380(SB)/4, $0x0000409ba9
DATA dsaZetasReversed<>+384(SB)/4, $0x00005a68b0
DATA dsaZetasReversed<>+388(SB)/4, $0x00007c0db3
DATA dsaZetasReversed<>+392(SB)/4, $0x000009b434
DATA dsaZetasReversed<>+396(SB)/4, $0x000049b0e3
DATA dsaZetasReversed<>+400(SB)/4, $0x0000465d8d
DATA dsaZetasReversed<>+404(SB)/4, $0x000028de06
DATA dsaZetasReversed<>+408(SB)/4, $0x00004bd579
DATA dsaZetasReversed<>+412(SB)/4, $0x0000662960
DATA dsaZetasReversed<>+416(SB)/4, $0x0000468298
DATA dsaZetasReversed<>+420(SB)/4, $0x0000437f31
DATA dsaZetasReversed<>+424(SB)/4, $0x0000185d96
DATA dsaZetasReversed<>+428(SB)/4, $0x000061ab98
DATA dsaZetasReversed<>+432(SB)/4, $0x00005a6d80
DATA dsaZetasReversed<>+436(SB)/4, $0x00000f66d5
DATA dsaZetasReversed<>+440(SB)/4, $0x00000c8d0d
DATA dsaZetasReversed<>+444(SB)/4, $0x00007f735d
DATA dsaZetasReversed<>+448(SB)/4, $0x00004728af
DATA dsaZetasReversed<>+452(SB)/4, $0x00004dc04e
DATA dsaZetasReversed<>+456(SB)/4, $0x00005cd5b4
DATA dsaZetasReversed<>+460(SB)/4, $0x0000437ff8
DATA dsaZetasReversed<>+464(SB)/4, $0x0000435e87
DATA dsaZetasReversed<>+468(SB)/4, $0x000009b7ff
DATA dsaZetasReversed<>+472(SB)/4, $0x00000154a8
DATA dsaZetasReversed<>+476(SB)/4, $0x0000120a23
DATA dsaZetasReversed<>+480(SB)/4, $0x00002a4e78
DATA dsaZetasReversed<>+484(SB)/4, $0x00007ef8f5
DATA dsaZetasReversed<>+488(SB)/4, $0x000064b5fe
DATA dsaZetasReversed<>+492(SB)/4, $0x0000289838
DATA dsaZetasReversed<>+496(SB)/4, $0x000069a8ef
DATA dsaZetasReversed<>+500(SB)/4, $0x0000574b3c
DATA dsaZetasReversed<>+504(SB)/4, $0x00006257c5
DATA dsaZetasReversed<>+508(SB)/4, $0x00000006d9
DATA dsaZetasReversed<>+512(SB)/4, $0x00001a9e7b
DATA dsaZetasReversed<>+516(SB)/4, $0x00005dbecb
DATA dsaZetasReversed<>+520(SB)/4, $0x0000628b34
DATA dsaZetasReversed<>+524(SB)/4, $0x0000459b7e
DATA dsaZetasReversed<>+528(SB)/4, $0x00005bf3da
DATA dsaZetasReversed<>+532(SB)/4, $0x00000f6e17
DATA dsaZetasReversed<>+536(SB)/4, $0x00007adf59
DATA dsaZetasReversed<>+540(SB)/4, $0x000005528c
DATA dsaZetasReversed<>+544(SB)/4, $0x000078de66
DATA dsaZetasReversed<>+548(SB)/4, $0x000075e826
DATA dsaZetasReversed<>+552(SB)/4, $0x0000234a86
DATA dsaZetasReversed<>+556(SB)/4, $0x00004af670
DATA dsaZetasReversed<>+560(SB)/4, $0x000055795d
DATA dsaZetasReversed<>+564(SB)/4, $0x000028f186
DATA dsaZetasReversed<>+568(SB)/4, $0x0000558536
DATA dsaZetasReversed<>+572(SB)/4, $0x000014b2a0
DATA dsaZetasReversed<>+576(SB)/4, $0x0000337caa
DATA dsaZetasReversed<>+580(SB)/4, $0x00002ca4f8
DATA dsaZetasReversed<>+584(SB)/4, $0x00006d285c
DATA dsaZetasReversed<>+588(SB)/4, $0x00003b8820
DATA dsaZetasReversed<>+592(SB)/4, $0x0000097a6c
DATA dsaZetasReversed<>+596(SB)/4, $0x00002e534c
DATA dsaZetasReversed<>+600(SB)/4, $0x0000258ecb
DATA dsaZetasReversed<>+604(SB)/4, $0x00006bc4d3
DATA dsaZetasReversed<>+608(SB)/4, $0x00005bd532
DATA dsaZetasReversed<>+612(SB)/4, $0x00006c09d1
DATA dsaZetasReversed<>+616(SB)/4, $0x0000400c7e
DATA dsaZetasReversed<>+620(SB)/4, $0x000035225e
DATA dsaZetasReversed<>+624(SB)/4, $0x00005d787a
DATA dsaZetasReversed<>+628(SB)/4, $0x00005b63d0
DATA dsaZetasReversed<>+632(SB)/4, $0x00001b4827
DATA dsaZetasReversed<>+636(SB)/4, $0x00005884cc
DATA dsaZetasReversed<>+640(SB)/4, $0x000031b859
DATA dsaZetasReversed<>+644(SB)/4, $0x00004e4817
DATA dsaZetasReversed<>+648(SB)/4, $0x000003978f
DATA dsaZetasReversed<>+652(SB)/4, $0x00001a7e79
DATA dsaZetasReversed<>+656(SB)/4, $0x00004f16c1
DATA dsaZetasReversed<>+660(SB)/4, $0x00001e54e6
DATA dsaZetasReversed<>+664(SB)/4, $0x00004aa582
DATA dsaZetasReversed<>+668(SB)/4, $0x0000404ce8
DATA dsaZetasReversed<>+672(SB)/4, $0x00004cff12
DATA dsaZetasReversed<>+676(SB)/4, $0x00002592ec
DATA dsaZetasReversed<>+680(SB)/4, $0x00000296d8
DATA dsaZetasReversed<>+684(SB)/4, $0x0000773e9e
DATA dsaZetasReversed<>+688(SB)/4, $0x000052aca9
DATA dsaZetasReversed<>+692(SB)/4, $0x00001187ba
DATA dsaZetasReversed<>+696(SB)/4, $0x0000075d59
DATA dsaZetasReversed<>+700(SB)/4, $0x0000175102
DATA dsaZetasReversed<>+704(SB)/4, $0x00003f7288
DATA dsaZetasReversed<>+708(SB)/4, $0x00006ef1f5
DATA dsaZetasReversed<>+712(SB)/4, $0x000052589c
DATA dsaZetasReversed<>+716(SB)/4, $0x00002ae59b
DATA dsaZetasReversed<>+720(SB)/4, $0x000045a6d4
DATA dsaZetasReversed<>+724(SB)/4, $0x00001d90a2
DATA dsaZetasReversed<>+728(SB)/4, $0x00001ef256
DATA dsaZetasReversed<>+732(SB)/4, $0x00002648b4
DATA dsaZetasReversed<>+736(SB)/4, $0x00007bb175
DATA dsaZetasReversed<>+740(SB)/4, $0x0000503ee1
DATA dsaZetasReversed<>+744(SB)/4, $0x00004eb2ea
DATA dsaZetasReversed<>+748(SB)/4, $0x00003fd54c
DATA dsaZetasReversed<>+752(SB)/4, $0x00003ac6ef
DATA dsaZetasReversed<>+756(SB)/4, $0x000057a930
DATA dsaZetasReversed<>+760(SB)/4, $0x0000137eb9
DATA dsaZetasReversed<>+764(SB)/4, $0x00002ee3f1
DATA dsaZetasReversed<>+768(SB)/4, $0x00001c5b70
DATA dsaZetasReversed<>+772(SB)/4, $0x0000330e2b
DATA dsaZetasReversed<>+776(SB)/4, $0x00001c496e
DATA dsaZetasReversed<>+780(SB)/4, $0x00002c83da
DATA dsaZetasReversed<>+784(SB)/4, $0x00003b0e6d
DATA dsaZetasReversed<>+788(SB)/4, $0x0000087f38
DATA dsaZetasReversed<>+792(SB)/4, $0x000030b622
DATA dsaZetasReversed<>+796(SB)/4, $0x000053aa5f
DATA dsaZetasReversed<>+800(SB)/4, $0x0000439a1c
DATA dsaZetasReversed<>+804(SB)/4, $0x000065ad05
DATA dsaZetasReversed<>+808(SB)/4, $0x000062564a
DATA dsaZetasReversed<>+812(SB)/4, $0x00003952f6
DATA dsaZetasReversed<>+816(SB)/4, $0x000049553f
DATA dsaZetasReversed<>+820(SB)/4, $0x0000736681
DATA dsaZetasReversed<>+824(SB)/4, $0x00001ad873
DATA dsaZetasReversed<>+828(SB)/4, $0x0000341c1d
DATA dsaZetasReversed<>+832(SB)/4, $0x000020e612
DATA dsaZetasReversed<>+836(SB)/4, $0x00003177f4
DATA dsaZetasReversed<>+840(SB)/4, $0x0000428cd4
DATA dsaZetasReversed<>+844(SB)/4, $0x00001f9d15
DATA dsaZetasReversed<>+848(SB)/4, $0x00004a5f35
DATA dsaZetasReversed<>+852(SB)/4, $0x000010b72c
DATA dsaZetasReversed<>+856(SB)/4, $0x00000e2bed
DATA dsaZetasReversed<>+860(SB)/4, $0x00000603a4
DATA dsaZetasReversed<>+864(SB)/4, $0x000011b2c3
DATA dsaZetasReversed<>+868(SB)/4, $0x00003887f7
DATA dsaZetasReversed<>+872(SB)/4, $0x00002010a2
DATA dsaZetasReversed<>+876(SB)/4, $0x000050685f
DATA dsaZetasReversed<>+880(SB)/4, $0x0000492673
DATA dsaZetasReversed<>+884(SB)/4, $0x000029d13f
DATA dsaZetasReversed<>+888(SB)/4, $0x000030911e
DATA dsaZetasReversed<>+892(SB)/4, $0x000036f72a
DATA dsaZetasReversed<>+896(SB)/4, $0x000022d8d5
DATA dsaZetasReversed<>+900(SB)/4, $0x00002af697
DATA dsaZetasReversed<>+904(SB)/4, $0x0000492bb7
DATA dsaZetasReversed<>+908(SB)/4, $0x00007611bd
DATA dsaZetasReversed<>+912(SB)/4, $0x00001649ee
DATA dsaZetasReversed<>+916(SB)/4, $0x00002571df
DATA dsaZetasReversed<>+920(SB)/4, $0x00001a2877
DATA dsaZetasReversed<>+924(SB)/4, $0x00004e9f1d
DATA dsaZetasReversed<>+928(SB)/4, $0x00006b7d81
DATA dsaZetasReversed<>+932(SB)/4, $0x00000a52ee
DATA dsaZetasReversed<>+936(SB)/4, $0x0000794034
DATA dsaZetasReversed<>+940(SB)/4, $0x00004a18a7
DATA dsaZetasReversed<>+944(SB)/4, $0x000066528a
DATA dsaZetasReversed<>+948(SB)/4, $0x000028a3d2
DATA dsaZetasReversed<>+952(SB)/4, $0x000041e0b4
DATA dsaZetasReversed<>+956(SB)/4, $0x00004c7294
DATA dsaZetasReversed<>+960(SB)/4, $0x00006d3dc8
DATA dsaZetasReversed<>+964(SB)/4, $0x0000088192
DATA dsaZetasReversed<>+968(SB)/4, $0x000070894a
DATA dsaZetasReversed<>+972(SB)/4, $0x0000397283
DATA dsaZetasReversed<>+976(SB)/4, $0x0000207fe4
DATA dsaZetasReversed<>+980(SB)/4, $0x000028edb0
DATA dsaZetasReversed<>+984(SB)/4, $0x0000360dd5
DATA dsaZetasReversed<>+988(SB)/4, $0x000076b1ae
DATA dsaZetasReversed<>+992(SB)/4, $0x00004f066b
DATA dsaZetasReversed<>+996(SB)/4, $0x00004fe033
DATA dsaZetasReversed<>+1000(SB)/4, $0x000053df73
DATA dsaZetasReversed<>+1004(SB)/4, $0x00004f062b
DATA dsaZetasReversed<>+1008(SB)/4, $0x0000396569
DATA dsaZetasReversed<>+1012(SB)/4, $0x0000397567
DATA dsaZetasReversed<>+1016(SB)/4, $0x0000495e02
DATA dsaZetasReversed<>+1020(SB)/4, $0x0000000001
GLOBL dsaZetasReversed<>(SB), RODATA|NOPTR, $1024

DATA dsaShoupsReversed<>+0(SB)/4, $0x00e9a81632
DATA dsaShoupsReversed<>+4(SB)/4, $0x0020362949
DATA dsaShoupsReversed<>+8(SB)/4, $0x00e81da198
DATA dsaShoupsReversed<>+12(SB)/4, $0x003a0aaa36
DATA dsaShoupsReversed<>+16(SB)/4, $0x008cb8e920
DATA dsaShoupsReversed<>+20(SB)/4, $0x008696fcb1
DATA dsaShoupsReversed<>+24(SB)/4, $0x006bdeb0d4
DATA dsaShoupsReversed<>+28(SB)/4, $0x00f6be75af
DATA dsaShoupsReversed<>+32(SB)/4, $0x00f400fa56
DATA dsaShoupsReversed<>+36(SB)/4, $0x00596223d6
DATA dsaShoupsReversed<>+40(SB)/4, $0x00cb8e47fa
DATA dsaShoupsReversed<>+44(SB)/4, $0x00a3ead36d
DATA dsaShoupsReversed<>+48(SB)/4, $0x00bd01c2f6
DATA dsaShoupsReversed<>+52(SB)/4, $0x00480acc22
DATA dsaShoupsReversed<>+56(SB)/4, $0x005f6c3e50
DATA dsaShoupsReversed<>+60(SB)/4, $0x00bd40589b
DATA dsaShoupsReversed<>+64(SB)/4, $0x00d1bf2024
DATA dsaShoupsReversed<>+68(SB)/4, $0x000448ba25
DATA dsaShoupsReversed<>+72(SB)/4, $0x0068ca79cc
DATA dsaShoupsReversed<>+76(SB)/4, $0x001a467167
DATA dsaShoupsReversed<>+80(SB)/4, $0x00ef15d998
DATA dsaShoupsReversed<>+84(SB)/4, $0x000f85c351
DATA dsaShoupsReversed<>+88(SB)/4, $0x00de4bb330
DATA dsaShoupsReversed<>+92(SB)/4, $0x005edde2ba
DATA dsaShoupsReversed<>+96(SB)/4, $0x00e8770bf2
DATA dsaShoupsReversed<>+100(SB)/4, $0x0010a8ea19
DATA dsaShoupsReversed<>+104(SB)/4, $0x000690640b
DATA dsaShoupsReversed<>+108(SB)/4, $0x0066bf5b09
DATA dsaShoupsReversed<>+112(SB)/4, $0x005c43e240
DATA dsaShoupsReversed<>+116(SB)/4, $0x00d6225eeb
DATA dsaShoupsReversed<>+120(SB)/4, $0x00ffa31ac7
DATA dsaShoupsReversed<>+124(SB)/4, $0x007a06dec3
DATA dsaShoupsReversed<>+128(SB)/4, $0x009913d3c2
DATA dsaShoupsReversed<>+132(SB)/4, $0x00238b7e98
DATA dsaShoupsReversed<>+136(SB)/4, $0x003df38866
DATA dsaShoupsReversed<>+140(SB)/4, $0x0032df035b
DATA dsaShoupsReversed<>+144(SB)/4, $0x0034a3e28f
DATA dsaShoupsReversed<>+148(SB)/4, $0x00cea655f8
DATA dsaShoupsReversed<>+152(SB)/4, $0x004e7a03e4
DATA dsaShoupsReversed<>+156(SB)/4, $0x007998d341
DATA dsaShoupsReversed<>+160(SB)/4, $0x00851d8c58
DATA dsaShoupsReversed<>+164(SB)/4, $0x0016e5cb45
DATA dsaShoupsReversed<>+168(SB)/4, $0x007eb99768
DATA dsaShoupsReversed<>+172(SB)/4, $0x00b02f2268
DATA dsaShoupsReversed<>+176(SB)/4, $0x005bf0a370
DATA dsaShoupsReversed<>+180(SB)/4, $0x0050e3ac49
DATA dsaShoupsReversed<>+184(SB)/4, $0x00f5a98275
DATA dsaShoupsReversed<>+188(SB)/4, $0x00a353b9a7
DATA dsaShoupsReversed<>+192(SB)/4, $0x00c7f5c1e0
DATA dsaShoupsReversed<>+196(SB)/4, $0x00e9dbef28
DATA dsaShoupsReversed<>+200(SB)/4, $0x00dbb693ed
DATA dsaShoupsReversed<>+204(SB)/4, $0x000f840ee4
DATA dsaShoupsReversed<>+208(SB)/4, $0x00d5714ea8
DATA dsaShoupsReversed<>+212(SB)/4, $0x004c1a8007
DATA dsaShoupsReversed<>+216(SB)/4, $0x003ce9b5f3
DATA dsaShoupsReversed<>+220(SB)/4, $0x00d2e1c6cb
DATA dsaShoupsReversed<>+224(SB)/4, $0x00ac322731
DATA dsaShoupsReversed<>+228(SB)/4, $0x001020e218
DATA dsaShoupsReversed<>+232(SB)/4, $0x00dbf74419
DATA dsaShoupsReversed<>+236(SB)/4, $0x0011e87bfb
DATA dsaShoupsReversed<>+240(SB)/4, $0x00c1df5a52
DATA dsaShoupsReversed<>+244(SB)/4, $0x00b777da87
DATA dsaShoupsReversed<>+248(SB)/4, $0x00404f9f67
DATA dsaShoupsReversed<>+252(SB)/4, $0x00ce6926ac
DATA dsaShoupsReversed<>+256(SB)/4, $0x00bd703291
DATA dsaShoupsReversed<>+260(SB)/4, $0x00e6fd2d7d
DATA dsaShoupsReversed<>+264(SB)/4, $0x00c6931939
DATA dsaShoupsReversed<>+268(SB)/4, $0x003e4a621b
DATA dsaShoupsReversed<>+272(SB)/4, $0x0095eff2d0
DATA dsaShoupsReversed<>+276(SB)/4, $0x007b6ae1c1
DATA dsaShoupsReversed<>+280(SB)/4, $0x00c549bee5
DATA dsaShoupsReversed<>+284(SB)/4, $0x00f1fc9741
DATA dsaShoupsReversed<>+288(SB)/4, $0x00bc3b4959
DATA dsaShoupsReversed<>+292(SB)/4, $0x00d7f994b5
DATA dsaShoupsReversed<>+296(SB)/4, $0x0012bb9ac1
DATA dsaShoupsReversed<>+300(SB)/4, $0x00d69c8f76
DATA dsaShoupsReversed<>+304(SB)/4, $0x004cc4246f
DATA dsaShoupsReversed<>+308(SB)/4, $0x00fd45a76f
DATA dsaShoupsReversed<>+312(SB)/4, $0x0004552b42
DATA dsaShoupsReversed<>+316(SB)/4, $0x005b967ae7
DATA dsaShoupsReversed<>+320(SB)/4, $0x00ff9ee5ba
DATA dsaShoupsReversed<>+324(SB)/4, $0x00264fefaf
DATA dsaShoupsReversed<>+328(SB)/4, $0x0050bc767c
DATA dsaShoupsReversed<>+332(SB)/4, $0x00619e9ee4
DATA dsaShoupsReversed<>+336(SB)/4, $0x008abe928f
DATA dsaShoupsReversed<>+340(SB)/4, $0x0025e045c5
DATA dsaShoupsReversed<>+344(SB)/4, $0x004623ce67
DATA dsaShoupsReversed<>+348(SB)/4, $0x007278011b
DATA dsaShoupsReversed<>+352(SB)/4, $0x009ed866dc
DATA dsaShoupsReversed<>+356(SB)/4, $0x00f7cca339
DATA dsaShoupsReversed<>+360(SB)/4, $0x0091ab9fc4
DATA dsaShoupsReversed<>+364(SB)/4, $0x0048eead19
DATA dsaShoupsReversed<>+368(SB)/4, $0x00cb3defe5
DATA dsaShoupsReversed<>+372(SB)/4, $0x0042fd12be
DATA dsaShoupsReversed<>+376(SB)/4, $0x00c9da1ef4
DATA dsaShoupsReversed<>+380(SB)/4, $0x008157a6e7
DATA dsaShoupsReversed<>+384(SB)/4, $0x00b4fe9e3d
DATA dsaShoupsReversed<>+388(SB)/4, $0x00f8597a6d
DATA dsaShoupsReversed<>+392(SB)/4, $0x00136d4329
DATA dsaShoupsReversed<>+396(SB)/4, $0x009386a682
DATA dsaShoupsReversed<>+400(SB)/4, $0x008cde507a
DATA dsaShoupsReversed<>+404(SB)/4, $0x0051d07f7c
DATA dsaShoupsReversed<>+408(SB)/4, $0x0097d0e509
DATA dsaShoupsReversed<>+412(SB)/4, $0x00cc85dfde
DATA dsaShoupsReversed<>+416(SB)/4, $0x008d287903
DATA dsaShoupsReversed<>+420(SB)/4, $0x00872028fb
DATA dsaShoupsReversed<>+424(SB)/4, $0x0030c75d75
DATA dsaShoupsReversed<>+428(SB)/4, $0x00c388107d
DATA dsaShoupsReversed<>+432(SB)/4, $0x00b50840a6
DATA dsaShoupsReversed<>+436(SB)/4, $0x001ed55f1a
DATA dsaShoupsReversed<>+440(SB)/4, $0x00192061e6
DATA dsaShoupsReversed<>+444(SB)/4, $0x00ff2681a2
DATA dsaShoupsReversed<>+448(SB)/4, $0x008e74fa21
DATA dsaShoupsReversed<>+452(SB)/4, $0x009ba784a9
DATA dsaShoupsReversed<>+456(SB)/4, $0x00b9d9dd03
DATA dsaShoupsReversed<>+460(SB)/4, $0x008721b75f
DATA dsaShoupsReversed<>+464(SB)/4, $0x0086dec4a3
DATA dsaShoupsReversed<>+468(SB)/4, $0x001374db0f
DATA dsaShoupsReversed<>+472(SB)/4, $0x0002a9fa79
DATA dsaShoupsReversed<>+476(SB)/4, $0x00241d4d0b
DATA dsaShoupsReversed<>+480(SB)/4, $0x0054b21bdd
DATA dsaShoupsReversed<>+484(SB)/4, $0x00fe317460
DATA dsaShoupsReversed<>+488(SB)/4, $0x00c99e6205
DATA dsaShoupsReversed<>+492(SB)/4, $0x005144c08d
DATA dsaShoupsReversed<>+496(SB)/4, $0x00d386be08
DATA dsaShoupsReversed<>+500(SB)/4, $0x00aec2272c
DATA dsaShoupsReversed<>+504(SB)/4, $0x00c4e0c0a6
DATA dsaShoupsReversed<>+508(SB)/4, $0x00000db56d
DATA dsaShoupsReversed<>+512(SB)/4, $0x00354a4827
DATA dsaShoupsReversed<>+516(SB)/4, $0x00bbac7fa8
DATA dsaShoupsReversed<>+520(SB)/4, $0x00c547b863
DATA dsaShoupsReversed<>+524(SB)/4, $0x008b59d15d
DATA dsaShoupsReversed<>+528(SB)/4, $0x00b815b7fd
DATA dsaShoupsReversed<>+532(SB)/4, $0x001ee3e6bb
DATA dsaShoupsReversed<>+536(SB)/4, $0x00f5fc2f1f
DATA dsaShoupsReversed<>+540(SB)/4, $0x000aa7c1db
DATA dsaShoupsReversed<>+544(SB)/4, $0x00f1f9486e
DATA dsaShoupsReversed<>+548(SB)/4, $0x00ec0b4cfb
DATA dsaShoupsReversed<>+552(SB)/4, $0x0046a6b51f
DATA dsaShoupsReversed<>+556(SB)/4, $0x009612636c
DATA dsaShoupsReversed<>+560(SB)/4, $0x00ab1d8009
DATA dsaShoupsReversed<>+564(SB)/4, $0x0051f7893e
DATA dsaShoupsReversed<>+568(SB)/4, $0x00ab3537f7
DATA dsaShoupsReversed<>+572(SB)/4, $0x00296f9b94
DATA dsaShoupsReversed<>+576(SB)/4, $0x00671317f7
DATA dsaShoupsReversed<>+580(SB)/4, $0x005960475f
DATA dsaShoupsReversed<>+584(SB)/4, $0x00da875820
DATA dsaShoupsReversed<>+588(SB)/4, $0x00772e0a94
DATA dsaShoupsReversed<>+592(SB)/4, $0x0012f9963f
DATA dsaShoupsReversed<>+596(SB)/4, $0x005cbdc6b8
DATA dsaShoupsReversed<>+600(SB)/4, $0x004b306181
DATA dsaShoupsReversed<>+604(SB)/4, $0x00d7bf9435
DATA dsaShoupsReversed<>+608(SB)/4, $0x00b7d858a6
DATA dsaShoupsReversed<>+612(SB)/4, $0x00d849b2bc
DATA dsaShoupsReversed<>+616(SB)/4, $0x0080390941
DATA dsaShoupsReversed<>+620(SB)/4, $0x006a5f5300
DATA dsaShoupsReversed<>+624(SB)/4, $0x00bb1fba78
DATA dsaShoupsReversed<>+628(SB)/4, $0x00b6f55be9
DATA dsaShoupsReversed<>+632(SB)/4, $0x00369df510
DATA dsaShoupsReversed<>+636(SB)/4, $0x00b135e416
DATA dsaShoupsReversed<>+640(SB)/4, $0x006389939d
DATA dsaShoupsReversed<>+644(SB)/4, $0x009cb75a9d
DATA dsaShoupsReversed<>+648(SB)/4, $0x000730ea2c
DATA dsaShoupsReversed<>+652(SB)/4, $0x00350a3422
DATA dsaShoupsReversed<>+656(SB)/4, $0x009e551608
DATA dsaShoupsReversed<>+660(SB)/4, $0x003cb8f9c4
DATA dsaShoupsReversed<>+664(SB)/4, $0x0095705eec
DATA dsaShoupsReversed<>+668(SB)/4, $0x0080b9fd7d
DATA dsaShoupsReversed<>+672(SB)/4, $0x009a24abf6
DATA dsaShoupsReversed<>+676(SB)/4, $0x004b38a592
DATA dsaShoupsReversed<>+680(SB)/4, $0x00052efbb4
DATA dsaShoupsReversed<>+684(SB)/4, $0x00eeb8e85c
DATA dsaShoupsReversed<>+688(SB)/4, $0x00a582b161
DATA dsaShoupsReversed<>+692(SB)/4, $0x00231839c8
DATA dsaShoupsReversed<>+696(SB)/4, $0x000ebe617a
DATA dsaShoupsReversed<>+700(SB)/4, $0x002eadaf0e
DATA dsaShoupsReversed<>+704(SB)/4, $0x007f04d036
DATA dsaShoupsReversed<>+708(SB)/4, $0x00de1b6f1f
DATA dsaShoupsReversed<>+712(SB)/4, $0x00a4da6d51
DATA dsaShoupsReversed<>+716(SB)/4, $0x0055e0ad7f
DATA dsaShoupsReversed<>+720(SB)/4, $0x008b708309
DATA dsaShoupsReversed<>+724(SB)/4, $0x003b300f8d
DATA dsaShoupsReversed<>+728(SB)/4, $0x003df4288e
DATA dsaShoupsReversed<>+732(SB)/4, $0x004ca4908a
DATA dsaShoupsReversed<>+736(SB)/4, $0x00f7a0d044
DATA dsaShoupsReversed<>+740(SB)/4, $0x00a0a5ea39
DATA dsaShoupsReversed<>+744(SB)/4, $0x009d8d3612
DATA dsaShoupsReversed<>+748(SB)/4, $0x007fca89a2
DATA dsaShoupsReversed<>+752(SB)/4, $0x0075ab47e6
DATA dsaShoupsReversed<>+756(SB)/4, $0x00af7e3e30
DATA dsaShoupsReversed<>+760(SB)/4, $0x002707337e
DATA dsaShoupsReversed<>+764(SB)/4, $0x005ddf591a
DATA dsaShoupsReversed<>+768(SB)/4, $0x0038c510d2
DATA dsaShoupsReversed<>+772(SB)/4, $0x006635e2ac
DATA dsaShoupsReversed<>+776(SB)/4, $0x0038a103cf
DATA dsaShoupsReversed<>+780(SB)/4, $0x00591dfacc
DATA dsaShoupsReversed<>+784(SB)/4, $0x00763a67ad
DATA dsaShoupsReversed<>+788(SB)/4, $0x001102b08a
DATA dsaShoupsReversed<>+792(SB)/4, $0x006184a466
DATA dsaShoupsReversed<>+796(SB)/4, $0x00a77e9c58
DATA dsaShoupsReversed<>+800(SB)/4, $0x0087560c74
DATA dsaShoupsReversed<>+804(SB)/4, $0x00cb8ceba3
DATA dsaShoupsReversed<>+808(SB)/4, $0x00c4ddc9e8
DATA dsaShoupsReversed<>+812(SB)/4, $0x0072c29bc1
DATA dsaShoupsReversed<>+816(SB)/4, $0x0092cf30a6
DATA dsaShoupsReversed<>+820(SB)/4, $0x00e706c1e2
DATA dsaShoupsReversed<>+824(SB)/4, $0x0035be5529
DATA dsaShoupsReversed<>+828(SB)/4, $0x0068524dc2
DATA dsaShoupsReversed<>+832(SB)/4, $0x0041dc9aa2
DATA dsaShoupsReversed<>+836(SB)/4, $0x006308a964
DATA dsaShoupsReversed<>+840(SB)/4, $0x00853af5b2
DATA dsaShoupsReversed<>+844(SB)/4, $0x003f49fc00
DATA dsaShoupsReversed<>+848(SB)/4, $0x0094e3a1be
DATA dsaShoupsReversed<>+852(SB)/4, $0x002176b56a
DATA dsaShoupsReversed<>+856(SB)/4, $0x001c5ef183
DATA dsaShoupsReversed<>+860(SB)/4, $0x000c0a4a7a
DATA dsaShoupsReversed<>+864(SB)/4, $0x00236e6151
DATA dsaShoupsReversed<>+868(SB)/4, $0x00712c382b
DATA dsaShoupsReversed<>+872(SB)/4, $0x0040314fd3
DATA dsaShoupsReversed<>+876(SB)/4, $0x00a0f8fafc
DATA dsaShoupsReversed<>+880(SB)/4, $0x009271813b
DATA dsaShoupsReversed<>+884(SB)/4, $0x0053b76b33
DATA dsaShoupsReversed<>+888(SB)/4, $0x00613a89e0
DATA dsaShoupsReversed<>+892(SB)/4, $0x006e09d599
DATA dsaShoupsReversed<>+896(SB)/4, $0x0045c31a3b
DATA dsaShoupsReversed<>+900(SB)/4, $0x005602adff
DATA dsaShoupsReversed<>+904(SB)/4, $0x00927c0bdd
DATA dsaShoupsReversed<>+908(SB)/4, $0x00ec5e8fcb
DATA dsaShoupsReversed<>+912(SB)/4, $0x002c9f0367
DATA dsaShoupsReversed<>+916(SB)/4, $0x004af67b08
DATA dsaShoupsReversed<>+920(SB)/4, $0x00345e0518
DATA dsaShoupsReversed<>+924(SB)/4, $0x009d659229
DATA dsaShoupsReversed<>+928(SB)/4, $0x00d730cc84
DATA dsaShoupsReversed<>+932(SB)/4, $0x0014ab0698
DATA dsaShoupsReversed<>+936(SB)/4, $0x00f2bd155f
DATA dsaShoupsReversed<>+940(SB)/4, $0x009456626f
DATA dsaShoupsReversed<>+944(SB)/4, $0x00ccd84878
DATA dsaShoupsReversed<>+948(SB)/4, $0x00515bfa5b
DATA dsaShoupsReversed<>+952(SB)/4, $0x0083e25f90
DATA dsaShoupsReversed<>+956(SB)/4, $0x00990b69a8
DATA dsaShoupsReversed<>+960(SB)/4, $0x00dab23ad9
DATA dsaShoupsReversed<>+964(SB)/4, $0x00110765b7
DATA dsaShoupsReversed<>+968(SB)/4, $0x00e14ae4f6
DATA dsaShoupsReversed<>+972(SB)/4, $0x007301c58b
DATA dsaShoupsReversed<>+976(SB)/4, $0x0041100b80
DATA dsaShoupsReversed<>+980(SB)/4, $0x0051efdb52
DATA dsaShoupsReversed<>+984(SB)/4, $0x006c36b6d5
DATA dsaShoupsReversed<>+988(SB)/4, $0x00ed9ec1d5
DATA dsaShoupsReversed<>+992(SB)/4, $0x009e3461dc
DATA dsaShoupsReversed<>+996(SB)/4, $0x009fe85ed7
DATA dsaShoupsReversed<>+1000(SB)/4, $0x00a7e8dee7
DATA dsaShoupsReversed<>+1004(SB)/4, $0x009e33e1bc
DATA dsaShoupsReversed<>+1008(SB)/4, $0x0072e78afc
DATA dsaShoupsReversed<>+1012(SB)/4, $0x0073078efd
DATA dsaShoupsReversed<>+1016(SB)/4, $0x0092e0bb09
DATA dsaShoupsReversed<>+1020(SB)/4, $0x0000000200
GLOBL dsaShoupsReversed<>(SB), RODATA|NOPTR, $1024

DATA dsaForwardZetas<>+0(SB)/4, $0x0000495e02
DATA dsaForwardZetas<>+4(SB)/4, $0x0000397567
DATA dsaForwardZetas<>+8(SB)/4, $0x0000396569
DATA dsaForwardZetas<>+12(SB)/4, $0x00004f062b
DATA dsaForwardZetas<>+16(SB)/4, $0x000053df73
DATA dsaForwardZetas<>+20(SB)/4, $0x00004fe033
DATA dsaForwardZetas<>+24(SB)/4, $0x00004f066b
DATA dsaForwardZetas<>+28(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+32(SB)/4, $0x0092e0bb09
DATA dsaForwardZetas<>+36(SB)/4, $0x0073078efd
DATA dsaForwardZetas<>+40(SB)/4, $0x0072e78afc
DATA dsaForwardZetas<>+44(SB)/4, $0x009e33e1bc
DATA dsaForwardZetas<>+48(SB)/4, $0x00a7e8dee7
DATA dsaForwardZetas<>+52(SB)/4, $0x009fe85ed7
DATA dsaForwardZetas<>+56(SB)/4, $0x009e3461dc
DATA dsaForwardZetas<>+60(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+64(SB)/4, $0x000076b1ae
DATA dsaForwardZetas<>+68(SB)/4, $0x00004c7294
DATA dsaForwardZetas<>+72(SB)/4, $0x000041e0b4
DATA dsaForwardZetas<>+76(SB)/4, $0x000036f72a
DATA dsaForwardZetas<>+80(SB)/4, $0x000030911e
DATA dsaForwardZetas<>+84(SB)/4, $0x000029d13f
DATA dsaForwardZetas<>+88(SB)/4, $0x0000492673
DATA dsaForwardZetas<>+92(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+96(SB)/4, $0x00ed9ec1d5
DATA dsaForwardZetas<>+100(SB)/4, $0x00990b69a8
DATA dsaForwardZetas<>+104(SB)/4, $0x0083e25f90
DATA dsaForwardZetas<>+108(SB)/4, $0x006e09d599
DATA dsaForwardZetas<>+112(SB)/4, $0x00613a89e0
DATA dsaForwardZetas<>+116(SB)/4, $0x0053b76b33
DATA dsaForwardZetas<>+120(SB)/4, $0x009271813b
DATA dsaForwardZetas<>+124(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+128(SB)/4, $0x0000360dd5
DATA dsaForwardZetas<>+132(SB)/4, $0x000028a3d2
DATA dsaForwardZetas<>+136(SB)/4, $0x000066528a
DATA dsaForwardZetas<>+140(SB)/4, $0x000050685f
DATA dsaForwardZetas<>+144(SB)/4, $0x00002010a2
DATA dsaForwardZetas<>+148(SB)/4, $0x00003887f7
DATA dsaForwardZetas<>+152(SB)/4, $0x000011b2c3
DATA dsaForwardZetas<>+156(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+160(SB)/4, $0x006c36b6d5
DATA dsaForwardZetas<>+164(SB)/4, $0x00515bfa5b
DATA dsaForwardZetas<>+168(SB)/4, $0x00ccd84878
DATA dsaForwardZetas<>+172(SB)/4, $0x00a0f8fafc
DATA dsaForwardZetas<>+176(SB)/4, $0x0040314fd3
DATA dsaForwardZetas<>+180(SB)/4, $0x00712c382b
DATA dsaForwardZetas<>+184(SB)/4, $0x00236e6151
DATA dsaForwardZetas<>+188(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+192(SB)/4, $0x000028edb0
DATA dsaForwardZetas<>+196(SB)/4, $0x00004a18a7
DATA dsaForwardZetas<>+200(SB)/4, $0x0000794034
DATA dsaForwardZetas<>+204(SB)/4, $0x00000603a4
DATA dsaForwardZetas<>+208(SB)/4, $0x00000e2bed
DATA dsaForwardZetas<>+212(SB)/4, $0x000010b72c
DATA dsaForwardZetas<>+216(SB)/4, $0x00004a5f35
DATA dsaForwardZetas<>+220(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+224(SB)/4, $0x0051efdb52
DATA dsaForwardZetas<>+228(SB)/4, $0x009456626f
DATA dsaForwardZetas<>+232(SB)/4, $0x00f2bd155f
DATA dsaForwardZetas<>+236(SB)/4, $0x000c0a4a7a
DATA dsaForwardZetas<>+240(SB)/4, $0x001c5ef183
DATA dsaForwardZetas<>+244(SB)/4, $0x002176b56a
DATA dsaForwardZetas<>+248(SB)/4, $0x0094e3a1be
DATA dsaForwardZetas<>+252(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+256(SB)/4, $0x0000207fe4
DATA dsaForwardZetas<>+260(SB)/4, $0x00000a52ee
DATA dsaForwardZetas<>+264(SB)/4, $0x00006b7d81
DATA dsaForwardZetas<>+268(SB)/4, $0x00001f9d15
DATA dsaForwardZetas<>+272(SB)/4, $0x0000428cd4
DATA dsaForwardZetas<>+276(SB)/4, $0x00003177f4
DATA dsaForwardZetas<>+280(SB)/4, $0x000020e612
DATA dsaForwardZetas<>+284(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+288(SB)/4, $0x0041100b80
DATA dsaForwardZetas<>+292(SB)/4, $0x0014ab0698
DATA dsaForwardZetas<>+296(SB)/4, $0x00d730cc84
DATA dsaForwardZetas<>+300(SB)/4, $0x003f49fc00
DATA dsaForwardZetas<>+304(SB)/4, $0x00853af5b2
DATA dsaForwardZetas<>+308(SB)/4, $0x006308a964
DATA dsaForwardZetas<>+312(SB)/4, $0x0041dc9aa2
DATA dsaForwardZetas<>+316(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+320(SB)/4, $0x0000397283
DATA dsaForwardZetas<>+324(SB)/4, $0x00004e9f1d
DATA dsaForwardZetas<>+328(SB)/4, $0x00001a2877
DATA dsaForwardZetas<>+332(SB)/4, $0x0000341c1d
DATA dsaForwardZetas<>+336(SB)/4, $0x00001ad873
DATA dsaForwardZetas<>+340(SB)/4, $0x0000736681
DATA dsaForwardZetas<>+344(SB)/4, $0x000049553f
DATA dsaForwardZetas<>+348(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+352(SB)/4, $0x007301c58b
DATA dsaForwardZetas<>+356(SB)/4, $0x009d659229
DATA dsaForwardZetas<>+360(SB)/4, $0x00345e0518
DATA dsaForwardZetas<>+364(SB)/4, $0x0068524dc2
DATA dsaForwardZetas<>+368(SB)/4, $0x0035be5529
DATA dsaForwardZetas<>+372(SB)/4, $0x00e706c1e2
DATA dsaForwardZetas<>+376(SB)/4, $0x0092cf30a6
DATA dsaForwardZetas<>+380(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+384(SB)/4, $0x000070894a
DATA dsaForwardZetas<>+388(SB)/4, $0x00002571df
DATA dsaForwardZetas<>+392(SB)/4, $0x00001649ee
DATA dsaForwardZetas<>+396(SB)/4, $0x00003952f6
DATA dsaForwardZetas<>+400(SB)/4, $0x000062564a
DATA dsaForwardZetas<>+404(SB)/4, $0x000065ad05
DATA dsaForwardZetas<>+408(SB)/4, $0x0000439a1c
DATA dsaForwardZetas<>+412(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+416(SB)/4, $0x00e14ae4f6
DATA dsaForwardZetas<>+420(SB)/4, $0x004af67b08
DATA dsaForwardZetas<>+424(SB)/4, $0x002c9f0367
DATA dsaForwardZetas<>+428(SB)/4, $0x0072c29bc1
DATA dsaForwardZetas<>+432(SB)/4, $0x00c4ddc9e8
DATA dsaForwardZetas<>+436(SB)/4, $0x00cb8ceba3
DATA dsaForwardZetas<>+440(SB)/4, $0x0087560c74
DATA dsaForwardZetas<>+444(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+448(SB)/4, $0x0000088192
DATA dsaForwardZetas<>+452(SB)/4, $0x00007611bd
DATA dsaForwardZetas<>+456(SB)/4, $0x0000492bb7
DATA dsaForwardZetas<>+460(SB)/4, $0x000053aa5f
DATA dsaForwardZetas<>+464(SB)/4, $0x000030b622
DATA dsaForwardZetas<>+468(SB)/4, $0x0000087f38
DATA dsaForwardZetas<>+472(SB)/4, $0x00003b0e6d
DATA dsaForwardZetas<>+476(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+480(SB)/4, $0x00110765b7
DATA dsaForwardZetas<>+484(SB)/4, $0x00ec5e8fcb
DATA dsaForwardZetas<>+488(SB)/4, $0x00927c0bdd
DATA dsaForwardZetas<>+492(SB)/4, $0x00a77e9c58
DATA dsaForwardZetas<>+496(SB)/4, $0x006184a466
DATA dsaForwardZetas<>+500(SB)/4, $0x001102b08a
DATA dsaForwardZetas<>+504(SB)/4, $0x00763a67ad
DATA dsaForwardZetas<>+508(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+512(SB)/4, $0x00006d3dc8
DATA dsaForwardZetas<>+516(SB)/4, $0x00002af697
DATA dsaForwardZetas<>+520(SB)/4, $0x000022d8d5
DATA dsaForwardZetas<>+524(SB)/4, $0x00002c83da
DATA dsaForwardZetas<>+528(SB)/4, $0x00001c496e
DATA dsaForwardZetas<>+532(SB)/4, $0x0000330e2b
DATA dsaForwardZetas<>+536(SB)/4, $0x00001c5b70
DATA dsaForwardZetas<>+540(SB)/4, $0x0000000000
DATA dsaForwardZetas<>+544(SB)/4, $0x00dab23ad9
DATA dsaForwardZetas<>+548(SB)/4, $0x005602adff
DATA dsaForwardZetas<>+552(SB)/4, $0x0045c31a3b
DATA dsaForwardZetas<>+556(SB)/4, $0x00591dfacc
DATA dsaForwardZetas<>+560(SB)/4, $0x0038a103cf
DATA dsaForwardZetas<>+564(SB)/4, $0x006635e2ac
DATA dsaForwardZetas<>+568(SB)/4, $0x0038c510d2
DATA dsaForwardZetas<>+572(SB)/4, $0x0000000000
GLOBL dsaForwardZetas<>(SB), RODATA|NOPTR, $576

DATA dsaInverseZetas<>+0(SB)/4, $0x00001c5b70
DATA dsaInverseZetas<>+4(SB)/4, $0x0000330e2b
DATA dsaInverseZetas<>+8(SB)/4, $0x00001c496e
DATA dsaInverseZetas<>+12(SB)/4, $0x00002c83da
DATA dsaInverseZetas<>+16(SB)/4, $0x000022d8d5
DATA dsaInverseZetas<>+20(SB)/4, $0x00002af697
DATA dsaInverseZetas<>+24(SB)/4, $0x00006d3dc8
DATA dsaInverseZetas<>+28(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+32(SB)/4, $0x0038c510d2
DATA dsaInverseZetas<>+36(SB)/4, $0x006635e2ac
DATA dsaInverseZetas<>+40(SB)/4, $0x0038a103cf
DATA dsaInverseZetas<>+44(SB)/4, $0x00591dfacc
DATA dsaInverseZetas<>+48(SB)/4, $0x0045c31a3b
DATA dsaInverseZetas<>+52(SB)/4, $0x005602adff
DATA dsaInverseZetas<>+56(SB)/4, $0x00dab23ad9
DATA dsaInverseZetas<>+60(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+64(SB)/4, $0x00003b0e6d
DATA dsaInverseZetas<>+68(SB)/4, $0x0000087f38
DATA dsaInverseZetas<>+72(SB)/4, $0x000030b622
DATA dsaInverseZetas<>+76(SB)/4, $0x000053aa5f
DATA dsaInverseZetas<>+80(SB)/4, $0x0000492bb7
DATA dsaInverseZetas<>+84(SB)/4, $0x00007611bd
DATA dsaInverseZetas<>+88(SB)/4, $0x0000088192
DATA dsaInverseZetas<>+92(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+96(SB)/4, $0x00763a67ad
DATA dsaInverseZetas<>+100(SB)/4, $0x001102b08a
DATA dsaInverseZetas<>+104(SB)/4, $0x006184a466
DATA dsaInverseZetas<>+108(SB)/4, $0x00a77e9c58
DATA dsaInverseZetas<>+112(SB)/4, $0x00927c0bdd
DATA dsaInverseZetas<>+116(SB)/4, $0x00ec5e8fcb
DATA dsaInverseZetas<>+120(SB)/4, $0x00110765b7
DATA dsaInverseZetas<>+124(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+128(SB)/4, $0x0000439a1c
DATA dsaInverseZetas<>+132(SB)/4, $0x000065ad05
DATA dsaInverseZetas<>+136(SB)/4, $0x000062564a
DATA dsaInverseZetas<>+140(SB)/4, $0x00003952f6
DATA dsaInverseZetas<>+144(SB)/4, $0x00001649ee
DATA dsaInverseZetas<>+148(SB)/4, $0x00002571df
DATA dsaInverseZetas<>+152(SB)/4, $0x000070894a
DATA dsaInverseZetas<>+156(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+160(SB)/4, $0x0087560c74
DATA dsaInverseZetas<>+164(SB)/4, $0x00cb8ceba3
DATA dsaInverseZetas<>+168(SB)/4, $0x00c4ddc9e8
DATA dsaInverseZetas<>+172(SB)/4, $0x0072c29bc1
DATA dsaInverseZetas<>+176(SB)/4, $0x002c9f0367
DATA dsaInverseZetas<>+180(SB)/4, $0x004af67b08
DATA dsaInverseZetas<>+184(SB)/4, $0x00e14ae4f6
DATA dsaInverseZetas<>+188(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+192(SB)/4, $0x000049553f
DATA dsaInverseZetas<>+196(SB)/4, $0x0000736681
DATA dsaInverseZetas<>+200(SB)/4, $0x00001ad873
DATA dsaInverseZetas<>+204(SB)/4, $0x0000341c1d
DATA dsaInverseZetas<>+208(SB)/4, $0x00001a2877
DATA dsaInverseZetas<>+212(SB)/4, $0x00004e9f1d
DATA dsaInverseZetas<>+216(SB)/4, $0x0000397283
DATA dsaInverseZetas<>+220(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+224(SB)/4, $0x0092cf30a6
DATA dsaInverseZetas<>+228(SB)/4, $0x00e706c1e2
DATA dsaInverseZetas<>+232(SB)/4, $0x0035be5529
DATA dsaInverseZetas<>+236(SB)/4, $0x0068524dc2
DATA dsaInverseZetas<>+240(SB)/4, $0x00345e0518
DATA dsaInverseZetas<>+244(SB)/4, $0x009d659229
DATA dsaInverseZetas<>+248(SB)/4, $0x007301c58b
DATA dsaInverseZetas<>+252(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+256(SB)/4, $0x000020e612
DATA dsaInverseZetas<>+260(SB)/4, $0x00003177f4
DATA dsaInverseZetas<>+264(SB)/4, $0x0000428cd4
DATA dsaInverseZetas<>+268(SB)/4, $0x00001f9d15
DATA dsaInverseZetas<>+272(SB)/4, $0x00006b7d81
DATA dsaInverseZetas<>+276(SB)/4, $0x00000a52ee
DATA dsaInverseZetas<>+280(SB)/4, $0x0000207fe4
DATA dsaInverseZetas<>+284(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+288(SB)/4, $0x0041dc9aa2
DATA dsaInverseZetas<>+292(SB)/4, $0x006308a964
DATA dsaInverseZetas<>+296(SB)/4, $0x00853af5b2
DATA dsaInverseZetas<>+300(SB)/4, $0x003f49fc00
DATA dsaInverseZetas<>+304(SB)/4, $0x00d730cc84
DATA dsaInverseZetas<>+308(SB)/4, $0x0014ab0698
DATA dsaInverseZetas<>+312(SB)/4, $0x0041100b80
DATA dsaInverseZetas<>+316(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+320(SB)/4, $0x00004a5f35
DATA dsaInverseZetas<>+324(SB)/4, $0x000010b72c
DATA dsaInverseZetas<>+328(SB)/4, $0x00000e2bed
DATA dsaInverseZetas<>+332(SB)/4, $0x00000603a4
DATA dsaInverseZetas<>+336(SB)/4, $0x0000794034
DATA dsaInverseZetas<>+340(SB)/4, $0x00004a18a7
DATA dsaInverseZetas<>+344(SB)/4, $0x000028edb0
DATA dsaInverseZetas<>+348(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+352(SB)/4, $0x0094e3a1be
DATA dsaInverseZetas<>+356(SB)/4, $0x002176b56a
DATA dsaInverseZetas<>+360(SB)/4, $0x001c5ef183
DATA dsaInverseZetas<>+364(SB)/4, $0x000c0a4a7a
DATA dsaInverseZetas<>+368(SB)/4, $0x00f2bd155f
DATA dsaInverseZetas<>+372(SB)/4, $0x009456626f
DATA dsaInverseZetas<>+376(SB)/4, $0x0051efdb52
DATA dsaInverseZetas<>+380(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+384(SB)/4, $0x000011b2c3
DATA dsaInverseZetas<>+388(SB)/4, $0x00003887f7
DATA dsaInverseZetas<>+392(SB)/4, $0x00002010a2
DATA dsaInverseZetas<>+396(SB)/4, $0x000050685f
DATA dsaInverseZetas<>+400(SB)/4, $0x000066528a
DATA dsaInverseZetas<>+404(SB)/4, $0x000028a3d2
DATA dsaInverseZetas<>+408(SB)/4, $0x0000360dd5
DATA dsaInverseZetas<>+412(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+416(SB)/4, $0x00236e6151
DATA dsaInverseZetas<>+420(SB)/4, $0x00712c382b
DATA dsaInverseZetas<>+424(SB)/4, $0x0040314fd3
DATA dsaInverseZetas<>+428(SB)/4, $0x00a0f8fafc
DATA dsaInverseZetas<>+432(SB)/4, $0x00ccd84878
DATA dsaInverseZetas<>+436(SB)/4, $0x00515bfa5b
DATA dsaInverseZetas<>+440(SB)/4, $0x006c36b6d5
DATA dsaInverseZetas<>+444(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+448(SB)/4, $0x0000492673
DATA dsaInverseZetas<>+452(SB)/4, $0x000029d13f
DATA dsaInverseZetas<>+456(SB)/4, $0x000030911e
DATA dsaInverseZetas<>+460(SB)/4, $0x000036f72a
DATA dsaInverseZetas<>+464(SB)/4, $0x000041e0b4
DATA dsaInverseZetas<>+468(SB)/4, $0x00004c7294
DATA dsaInverseZetas<>+472(SB)/4, $0x000076b1ae
DATA dsaInverseZetas<>+476(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+480(SB)/4, $0x009271813b
DATA dsaInverseZetas<>+484(SB)/4, $0x0053b76b33
DATA dsaInverseZetas<>+488(SB)/4, $0x00613a89e0
DATA dsaInverseZetas<>+492(SB)/4, $0x006e09d599
DATA dsaInverseZetas<>+496(SB)/4, $0x0083e25f90
DATA dsaInverseZetas<>+500(SB)/4, $0x00990b69a8
DATA dsaInverseZetas<>+504(SB)/4, $0x00ed9ec1d5
DATA dsaInverseZetas<>+508(SB)/4, $0x0000000000
DATA dsaInverseZetas<>+512(SB)/4, $0x00004f066b
DATA dsaInverseZetas<>+516(SB)/4, $0x00004fe033
DATA dsaInverseZetas<>+520(SB)/4, $0x000053df73
DATA dsaInverseZetas<>+524(SB)/4, $0x00004f062b
DATA dsaInverseZetas<>+528(SB)/4, $0x0000396569
DATA dsaInverseZetas<>+532(SB)/4, $0x0000397567
DATA dsaInverseZetas<>+536(SB)/4, $0x00007f299f
DATA dsaInverseZetas<>+540(SB)/4, $0x00007f6021
DATA dsaInverseZetas<>+544(SB)/4, $0x009e3461dc
DATA dsaInverseZetas<>+548(SB)/4, $0x009fe85ed7
DATA dsaInverseZetas<>+552(SB)/4, $0x00a7e8dee7
DATA dsaInverseZetas<>+556(SB)/4, $0x009e33e1bc
DATA dsaInverseZetas<>+560(SB)/4, $0x0072e78afc
DATA dsaInverseZetas<>+564(SB)/4, $0x0073078efd
DATA dsaInverseZetas<>+568(SB)/4, $0x00fe92e0bb
DATA dsaInverseZetas<>+572(SB)/4, $0x00ff000002
GLOBL dsaInverseZetas<>(SB), RODATA|NOPTR, $576

DATA dsaConstants<>+0(SB)/4, $0x00007fe001
DATA dsaConstants<>+4(SB)/4, $0x00007fe001
DATA dsaConstants<>+8(SB)/4, $0x00007fe001
DATA dsaConstants<>+12(SB)/4, $0x00007fe001
DATA dsaConstants<>+16(SB)/4, $0x0000ffc002
DATA dsaConstants<>+20(SB)/4, $0x0000ffc002
DATA dsaConstants<>+24(SB)/4, $0x0000ffc002
DATA dsaConstants<>+28(SB)/4, $0x0000ffc002
DATA dsaConstants<>+32(SB)/4, $0x00007fe001
DATA dsaConstants<>+36(SB)/4, $0x00007fe001
DATA dsaConstants<>+40(SB)/4, $0x00007fe001
DATA dsaConstants<>+44(SB)/4, $0x00007fe001
DATA dsaConstants<>+48(SB)/4, $0x0000ffc002
DATA dsaConstants<>+52(SB)/4, $0x0000ffc002
DATA dsaConstants<>+56(SB)/4, $0x0000ffc002
DATA dsaConstants<>+60(SB)/4, $0x0000ffc002
DATA dsaConstants<>+64(SB)/4, $0x0001ff8004
DATA dsaConstants<>+68(SB)/4, $0x0001ff8004
DATA dsaConstants<>+72(SB)/4, $0x0001ff8004
DATA dsaConstants<>+76(SB)/4, $0x0001ff8004
DATA dsaConstants<>+80(SB)/4, $0x0003ff0008
DATA dsaConstants<>+84(SB)/4, $0x0003ff0008
DATA dsaConstants<>+88(SB)/4, $0x0003ff0008
DATA dsaConstants<>+92(SB)/4, $0x0003ff0008
DATA dsaConstants<>+96(SB)/4, $0x0007fe0010
DATA dsaConstants<>+100(SB)/4, $0x0007fe0010
DATA dsaConstants<>+104(SB)/4, $0x0007fe0010
DATA dsaConstants<>+108(SB)/4, $0x0007fe0010
DATA dsaConstants<>+112(SB)/4, $0x000ffc0020
DATA dsaConstants<>+116(SB)/4, $0x000ffc0020
DATA dsaConstants<>+120(SB)/4, $0x000ffc0020
DATA dsaConstants<>+124(SB)/4, $0x000ffc0020
DATA dsaConstants<>+128(SB)/4, $0x001ff80040
DATA dsaConstants<>+132(SB)/4, $0x001ff80040
DATA dsaConstants<>+136(SB)/4, $0x001ff80040
DATA dsaConstants<>+140(SB)/4, $0x001ff80040
DATA dsaConstants<>+144(SB)/4, $0x003ff00080
DATA dsaConstants<>+148(SB)/4, $0x003ff00080
DATA dsaConstants<>+152(SB)/4, $0x003ff00080
DATA dsaConstants<>+156(SB)/4, $0x003ff00080
GLOBL dsaConstants<>(SB), RODATA|NOPTR, $160
