package main

import (
	"bytes"
	"fmt"
)

type asm struct {
	text bytes.Buffer
}

// Every file builds only without the purego tag; its name restricts it to one architecture.
func newAsm() *asm {
	a := &asm{}

	a.text.WriteString("// Code generated by internal/asmgen. DO NOT EDIT.\n\n//go:build !purego\n\n#include \"textflag.h\"\n")

	return a
}

func (a *asm) bytes() []byte {
	return a.text.Bytes()
}

func (a *asm) op(format string, args ...any) {
	fmt.Fprintf(&a.text, "\t"+format+"\n", args...)
}

func (a *asm) label(name string) {
	fmt.Fprintf(&a.text, "%s:\n", name)
}

func (a *asm) comment(lines ...string) {
	for _, line := range lines {
		fmt.Fprintf(&a.text, "// %s\n", line)
	}
}

// Starts a function without a stack frame of its own; args is the size of its arguments and
// results, which go vet checks against the Go declaration.
func (a *asm) function(name, declaration string, args int, notes ...string) {
	a.text.WriteString("\n")

	a.comment(notes...)

	a.comment(declaration)

	fmt.Fprintf(&a.text, "TEXT ·%s(SB), NOSPLIT, $0-%d\n", name, args)
}

// A read-only table of width-byte words, local to the file.
func (a *asm) table(name string, width int, values []uint64) {
	a.text.WriteString("\n")

	for i, value := range values {
		fmt.Fprintf(&a.text, "DATA %s<>+%d(SB)/%d, $%#0*x\n", name, i*width, width, 2+2*width, value)
	}

	fmt.Fprintf(&a.text, "GLOBL %s<>(SB), RODATA|NOPTR, $%d\n", name, len(values)*width)
}
